//
// AnulacionRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AnulacionRequest: Sendable, Codable, Hashable {

    public var cantidaDeNcfAnulados: SearchEcfReceptionRequestsTiposEcfsParameterInner
    public var detalleAnulacion: [DetalleAnulacionRequest]

    public init(cantidaDeNcfAnulados: SearchEcfReceptionRequestsTiposEcfsParameterInner, detalleAnulacion: [DetalleAnulacionRequest]) {
        self.cantidaDeNcfAnulados = cantidaDeNcfAnulados
        self.detalleAnulacion = detalleAnulacion
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case cantidaDeNcfAnulados
        case detalleAnulacion
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(cantidaDeNcfAnulados, forKey: .cantidaDeNcfAnulados)
        try container.encode(detalleAnulacion, forKey: .detalleAnulacion)
    }
}

