//
// Ecf33OtraMonedaDetalle.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Ecf33OtraMonedaDetalle: Sendable, Codable, Hashable {

    public var precioOtraMoneda: Ecf31OtraMonedaDetallePrecioOtraMoneda?
    public var descuentoOtraMoneda: Ecf31DescuentoORecargoMontoDescuentooRecargo?
    public var recargoOtraMoneda: Ecf31DescuentoORecargoMontoDescuentooRecargo?
    public var montoItemOtraMoneda: Ecf31DescuentoORecargoMontoDescuentooRecargo?

    public init(precioOtraMoneda: Ecf31OtraMonedaDetallePrecioOtraMoneda? = nil, descuentoOtraMoneda: Ecf31DescuentoORecargoMontoDescuentooRecargo? = nil, recargoOtraMoneda: Ecf31DescuentoORecargoMontoDescuentooRecargo? = nil, montoItemOtraMoneda: Ecf31DescuentoORecargoMontoDescuentooRecargo? = nil) {
        self.precioOtraMoneda = precioOtraMoneda
        self.descuentoOtraMoneda = descuentoOtraMoneda
        self.recargoOtraMoneda = recargoOtraMoneda
        self.montoItemOtraMoneda = montoItemOtraMoneda
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case precioOtraMoneda
        case descuentoOtraMoneda
        case recargoOtraMoneda
        case montoItemOtraMoneda
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(precioOtraMoneda, forKey: .precioOtraMoneda)
        try container.encodeIfPresent(descuentoOtraMoneda, forKey: .descuentoOtraMoneda)
        try container.encodeIfPresent(recargoOtraMoneda, forKey: .recargoOtraMoneda)
        try container.encodeIfPresent(montoItemOtraMoneda, forKey: .montoItemOtraMoneda)
    }
}

