//
// Ecf32Item.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Ecf32Item: Sendable, Codable, Hashable {

    public var numeroLinea: AcecfReceptionRequestDtoProgress
    public var tablaCodigosItem: [Ecf32CodigosItem]?
    public var indicadorFacturacion: Ecf32IndicadorFacturacionType
    public var nombreItem: String
    public var indicadorBienoServicio: Ecf32IndicadorBienoServicioType
    public var descripcionItem: String?
    public var cantidadItem: Ecf31ItemCantidadItem
    public var unidadMedida: UnidadMedidaType?
    public var cantidadReferencia: Ecf31DescuentoORecargoMontoDescuentooRecargo?
    public var unidadReferencia: UnidadMedidaType?
    public var tablaSubcantidad: [Ecf32SubcantidadItem]?
    public var gradosAlcohol: Ecf31DescuentoORecargoValorDescuentooRecargo?
    public var precioUnitarioReferencia: Ecf31ImpuestoAdicional2MontoImpuestoSelectivoConsumoEspecifico?
    public var fechaElaboracion: Date?
    public var fechaVencimientoItem: Date?
    public var mineria: Ecf32Mineria?
    public var precioUnitarioItem: Ecf31ItemPrecioUnitarioItem
    public var descuentoMonto: Ecf31DescuentoORecargoMontoDescuentooRecargo?
    public var tablaSubDescuento: [Ecf32SubDescuento]?
    public var recargoMonto: Ecf31DescuentoORecargoMontoDescuentooRecargo?
    public var tablaSubRecargo: [Ecf32SubRecargo]?
    public var tablaImpuestoAdicional: [Ecf32ImpuestoAdicional]?
    public var otraMonedaDetalle: Ecf32OtraMonedaDetalle?
    public var montoItem: Ecf31FormaDePagoMontoPago

    public init(numeroLinea: AcecfReceptionRequestDtoProgress, tablaCodigosItem: [Ecf32CodigosItem]? = nil, indicadorFacturacion: Ecf32IndicadorFacturacionType, nombreItem: String, indicadorBienoServicio: Ecf32IndicadorBienoServicioType, descripcionItem: String? = nil, cantidadItem: Ecf31ItemCantidadItem, unidadMedida: UnidadMedidaType? = nil, cantidadReferencia: Ecf31DescuentoORecargoMontoDescuentooRecargo? = nil, unidadReferencia: UnidadMedidaType? = nil, tablaSubcantidad: [Ecf32SubcantidadItem]? = nil, gradosAlcohol: Ecf31DescuentoORecargoValorDescuentooRecargo? = nil, precioUnitarioReferencia: Ecf31ImpuestoAdicional2MontoImpuestoSelectivoConsumoEspecifico? = nil, fechaElaboracion: Date? = nil, fechaVencimientoItem: Date? = nil, mineria: Ecf32Mineria? = nil, precioUnitarioItem: Ecf31ItemPrecioUnitarioItem, descuentoMonto: Ecf31DescuentoORecargoMontoDescuentooRecargo? = nil, tablaSubDescuento: [Ecf32SubDescuento]? = nil, recargoMonto: Ecf31DescuentoORecargoMontoDescuentooRecargo? = nil, tablaSubRecargo: [Ecf32SubRecargo]? = nil, tablaImpuestoAdicional: [Ecf32ImpuestoAdicional]? = nil, otraMonedaDetalle: Ecf32OtraMonedaDetalle? = nil, montoItem: Ecf31FormaDePagoMontoPago) {
        self.numeroLinea = numeroLinea
        self.tablaCodigosItem = tablaCodigosItem
        self.indicadorFacturacion = indicadorFacturacion
        self.nombreItem = nombreItem
        self.indicadorBienoServicio = indicadorBienoServicio
        self.descripcionItem = descripcionItem
        self.cantidadItem = cantidadItem
        self.unidadMedida = unidadMedida
        self.cantidadReferencia = cantidadReferencia
        self.unidadReferencia = unidadReferencia
        self.tablaSubcantidad = tablaSubcantidad
        self.gradosAlcohol = gradosAlcohol
        self.precioUnitarioReferencia = precioUnitarioReferencia
        self.fechaElaboracion = fechaElaboracion
        self.fechaVencimientoItem = fechaVencimientoItem
        self.mineria = mineria
        self.precioUnitarioItem = precioUnitarioItem
        self.descuentoMonto = descuentoMonto
        self.tablaSubDescuento = tablaSubDescuento
        self.recargoMonto = recargoMonto
        self.tablaSubRecargo = tablaSubRecargo
        self.tablaImpuestoAdicional = tablaImpuestoAdicional
        self.otraMonedaDetalle = otraMonedaDetalle
        self.montoItem = montoItem
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case numeroLinea
        case tablaCodigosItem
        case indicadorFacturacion
        case nombreItem
        case indicadorBienoServicio
        case descripcionItem
        case cantidadItem
        case unidadMedida
        case cantidadReferencia
        case unidadReferencia
        case tablaSubcantidad
        case gradosAlcohol
        case precioUnitarioReferencia
        case fechaElaboracion
        case fechaVencimientoItem
        case mineria
        case precioUnitarioItem
        case descuentoMonto
        case tablaSubDescuento
        case recargoMonto
        case tablaSubRecargo
        case tablaImpuestoAdicional
        case otraMonedaDetalle
        case montoItem
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(numeroLinea, forKey: .numeroLinea)
        try container.encodeIfPresent(tablaCodigosItem, forKey: .tablaCodigosItem)
        try container.encode(indicadorFacturacion, forKey: .indicadorFacturacion)
        try container.encode(nombreItem, forKey: .nombreItem)
        try container.encode(indicadorBienoServicio, forKey: .indicadorBienoServicio)
        try container.encodeIfPresent(descripcionItem, forKey: .descripcionItem)
        try container.encode(cantidadItem, forKey: .cantidadItem)
        try container.encodeIfPresent(unidadMedida, forKey: .unidadMedida)
        try container.encodeIfPresent(cantidadReferencia, forKey: .cantidadReferencia)
        try container.encodeIfPresent(unidadReferencia, forKey: .unidadReferencia)
        try container.encodeIfPresent(tablaSubcantidad, forKey: .tablaSubcantidad)
        try container.encodeIfPresent(gradosAlcohol, forKey: .gradosAlcohol)
        try container.encodeIfPresent(precioUnitarioReferencia, forKey: .precioUnitarioReferencia)
        try container.encodeIfPresent(fechaElaboracion, forKey: .fechaElaboracion)
        try container.encodeIfPresent(fechaVencimientoItem, forKey: .fechaVencimientoItem)
        try container.encodeIfPresent(mineria, forKey: .mineria)
        try container.encode(precioUnitarioItem, forKey: .precioUnitarioItem)
        try container.encodeIfPresent(descuentoMonto, forKey: .descuentoMonto)
        try container.encodeIfPresent(tablaSubDescuento, forKey: .tablaSubDescuento)
        try container.encodeIfPresent(recargoMonto, forKey: .recargoMonto)
        try container.encodeIfPresent(tablaSubRecargo, forKey: .tablaSubRecargo)
        try container.encodeIfPresent(tablaImpuestoAdicional, forKey: .tablaImpuestoAdicional)
        try container.encodeIfPresent(otraMonedaDetalle, forKey: .otraMonedaDetalle)
        try container.encode(montoItem, forKey: .montoItem)
    }
}

