//
// Ecf43Pagina.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Ecf43Pagina: Sendable, Codable, Hashable {

    public var paginaNo: Ecf31IdDocTotalPaginas?
    public var noLineaDesde: Ecf31IdDocTotalPaginas?
    public var noLineaHasta: Ecf31IdDocTotalPaginas?
    public var subtotalExentoPagina: Ecf31DescuentoORecargoMontoDescuentooRecargo?
    public var montoSubtotalPagina: Ecf31DescuentoORecargoMontoDescuentooRecargo?

    public init(paginaNo: Ecf31IdDocTotalPaginas? = nil, noLineaDesde: Ecf31IdDocTotalPaginas? = nil, noLineaHasta: Ecf31IdDocTotalPaginas? = nil, subtotalExentoPagina: Ecf31DescuentoORecargoMontoDescuentooRecargo? = nil, montoSubtotalPagina: Ecf31DescuentoORecargoMontoDescuentooRecargo? = nil) {
        self.paginaNo = paginaNo
        self.noLineaDesde = noLineaDesde
        self.noLineaHasta = noLineaHasta
        self.subtotalExentoPagina = subtotalExentoPagina
        self.montoSubtotalPagina = montoSubtotalPagina
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case paginaNo
        case noLineaDesde
        case noLineaHasta
        case subtotalExentoPagina
        case montoSubtotalPagina
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(paginaNo, forKey: .paginaNo)
        try container.encodeIfPresent(noLineaDesde, forKey: .noLineaDesde)
        try container.encodeIfPresent(noLineaHasta, forKey: .noLineaHasta)
        try container.encodeIfPresent(subtotalExentoPagina, forKey: .subtotalExentoPagina)
        try container.encodeIfPresent(montoSubtotalPagina, forKey: .montoSubtotalPagina)
    }
}

