//
// Ecf44OtraMoneda.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Ecf44OtraMoneda: Sendable, Codable, Hashable {

    public var tipoMoneda: TipoMonedaType?
    public var tipoCambio: Ecf31OtraMonedaTipoCambio?
    public var montoExentoOtraMoneda: Ecf31DescuentoORecargoMontoDescuentooRecargo?
    public var montoImpuestoAdicionalOtraMoneda: Ecf31ImpuestoAdicional2MontoImpuestoSelectivoConsumoEspecifico?
    public var impuestosAdicionalesOtraMoneda: [Ecf44ImpuestoAdicionalOtraMoneda]?
    public var montoTotalOtraMoneda: Ecf31DescuentoORecargoMontoDescuentooRecargo?

    public init(tipoMoneda: TipoMonedaType? = nil, tipoCambio: Ecf31OtraMonedaTipoCambio? = nil, montoExentoOtraMoneda: Ecf31DescuentoORecargoMontoDescuentooRecargo? = nil, montoImpuestoAdicionalOtraMoneda: Ecf31ImpuestoAdicional2MontoImpuestoSelectivoConsumoEspecifico? = nil, impuestosAdicionalesOtraMoneda: [Ecf44ImpuestoAdicionalOtraMoneda]? = nil, montoTotalOtraMoneda: Ecf31DescuentoORecargoMontoDescuentooRecargo? = nil) {
        self.tipoMoneda = tipoMoneda
        self.tipoCambio = tipoCambio
        self.montoExentoOtraMoneda = montoExentoOtraMoneda
        self.montoImpuestoAdicionalOtraMoneda = montoImpuestoAdicionalOtraMoneda
        self.impuestosAdicionalesOtraMoneda = impuestosAdicionalesOtraMoneda
        self.montoTotalOtraMoneda = montoTotalOtraMoneda
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case tipoMoneda
        case tipoCambio
        case montoExentoOtraMoneda
        case montoImpuestoAdicionalOtraMoneda
        case impuestosAdicionalesOtraMoneda
        case montoTotalOtraMoneda
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(tipoMoneda, forKey: .tipoMoneda)
        try container.encodeIfPresent(tipoCambio, forKey: .tipoCambio)
        try container.encodeIfPresent(montoExentoOtraMoneda, forKey: .montoExentoOtraMoneda)
        try container.encodeIfPresent(montoImpuestoAdicionalOtraMoneda, forKey: .montoImpuestoAdicionalOtraMoneda)
        try container.encodeIfPresent(impuestosAdicionalesOtraMoneda, forKey: .impuestosAdicionalesOtraMoneda)
        try container.encodeIfPresent(montoTotalOtraMoneda, forKey: .montoTotalOtraMoneda)
    }
}

