//
// Ecf44ImpuestoAdicional.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Ecf44ImpuestoAdicional: Sendable, Codable, Hashable {

    public var tipoImpuesto: Ecf44CodificacionTipoImpuestosType

    public init(tipoImpuesto: Ecf44CodificacionTipoImpuestosType) {
        self.tipoImpuesto = tipoImpuesto
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case tipoImpuesto
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(tipoImpuesto, forKey: .tipoImpuesto)
    }
}

