//
// EcfReceptorDtoEstado.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Estado from the generated ARECF (ECFRecibido / ECFNoRecibido). */
public struct EcfReceptorDtoEstado: Sendable, Codable, Hashable {


    public enum CodingKeys: CodingKey, CaseIterable {
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
    }
}

