//
// OtraMoneda.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct OtraMoneda: Sendable, Codable, Hashable {

    public static let tipoCambioRule = NumericRule<Double>(minimum: 0.01, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public static let montoExentoOtraMonedaRule = NumericRule<Double>(minimum: 0, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public static let montoTotalOtraMonedaRule = NumericRule<Double>(minimum: 0, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public var tipoMoneda: TipoMonedaType?
    public var tipoCambio: Double?
    public var montoExentoOtraMoneda: Double?
    public var montoTotalOtraMoneda: Double?

    public init(tipoMoneda: TipoMonedaType? = nil, tipoCambio: Double? = nil, montoExentoOtraMoneda: Double? = nil, montoTotalOtraMoneda: Double? = nil) {
        self.tipoMoneda = tipoMoneda
        self.tipoCambio = tipoCambio
        self.montoExentoOtraMoneda = montoExentoOtraMoneda
        self.montoTotalOtraMoneda = montoTotalOtraMoneda
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case tipoMoneda
        case tipoCambio
        case montoExentoOtraMoneda
        case montoTotalOtraMoneda
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(tipoMoneda, forKey: .tipoMoneda)
        try container.encodeIfPresent(tipoCambio, forKey: .tipoCambio)
        try container.encodeIfPresent(montoExentoOtraMoneda, forKey: .montoExentoOtraMoneda)
        try container.encodeIfPresent(montoTotalOtraMoneda, forKey: .montoTotalOtraMoneda)
    }
}

