//
// Retencion.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Retencion: Sendable, Codable, Hashable {

    public static let montoISRRetenidoRule = NumericRule<Double>(minimum: 0, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public var indicadorAgenteRetencionoPercepcion: IndicadorAgenteRetencionoPercepcionType
    public var montoISRRetenido: Double

    public init(indicadorAgenteRetencionoPercepcion: IndicadorAgenteRetencionoPercepcionType, montoISRRetenido: Double) {
        self.indicadorAgenteRetencionoPercepcion = indicadorAgenteRetencionoPercepcion
        self.montoISRRetenido = montoISRRetenido
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case indicadorAgenteRetencionoPercepcion
        case montoISRRetenido
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(indicadorAgenteRetencionoPercepcion, forKey: .indicadorAgenteRetencionoPercepcion)
        try container.encode(montoISRRetenido, forKey: .montoISRRetenido)
    }
}

