//
// TipoMonedaType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum TipoMonedaType: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
    case brl = "BRL"
    case cad = "CAD"
    case chf = "CHF"
    case chy = "CHY"
    case xdr = "XDR"
    case dkk = "DKK"
    case eur = "EUR"
    case gbp = "GBP"
    case jpy = "JPY"
    case nok = "NOK"
    case scp = "SCP"
    case sek = "SEK"
    case usd = "USD"
    case vef = "VEF"
    case htg = "HTG"
    case mxn = "MXN"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}
