/*
 * ECF API
 * ECF API (Electronic Fiscal Receipt).
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dom.com.ssd.ecfx.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import dom.com.ssd.ecfx.client.model.Ecf31ImpuestoAdicional2MontoImpuestoSelectivoConsumoEspecifico;
import dom.com.ssd.ecfx.client.model.Ecf31ImpuestoAdicional2TasaImpuestoAdicional;
import dom.com.ssd.ecfx.client.model.Ecf34CodificacionTipoImpuestosType;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import dom.com.ssd.ecfx.client.JSON;

/**
 * Ecf34ImpuestoAdicionalOtraMoneda
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.20.0")
public class Ecf34ImpuestoAdicionalOtraMoneda {
  public static final String SERIALIZED_NAME_TIPO_IMPUESTO_OTRA_MONEDA = "tipoImpuestoOtraMoneda";
  @SerializedName(SERIALIZED_NAME_TIPO_IMPUESTO_OTRA_MONEDA)
  @javax.annotation.Nonnull
  private Ecf34CodificacionTipoImpuestosType tipoImpuestoOtraMoneda;

  public static final String SERIALIZED_NAME_TASA_IMPUESTO_ADICIONAL_OTRA_MONEDA = "tasaImpuestoAdicionalOtraMoneda";
  @SerializedName(SERIALIZED_NAME_TASA_IMPUESTO_ADICIONAL_OTRA_MONEDA)
  @javax.annotation.Nonnull
  private Ecf31ImpuestoAdicional2TasaImpuestoAdicional tasaImpuestoAdicionalOtraMoneda;

  public static final String SERIALIZED_NAME_MONTO_IMPUESTO_SELECTIVO_CONSUMO_ESPECIFICO_OTRA_MONEDA = "montoImpuestoSelectivoConsumoEspecificoOtraMoneda";
  @SerializedName(SERIALIZED_NAME_MONTO_IMPUESTO_SELECTIVO_CONSUMO_ESPECIFICO_OTRA_MONEDA)
  @javax.annotation.Nullable
  private Ecf31ImpuestoAdicional2MontoImpuestoSelectivoConsumoEspecifico montoImpuestoSelectivoConsumoEspecificoOtraMoneda;

  public static final String SERIALIZED_NAME_MONTO_IMPUESTO_SELECTIVO_CONSUMO_ADVALOREM_OTRA_MONEDA = "montoImpuestoSelectivoConsumoAdvaloremOtraMoneda";
  @SerializedName(SERIALIZED_NAME_MONTO_IMPUESTO_SELECTIVO_CONSUMO_ADVALOREM_OTRA_MONEDA)
  @javax.annotation.Nullable
  private Ecf31ImpuestoAdicional2MontoImpuestoSelectivoConsumoEspecifico montoImpuestoSelectivoConsumoAdvaloremOtraMoneda;

  public static final String SERIALIZED_NAME_OTROS_IMPUESTOS_ADICIONALES_OTRA_MONEDA = "otrosImpuestosAdicionalesOtraMoneda";
  @SerializedName(SERIALIZED_NAME_OTROS_IMPUESTOS_ADICIONALES_OTRA_MONEDA)
  @javax.annotation.Nullable
  private Ecf31ImpuestoAdicional2MontoImpuestoSelectivoConsumoEspecifico otrosImpuestosAdicionalesOtraMoneda;

  public Ecf34ImpuestoAdicionalOtraMoneda() {
  }

  public Ecf34ImpuestoAdicionalOtraMoneda tipoImpuestoOtraMoneda(@javax.annotation.Nonnull Ecf34CodificacionTipoImpuestosType tipoImpuestoOtraMoneda) {
    this.tipoImpuestoOtraMoneda = tipoImpuestoOtraMoneda;
    return this;
  }

  /**
   * Get tipoImpuestoOtraMoneda
   * @return tipoImpuestoOtraMoneda
   */
  @javax.annotation.Nonnull
  public Ecf34CodificacionTipoImpuestosType getTipoImpuestoOtraMoneda() {
    return tipoImpuestoOtraMoneda;
  }

  public void setTipoImpuestoOtraMoneda(@javax.annotation.Nonnull Ecf34CodificacionTipoImpuestosType tipoImpuestoOtraMoneda) {
    this.tipoImpuestoOtraMoneda = tipoImpuestoOtraMoneda;
  }


  public Ecf34ImpuestoAdicionalOtraMoneda tasaImpuestoAdicionalOtraMoneda(@javax.annotation.Nonnull Ecf31ImpuestoAdicional2TasaImpuestoAdicional tasaImpuestoAdicionalOtraMoneda) {
    this.tasaImpuestoAdicionalOtraMoneda = tasaImpuestoAdicionalOtraMoneda;
    return this;
  }

  /**
   * Get tasaImpuestoAdicionalOtraMoneda
   * @return tasaImpuestoAdicionalOtraMoneda
   */
  @javax.annotation.Nonnull
  public Ecf31ImpuestoAdicional2TasaImpuestoAdicional getTasaImpuestoAdicionalOtraMoneda() {
    return tasaImpuestoAdicionalOtraMoneda;
  }

  public void setTasaImpuestoAdicionalOtraMoneda(@javax.annotation.Nonnull Ecf31ImpuestoAdicional2TasaImpuestoAdicional tasaImpuestoAdicionalOtraMoneda) {
    this.tasaImpuestoAdicionalOtraMoneda = tasaImpuestoAdicionalOtraMoneda;
  }


  public Ecf34ImpuestoAdicionalOtraMoneda montoImpuestoSelectivoConsumoEspecificoOtraMoneda(@javax.annotation.Nullable Ecf31ImpuestoAdicional2MontoImpuestoSelectivoConsumoEspecifico montoImpuestoSelectivoConsumoEspecificoOtraMoneda) {
    this.montoImpuestoSelectivoConsumoEspecificoOtraMoneda = montoImpuestoSelectivoConsumoEspecificoOtraMoneda;
    return this;
  }

  /**
   * Get montoImpuestoSelectivoConsumoEspecificoOtraMoneda
   * @return montoImpuestoSelectivoConsumoEspecificoOtraMoneda
   */
  @javax.annotation.Nullable
  public Ecf31ImpuestoAdicional2MontoImpuestoSelectivoConsumoEspecifico getMontoImpuestoSelectivoConsumoEspecificoOtraMoneda() {
    return montoImpuestoSelectivoConsumoEspecificoOtraMoneda;
  }

  public void setMontoImpuestoSelectivoConsumoEspecificoOtraMoneda(@javax.annotation.Nullable Ecf31ImpuestoAdicional2MontoImpuestoSelectivoConsumoEspecifico montoImpuestoSelectivoConsumoEspecificoOtraMoneda) {
    this.montoImpuestoSelectivoConsumoEspecificoOtraMoneda = montoImpuestoSelectivoConsumoEspecificoOtraMoneda;
  }


  public Ecf34ImpuestoAdicionalOtraMoneda montoImpuestoSelectivoConsumoAdvaloremOtraMoneda(@javax.annotation.Nullable Ecf31ImpuestoAdicional2MontoImpuestoSelectivoConsumoEspecifico montoImpuestoSelectivoConsumoAdvaloremOtraMoneda) {
    this.montoImpuestoSelectivoConsumoAdvaloremOtraMoneda = montoImpuestoSelectivoConsumoAdvaloremOtraMoneda;
    return this;
  }

  /**
   * Get montoImpuestoSelectivoConsumoAdvaloremOtraMoneda
   * @return montoImpuestoSelectivoConsumoAdvaloremOtraMoneda
   */
  @javax.annotation.Nullable
  public Ecf31ImpuestoAdicional2MontoImpuestoSelectivoConsumoEspecifico getMontoImpuestoSelectivoConsumoAdvaloremOtraMoneda() {
    return montoImpuestoSelectivoConsumoAdvaloremOtraMoneda;
  }

  public void setMontoImpuestoSelectivoConsumoAdvaloremOtraMoneda(@javax.annotation.Nullable Ecf31ImpuestoAdicional2MontoImpuestoSelectivoConsumoEspecifico montoImpuestoSelectivoConsumoAdvaloremOtraMoneda) {
    this.montoImpuestoSelectivoConsumoAdvaloremOtraMoneda = montoImpuestoSelectivoConsumoAdvaloremOtraMoneda;
  }


  public Ecf34ImpuestoAdicionalOtraMoneda otrosImpuestosAdicionalesOtraMoneda(@javax.annotation.Nullable Ecf31ImpuestoAdicional2MontoImpuestoSelectivoConsumoEspecifico otrosImpuestosAdicionalesOtraMoneda) {
    this.otrosImpuestosAdicionalesOtraMoneda = otrosImpuestosAdicionalesOtraMoneda;
    return this;
  }

  /**
   * Get otrosImpuestosAdicionalesOtraMoneda
   * @return otrosImpuestosAdicionalesOtraMoneda
   */
  @javax.annotation.Nullable
  public Ecf31ImpuestoAdicional2MontoImpuestoSelectivoConsumoEspecifico getOtrosImpuestosAdicionalesOtraMoneda() {
    return otrosImpuestosAdicionalesOtraMoneda;
  }

  public void setOtrosImpuestosAdicionalesOtraMoneda(@javax.annotation.Nullable Ecf31ImpuestoAdicional2MontoImpuestoSelectivoConsumoEspecifico otrosImpuestosAdicionalesOtraMoneda) {
    this.otrosImpuestosAdicionalesOtraMoneda = otrosImpuestosAdicionalesOtraMoneda;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Ecf34ImpuestoAdicionalOtraMoneda ecf34ImpuestoAdicionalOtraMoneda = (Ecf34ImpuestoAdicionalOtraMoneda) o;
    return Objects.equals(this.tipoImpuestoOtraMoneda, ecf34ImpuestoAdicionalOtraMoneda.tipoImpuestoOtraMoneda) &&
        Objects.equals(this.tasaImpuestoAdicionalOtraMoneda, ecf34ImpuestoAdicionalOtraMoneda.tasaImpuestoAdicionalOtraMoneda) &&
        Objects.equals(this.montoImpuestoSelectivoConsumoEspecificoOtraMoneda, ecf34ImpuestoAdicionalOtraMoneda.montoImpuestoSelectivoConsumoEspecificoOtraMoneda) &&
        Objects.equals(this.montoImpuestoSelectivoConsumoAdvaloremOtraMoneda, ecf34ImpuestoAdicionalOtraMoneda.montoImpuestoSelectivoConsumoAdvaloremOtraMoneda) &&
        Objects.equals(this.otrosImpuestosAdicionalesOtraMoneda, ecf34ImpuestoAdicionalOtraMoneda.otrosImpuestosAdicionalesOtraMoneda);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tipoImpuestoOtraMoneda, tasaImpuestoAdicionalOtraMoneda, montoImpuestoSelectivoConsumoEspecificoOtraMoneda, montoImpuestoSelectivoConsumoAdvaloremOtraMoneda, otrosImpuestosAdicionalesOtraMoneda);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Ecf34ImpuestoAdicionalOtraMoneda {\n");
    sb.append("    tipoImpuestoOtraMoneda: ").append(toIndentedString(tipoImpuestoOtraMoneda)).append("\n");
    sb.append("    tasaImpuestoAdicionalOtraMoneda: ").append(toIndentedString(tasaImpuestoAdicionalOtraMoneda)).append("\n");
    sb.append("    montoImpuestoSelectivoConsumoEspecificoOtraMoneda: ").append(toIndentedString(montoImpuestoSelectivoConsumoEspecificoOtraMoneda)).append("\n");
    sb.append("    montoImpuestoSelectivoConsumoAdvaloremOtraMoneda: ").append(toIndentedString(montoImpuestoSelectivoConsumoAdvaloremOtraMoneda)).append("\n");
    sb.append("    otrosImpuestosAdicionalesOtraMoneda: ").append(toIndentedString(otrosImpuestosAdicionalesOtraMoneda)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("tipoImpuestoOtraMoneda", "tasaImpuestoAdicionalOtraMoneda", "montoImpuestoSelectivoConsumoEspecificoOtraMoneda", "montoImpuestoSelectivoConsumoAdvaloremOtraMoneda", "otrosImpuestosAdicionalesOtraMoneda"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("tipoImpuestoOtraMoneda", "tasaImpuestoAdicionalOtraMoneda"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to Ecf34ImpuestoAdicionalOtraMoneda
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!Ecf34ImpuestoAdicionalOtraMoneda.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in Ecf34ImpuestoAdicionalOtraMoneda is not found in the empty JSON string", Ecf34ImpuestoAdicionalOtraMoneda.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!Ecf34ImpuestoAdicionalOtraMoneda.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `Ecf34ImpuestoAdicionalOtraMoneda` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : Ecf34ImpuestoAdicionalOtraMoneda.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the required field `tipoImpuestoOtraMoneda`
      Ecf34CodificacionTipoImpuestosType.validateJsonElement(jsonObj.get("tipoImpuestoOtraMoneda"));
      // validate the required field `tasaImpuestoAdicionalOtraMoneda`
      Ecf31ImpuestoAdicional2TasaImpuestoAdicional.validateJsonElement(jsonObj.get("tasaImpuestoAdicionalOtraMoneda"));
      // validate the optional field `montoImpuestoSelectivoConsumoEspecificoOtraMoneda`
      if (jsonObj.get("montoImpuestoSelectivoConsumoEspecificoOtraMoneda") != null && !jsonObj.get("montoImpuestoSelectivoConsumoEspecificoOtraMoneda").isJsonNull()) {
        Ecf31ImpuestoAdicional2MontoImpuestoSelectivoConsumoEspecifico.validateJsonElement(jsonObj.get("montoImpuestoSelectivoConsumoEspecificoOtraMoneda"));
      }
      // validate the optional field `montoImpuestoSelectivoConsumoAdvaloremOtraMoneda`
      if (jsonObj.get("montoImpuestoSelectivoConsumoAdvaloremOtraMoneda") != null && !jsonObj.get("montoImpuestoSelectivoConsumoAdvaloremOtraMoneda").isJsonNull()) {
        Ecf31ImpuestoAdicional2MontoImpuestoSelectivoConsumoEspecifico.validateJsonElement(jsonObj.get("montoImpuestoSelectivoConsumoAdvaloremOtraMoneda"));
      }
      // validate the optional field `otrosImpuestosAdicionalesOtraMoneda`
      if (jsonObj.get("otrosImpuestosAdicionalesOtraMoneda") != null && !jsonObj.get("otrosImpuestosAdicionalesOtraMoneda").isJsonNull()) {
        Ecf31ImpuestoAdicional2MontoImpuestoSelectivoConsumoEspecifico.validateJsonElement(jsonObj.get("otrosImpuestosAdicionalesOtraMoneda"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Ecf34ImpuestoAdicionalOtraMoneda.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Ecf34ImpuestoAdicionalOtraMoneda' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Ecf34ImpuestoAdicionalOtraMoneda> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Ecf34ImpuestoAdicionalOtraMoneda.class));

       return (TypeAdapter<T>) new TypeAdapter<Ecf34ImpuestoAdicionalOtraMoneda>() {
           @Override
           public void write(JsonWriter out, Ecf34ImpuestoAdicionalOtraMoneda value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public Ecf34ImpuestoAdicionalOtraMoneda read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of Ecf34ImpuestoAdicionalOtraMoneda given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of Ecf34ImpuestoAdicionalOtraMoneda
   * @throws IOException if the JSON string is invalid with respect to Ecf34ImpuestoAdicionalOtraMoneda
   */
  public static Ecf34ImpuestoAdicionalOtraMoneda fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Ecf34ImpuestoAdicionalOtraMoneda.class);
  }

  /**
   * Convert an instance of Ecf34ImpuestoAdicionalOtraMoneda to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

