/*
 * ECF API
 * ECF API (Electronic Fiscal Receipt).
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dom.com.ssd.ecfx.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import dom.com.ssd.ecfx.client.model.Ecf32Comprador;
import dom.com.ssd.ecfx.client.model.Ecf32Emisor;
import dom.com.ssd.ecfx.client.model.Ecf32IdDoc;
import dom.com.ssd.ecfx.client.model.Ecf32InformacionesAdicionales;
import dom.com.ssd.ecfx.client.model.Ecf32OtraMoneda;
import dom.com.ssd.ecfx.client.model.Ecf32Totales;
import dom.com.ssd.ecfx.client.model.Ecf32Transporte;
import dom.com.ssd.ecfx.client.model.Ecf32VersionType;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import dom.com.ssd.ecfx.client.JSON;

/**
 * Ecf32Encabezado
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.20.0")
public class Ecf32Encabezado {
  public static final String SERIALIZED_NAME_VERSION = "version";
  @SerializedName(SERIALIZED_NAME_VERSION)
  @javax.annotation.Nonnull
  private Ecf32VersionType version;

  public static final String SERIALIZED_NAME_ID_DOC = "idDoc";
  @SerializedName(SERIALIZED_NAME_ID_DOC)
  @javax.annotation.Nonnull
  private Ecf32IdDoc idDoc;

  public static final String SERIALIZED_NAME_EMISOR = "emisor";
  @SerializedName(SERIALIZED_NAME_EMISOR)
  @javax.annotation.Nonnull
  private Ecf32Emisor emisor;

  public static final String SERIALIZED_NAME_COMPRADOR = "comprador";
  @SerializedName(SERIALIZED_NAME_COMPRADOR)
  @javax.annotation.Nonnull
  private Ecf32Comprador comprador;

  public static final String SERIALIZED_NAME_INFORMACIONES_ADICIONALES = "informacionesAdicionales";
  @SerializedName(SERIALIZED_NAME_INFORMACIONES_ADICIONALES)
  @javax.annotation.Nullable
  private Ecf32InformacionesAdicionales informacionesAdicionales;

  public static final String SERIALIZED_NAME_TRANSPORTE = "transporte";
  @SerializedName(SERIALIZED_NAME_TRANSPORTE)
  @javax.annotation.Nullable
  private Ecf32Transporte transporte;

  public static final String SERIALIZED_NAME_TOTALES = "totales";
  @SerializedName(SERIALIZED_NAME_TOTALES)
  @javax.annotation.Nonnull
  private Ecf32Totales totales;

  public static final String SERIALIZED_NAME_OTRA_MONEDA = "otraMoneda";
  @SerializedName(SERIALIZED_NAME_OTRA_MONEDA)
  @javax.annotation.Nullable
  private Ecf32OtraMoneda otraMoneda;

  public Ecf32Encabezado() {
  }

  public Ecf32Encabezado version(@javax.annotation.Nonnull Ecf32VersionType version) {
    this.version = version;
    return this;
  }

  /**
   * Get version
   * @return version
   */
  @javax.annotation.Nonnull
  public Ecf32VersionType getVersion() {
    return version;
  }

  public void setVersion(@javax.annotation.Nonnull Ecf32VersionType version) {
    this.version = version;
  }


  public Ecf32Encabezado idDoc(@javax.annotation.Nonnull Ecf32IdDoc idDoc) {
    this.idDoc = idDoc;
    return this;
  }

  /**
   * Get idDoc
   * @return idDoc
   */
  @javax.annotation.Nonnull
  public Ecf32IdDoc getIdDoc() {
    return idDoc;
  }

  public void setIdDoc(@javax.annotation.Nonnull Ecf32IdDoc idDoc) {
    this.idDoc = idDoc;
  }


  public Ecf32Encabezado emisor(@javax.annotation.Nonnull Ecf32Emisor emisor) {
    this.emisor = emisor;
    return this;
  }

  /**
   * Get emisor
   * @return emisor
   */
  @javax.annotation.Nonnull
  public Ecf32Emisor getEmisor() {
    return emisor;
  }

  public void setEmisor(@javax.annotation.Nonnull Ecf32Emisor emisor) {
    this.emisor = emisor;
  }


  public Ecf32Encabezado comprador(@javax.annotation.Nonnull Ecf32Comprador comprador) {
    this.comprador = comprador;
    return this;
  }

  /**
   * Get comprador
   * @return comprador
   */
  @javax.annotation.Nonnull
  public Ecf32Comprador getComprador() {
    return comprador;
  }

  public void setComprador(@javax.annotation.Nonnull Ecf32Comprador comprador) {
    this.comprador = comprador;
  }


  public Ecf32Encabezado informacionesAdicionales(@javax.annotation.Nullable Ecf32InformacionesAdicionales informacionesAdicionales) {
    this.informacionesAdicionales = informacionesAdicionales;
    return this;
  }

  /**
   * Get informacionesAdicionales
   * @return informacionesAdicionales
   */
  @javax.annotation.Nullable
  public Ecf32InformacionesAdicionales getInformacionesAdicionales() {
    return informacionesAdicionales;
  }

  public void setInformacionesAdicionales(@javax.annotation.Nullable Ecf32InformacionesAdicionales informacionesAdicionales) {
    this.informacionesAdicionales = informacionesAdicionales;
  }


  public Ecf32Encabezado transporte(@javax.annotation.Nullable Ecf32Transporte transporte) {
    this.transporte = transporte;
    return this;
  }

  /**
   * Get transporte
   * @return transporte
   */
  @javax.annotation.Nullable
  public Ecf32Transporte getTransporte() {
    return transporte;
  }

  public void setTransporte(@javax.annotation.Nullable Ecf32Transporte transporte) {
    this.transporte = transporte;
  }


  public Ecf32Encabezado totales(@javax.annotation.Nonnull Ecf32Totales totales) {
    this.totales = totales;
    return this;
  }

  /**
   * Get totales
   * @return totales
   */
  @javax.annotation.Nonnull
  public Ecf32Totales getTotales() {
    return totales;
  }

  public void setTotales(@javax.annotation.Nonnull Ecf32Totales totales) {
    this.totales = totales;
  }


  public Ecf32Encabezado otraMoneda(@javax.annotation.Nullable Ecf32OtraMoneda otraMoneda) {
    this.otraMoneda = otraMoneda;
    return this;
  }

  /**
   * Get otraMoneda
   * @return otraMoneda
   */
  @javax.annotation.Nullable
  public Ecf32OtraMoneda getOtraMoneda() {
    return otraMoneda;
  }

  public void setOtraMoneda(@javax.annotation.Nullable Ecf32OtraMoneda otraMoneda) {
    this.otraMoneda = otraMoneda;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Ecf32Encabezado ecf32Encabezado = (Ecf32Encabezado) o;
    return Objects.equals(this.version, ecf32Encabezado.version) &&
        Objects.equals(this.idDoc, ecf32Encabezado.idDoc) &&
        Objects.equals(this.emisor, ecf32Encabezado.emisor) &&
        Objects.equals(this.comprador, ecf32Encabezado.comprador) &&
        Objects.equals(this.informacionesAdicionales, ecf32Encabezado.informacionesAdicionales) &&
        Objects.equals(this.transporte, ecf32Encabezado.transporte) &&
        Objects.equals(this.totales, ecf32Encabezado.totales) &&
        Objects.equals(this.otraMoneda, ecf32Encabezado.otraMoneda);
  }

  @Override
  public int hashCode() {
    return Objects.hash(version, idDoc, emisor, comprador, informacionesAdicionales, transporte, totales, otraMoneda);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Ecf32Encabezado {\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    idDoc: ").append(toIndentedString(idDoc)).append("\n");
    sb.append("    emisor: ").append(toIndentedString(emisor)).append("\n");
    sb.append("    comprador: ").append(toIndentedString(comprador)).append("\n");
    sb.append("    informacionesAdicionales: ").append(toIndentedString(informacionesAdicionales)).append("\n");
    sb.append("    transporte: ").append(toIndentedString(transporte)).append("\n");
    sb.append("    totales: ").append(toIndentedString(totales)).append("\n");
    sb.append("    otraMoneda: ").append(toIndentedString(otraMoneda)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("version", "idDoc", "emisor", "comprador", "informacionesAdicionales", "transporte", "totales", "otraMoneda"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("version", "idDoc", "emisor", "comprador", "totales"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to Ecf32Encabezado
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!Ecf32Encabezado.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in Ecf32Encabezado is not found in the empty JSON string", Ecf32Encabezado.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!Ecf32Encabezado.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `Ecf32Encabezado` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : Ecf32Encabezado.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the required field `version`
      Ecf32VersionType.validateJsonElement(jsonObj.get("version"));
      // validate the required field `idDoc`
      Ecf32IdDoc.validateJsonElement(jsonObj.get("idDoc"));
      // validate the required field `emisor`
      Ecf32Emisor.validateJsonElement(jsonObj.get("emisor"));
      // validate the required field `comprador`
      Ecf32Comprador.validateJsonElement(jsonObj.get("comprador"));
      // validate the optional field `informacionesAdicionales`
      if (jsonObj.get("informacionesAdicionales") != null && !jsonObj.get("informacionesAdicionales").isJsonNull()) {
        Ecf32InformacionesAdicionales.validateJsonElement(jsonObj.get("informacionesAdicionales"));
      }
      // validate the optional field `transporte`
      if (jsonObj.get("transporte") != null && !jsonObj.get("transporte").isJsonNull()) {
        Ecf32Transporte.validateJsonElement(jsonObj.get("transporte"));
      }
      // validate the required field `totales`
      Ecf32Totales.validateJsonElement(jsonObj.get("totales"));
      // validate the optional field `otraMoneda`
      if (jsonObj.get("otraMoneda") != null && !jsonObj.get("otraMoneda").isJsonNull()) {
        Ecf32OtraMoneda.validateJsonElement(jsonObj.get("otraMoneda"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Ecf32Encabezado.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Ecf32Encabezado' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Ecf32Encabezado> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Ecf32Encabezado.class));

       return (TypeAdapter<T>) new TypeAdapter<Ecf32Encabezado>() {
           @Override
           public void write(JsonWriter out, Ecf32Encabezado value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public Ecf32Encabezado read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of Ecf32Encabezado given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of Ecf32Encabezado
   * @throws IOException if the JSON string is invalid with respect to Ecf32Encabezado
   */
  public static Ecf32Encabezado fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Ecf32Encabezado.class);
  }

  /**
   * Convert an instance of Ecf32Encabezado to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

