/*
 * ECF API
 * ECF API (Electronic Fiscal Receipt).
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dom.com.ssd.ecfx.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import dom.com.ssd.ecfx.client.model.Ecf31FormaDePagoMontoPago;
import dom.com.ssd.ecfx.client.model.Ecf47IndicadorAgenteRetencionoPercepcionType;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import dom.com.ssd.ecfx.client.JSON;

/**
 * Ecf47Retencion
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.20.0")
public class Ecf47Retencion {
  public static final String SERIALIZED_NAME_INDICADOR_AGENTE_RETENCIONO_PERCEPCION = "indicadorAgenteRetencionoPercepcion";
  @SerializedName(SERIALIZED_NAME_INDICADOR_AGENTE_RETENCIONO_PERCEPCION)
  @javax.annotation.Nonnull
  private Ecf47IndicadorAgenteRetencionoPercepcionType indicadorAgenteRetencionoPercepcion;

  public static final String SERIALIZED_NAME_MONTO_I_S_R_RETENIDO = "montoISRRetenido";
  @SerializedName(SERIALIZED_NAME_MONTO_I_S_R_RETENIDO)
  @javax.annotation.Nonnull
  private Ecf31FormaDePagoMontoPago montoISRRetenido;

  public Ecf47Retencion() {
  }

  public Ecf47Retencion indicadorAgenteRetencionoPercepcion(@javax.annotation.Nonnull Ecf47IndicadorAgenteRetencionoPercepcionType indicadorAgenteRetencionoPercepcion) {
    this.indicadorAgenteRetencionoPercepcion = indicadorAgenteRetencionoPercepcion;
    return this;
  }

  /**
   * Get indicadorAgenteRetencionoPercepcion
   * @return indicadorAgenteRetencionoPercepcion
   */
  @javax.annotation.Nonnull
  public Ecf47IndicadorAgenteRetencionoPercepcionType getIndicadorAgenteRetencionoPercepcion() {
    return indicadorAgenteRetencionoPercepcion;
  }

  public void setIndicadorAgenteRetencionoPercepcion(@javax.annotation.Nonnull Ecf47IndicadorAgenteRetencionoPercepcionType indicadorAgenteRetencionoPercepcion) {
    this.indicadorAgenteRetencionoPercepcion = indicadorAgenteRetencionoPercepcion;
  }


  public Ecf47Retencion montoISRRetenido(@javax.annotation.Nonnull Ecf31FormaDePagoMontoPago montoISRRetenido) {
    this.montoISRRetenido = montoISRRetenido;
    return this;
  }

  /**
   * Get montoISRRetenido
   * @return montoISRRetenido
   */
  @javax.annotation.Nonnull
  public Ecf31FormaDePagoMontoPago getMontoISRRetenido() {
    return montoISRRetenido;
  }

  public void setMontoISRRetenido(@javax.annotation.Nonnull Ecf31FormaDePagoMontoPago montoISRRetenido) {
    this.montoISRRetenido = montoISRRetenido;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Ecf47Retencion ecf47Retencion = (Ecf47Retencion) o;
    return Objects.equals(this.indicadorAgenteRetencionoPercepcion, ecf47Retencion.indicadorAgenteRetencionoPercepcion) &&
        Objects.equals(this.montoISRRetenido, ecf47Retencion.montoISRRetenido);
  }

  @Override
  public int hashCode() {
    return Objects.hash(indicadorAgenteRetencionoPercepcion, montoISRRetenido);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Ecf47Retencion {\n");
    sb.append("    indicadorAgenteRetencionoPercepcion: ").append(toIndentedString(indicadorAgenteRetencionoPercepcion)).append("\n");
    sb.append("    montoISRRetenido: ").append(toIndentedString(montoISRRetenido)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("indicadorAgenteRetencionoPercepcion", "montoISRRetenido"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("indicadorAgenteRetencionoPercepcion", "montoISRRetenido"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to Ecf47Retencion
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!Ecf47Retencion.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in Ecf47Retencion is not found in the empty JSON string", Ecf47Retencion.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!Ecf47Retencion.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `Ecf47Retencion` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : Ecf47Retencion.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the required field `indicadorAgenteRetencionoPercepcion`
      Ecf47IndicadorAgenteRetencionoPercepcionType.validateJsonElement(jsonObj.get("indicadorAgenteRetencionoPercepcion"));
      // validate the required field `montoISRRetenido`
      Ecf31FormaDePagoMontoPago.validateJsonElement(jsonObj.get("montoISRRetenido"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Ecf47Retencion.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Ecf47Retencion' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Ecf47Retencion> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Ecf47Retencion.class));

       return (TypeAdapter<T>) new TypeAdapter<Ecf47Retencion>() {
           @Override
           public void write(JsonWriter out, Ecf47Retencion value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public Ecf47Retencion read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of Ecf47Retencion given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of Ecf47Retencion
   * @throws IOException if the JSON string is invalid with respect to Ecf47Retencion
   */
  public static Ecf47Retencion fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Ecf47Retencion.class);
  }

  /**
   * Convert an instance of Ecf47Retencion to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

