/*
 * ECF API
 * ECF API (Electronic Fiscal Receipt).
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dom.com.ssd.ecfx.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import dom.com.ssd.ecfx.client.model.ProvinciaMunicipioType;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import dom.com.ssd.ecfx.client.JSON;

/**
 * Ecf45Emisor
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.20.0")
public class Ecf45Emisor {
  public static final String SERIALIZED_NAME_RNC_EMISOR = "rncEmisor";
  @SerializedName(SERIALIZED_NAME_RNC_EMISOR)
  @javax.annotation.Nonnull
  private String rncEmisor;

  public static final String SERIALIZED_NAME_RAZON_SOCIAL_EMISOR = "razonSocialEmisor";
  @SerializedName(SERIALIZED_NAME_RAZON_SOCIAL_EMISOR)
  @javax.annotation.Nonnull
  private String razonSocialEmisor;

  public static final String SERIALIZED_NAME_NOMBRE_COMERCIAL = "nombreComercial";
  @SerializedName(SERIALIZED_NAME_NOMBRE_COMERCIAL)
  @javax.annotation.Nullable
  private String nombreComercial;

  public static final String SERIALIZED_NAME_SUCURSAL = "sucursal";
  @SerializedName(SERIALIZED_NAME_SUCURSAL)
  @javax.annotation.Nullable
  private String sucursal;

  public static final String SERIALIZED_NAME_DIRECCION_EMISOR = "direccionEmisor";
  @SerializedName(SERIALIZED_NAME_DIRECCION_EMISOR)
  @javax.annotation.Nonnull
  private String direccionEmisor;

  public static final String SERIALIZED_NAME_MUNICIPIO = "municipio";
  @SerializedName(SERIALIZED_NAME_MUNICIPIO)
  @javax.annotation.Nullable
  private ProvinciaMunicipioType municipio;

  public static final String SERIALIZED_NAME_PROVINCIA = "provincia";
  @SerializedName(SERIALIZED_NAME_PROVINCIA)
  @javax.annotation.Nullable
  private ProvinciaMunicipioType provincia;

  public static final String SERIALIZED_NAME_TABLA_TELEFONO_EMISOR = "tablaTelefonoEmisor";
  @SerializedName(SERIALIZED_NAME_TABLA_TELEFONO_EMISOR)
  @javax.annotation.Nullable
  private List<String> tablaTelefonoEmisor;

  public static final String SERIALIZED_NAME_CORREO_EMISOR = "correoEmisor";
  @SerializedName(SERIALIZED_NAME_CORREO_EMISOR)
  @javax.annotation.Nullable
  private String correoEmisor;

  public static final String SERIALIZED_NAME_WEB_SITE = "webSite";
  @SerializedName(SERIALIZED_NAME_WEB_SITE)
  @javax.annotation.Nullable
  private String webSite;

  public static final String SERIALIZED_NAME_ACTIVIDAD_ECONOMICA = "actividadEconomica";
  @SerializedName(SERIALIZED_NAME_ACTIVIDAD_ECONOMICA)
  @javax.annotation.Nullable
  private String actividadEconomica;

  public static final String SERIALIZED_NAME_CODIGO_VENDEDOR = "codigoVendedor";
  @SerializedName(SERIALIZED_NAME_CODIGO_VENDEDOR)
  @javax.annotation.Nullable
  private String codigoVendedor;

  public static final String SERIALIZED_NAME_NUMERO_FACTURA_INTERNA = "numeroFacturaInterna";
  @SerializedName(SERIALIZED_NAME_NUMERO_FACTURA_INTERNA)
  @javax.annotation.Nullable
  private String numeroFacturaInterna;

  public static final String SERIALIZED_NAME_NUMERO_PEDIDO_INTERNO = "numeroPedidoInterno";
  @SerializedName(SERIALIZED_NAME_NUMERO_PEDIDO_INTERNO)
  @javax.annotation.Nullable
  private String numeroPedidoInterno;

  public static final String SERIALIZED_NAME_ZONA_VENTA = "zonaVenta";
  @SerializedName(SERIALIZED_NAME_ZONA_VENTA)
  @javax.annotation.Nullable
  private String zonaVenta;

  public static final String SERIALIZED_NAME_RUTA_VENTA = "rutaVenta";
  @SerializedName(SERIALIZED_NAME_RUTA_VENTA)
  @javax.annotation.Nullable
  private String rutaVenta;

  public static final String SERIALIZED_NAME_INFORMACION_ADICIONAL_EMISOR = "informacionAdicionalEmisor";
  @SerializedName(SERIALIZED_NAME_INFORMACION_ADICIONAL_EMISOR)
  @javax.annotation.Nullable
  private String informacionAdicionalEmisor;

  public static final String SERIALIZED_NAME_FECHA_EMISION = "fechaEmision";
  @SerializedName(SERIALIZED_NAME_FECHA_EMISION)
  @javax.annotation.Nullable
  private Date fechaEmision;

  public Ecf45Emisor() {
  }

  public Ecf45Emisor rncEmisor(@javax.annotation.Nonnull String rncEmisor) {
    this.rncEmisor = rncEmisor;
    return this;
  }

  /**
   * Get rncEmisor
   * @return rncEmisor
   */
  @javax.annotation.Nonnull
  public String getRncEmisor() {
    return rncEmisor;
  }

  public void setRncEmisor(@javax.annotation.Nonnull String rncEmisor) {
    this.rncEmisor = rncEmisor;
  }


  public Ecf45Emisor razonSocialEmisor(@javax.annotation.Nonnull String razonSocialEmisor) {
    this.razonSocialEmisor = razonSocialEmisor;
    return this;
  }

  /**
   * Get razonSocialEmisor
   * @return razonSocialEmisor
   */
  @javax.annotation.Nonnull
  public String getRazonSocialEmisor() {
    return razonSocialEmisor;
  }

  public void setRazonSocialEmisor(@javax.annotation.Nonnull String razonSocialEmisor) {
    this.razonSocialEmisor = razonSocialEmisor;
  }


  public Ecf45Emisor nombreComercial(@javax.annotation.Nullable String nombreComercial) {
    this.nombreComercial = nombreComercial;
    return this;
  }

  /**
   * Get nombreComercial
   * @return nombreComercial
   */
  @javax.annotation.Nullable
  public String getNombreComercial() {
    return nombreComercial;
  }

  public void setNombreComercial(@javax.annotation.Nullable String nombreComercial) {
    this.nombreComercial = nombreComercial;
  }


  public Ecf45Emisor sucursal(@javax.annotation.Nullable String sucursal) {
    this.sucursal = sucursal;
    return this;
  }

  /**
   * Get sucursal
   * @return sucursal
   */
  @javax.annotation.Nullable
  public String getSucursal() {
    return sucursal;
  }

  public void setSucursal(@javax.annotation.Nullable String sucursal) {
    this.sucursal = sucursal;
  }


  public Ecf45Emisor direccionEmisor(@javax.annotation.Nonnull String direccionEmisor) {
    this.direccionEmisor = direccionEmisor;
    return this;
  }

  /**
   * Get direccionEmisor
   * @return direccionEmisor
   */
  @javax.annotation.Nonnull
  public String getDireccionEmisor() {
    return direccionEmisor;
  }

  public void setDireccionEmisor(@javax.annotation.Nonnull String direccionEmisor) {
    this.direccionEmisor = direccionEmisor;
  }


  public Ecf45Emisor municipio(@javax.annotation.Nullable ProvinciaMunicipioType municipio) {
    this.municipio = municipio;
    return this;
  }

  /**
   * Get municipio
   * @return municipio
   */
  @javax.annotation.Nullable
  public ProvinciaMunicipioType getMunicipio() {
    return municipio;
  }

  public void setMunicipio(@javax.annotation.Nullable ProvinciaMunicipioType municipio) {
    this.municipio = municipio;
  }


  public Ecf45Emisor provincia(@javax.annotation.Nullable ProvinciaMunicipioType provincia) {
    this.provincia = provincia;
    return this;
  }

  /**
   * Get provincia
   * @return provincia
   */
  @javax.annotation.Nullable
  public ProvinciaMunicipioType getProvincia() {
    return provincia;
  }

  public void setProvincia(@javax.annotation.Nullable ProvinciaMunicipioType provincia) {
    this.provincia = provincia;
  }


  public Ecf45Emisor tablaTelefonoEmisor(@javax.annotation.Nullable List<String> tablaTelefonoEmisor) {
    this.tablaTelefonoEmisor = tablaTelefonoEmisor;
    return this;
  }

  public Ecf45Emisor addTablaTelefonoEmisorItem(String tablaTelefonoEmisorItem) {
    if (this.tablaTelefonoEmisor == null) {
      this.tablaTelefonoEmisor = new ArrayList<>();
    }
    this.tablaTelefonoEmisor.add(tablaTelefonoEmisorItem);
    return this;
  }

  /**
   * Get tablaTelefonoEmisor
   * @return tablaTelefonoEmisor
   */
  @javax.annotation.Nullable
  public List<String> getTablaTelefonoEmisor() {
    return tablaTelefonoEmisor;
  }

  public void setTablaTelefonoEmisor(@javax.annotation.Nullable List<String> tablaTelefonoEmisor) {
    this.tablaTelefonoEmisor = tablaTelefonoEmisor;
  }


  public Ecf45Emisor correoEmisor(@javax.annotation.Nullable String correoEmisor) {
    this.correoEmisor = correoEmisor;
    return this;
  }

  /**
   * Get correoEmisor
   * @return correoEmisor
   */
  @javax.annotation.Nullable
  public String getCorreoEmisor() {
    return correoEmisor;
  }

  public void setCorreoEmisor(@javax.annotation.Nullable String correoEmisor) {
    this.correoEmisor = correoEmisor;
  }


  public Ecf45Emisor webSite(@javax.annotation.Nullable String webSite) {
    this.webSite = webSite;
    return this;
  }

  /**
   * Get webSite
   * @return webSite
   */
  @javax.annotation.Nullable
  public String getWebSite() {
    return webSite;
  }

  public void setWebSite(@javax.annotation.Nullable String webSite) {
    this.webSite = webSite;
  }


  public Ecf45Emisor actividadEconomica(@javax.annotation.Nullable String actividadEconomica) {
    this.actividadEconomica = actividadEconomica;
    return this;
  }

  /**
   * Get actividadEconomica
   * @return actividadEconomica
   */
  @javax.annotation.Nullable
  public String getActividadEconomica() {
    return actividadEconomica;
  }

  public void setActividadEconomica(@javax.annotation.Nullable String actividadEconomica) {
    this.actividadEconomica = actividadEconomica;
  }


  public Ecf45Emisor codigoVendedor(@javax.annotation.Nullable String codigoVendedor) {
    this.codigoVendedor = codigoVendedor;
    return this;
  }

  /**
   * Get codigoVendedor
   * @return codigoVendedor
   */
  @javax.annotation.Nullable
  public String getCodigoVendedor() {
    return codigoVendedor;
  }

  public void setCodigoVendedor(@javax.annotation.Nullable String codigoVendedor) {
    this.codigoVendedor = codigoVendedor;
  }


  public Ecf45Emisor numeroFacturaInterna(@javax.annotation.Nullable String numeroFacturaInterna) {
    this.numeroFacturaInterna = numeroFacturaInterna;
    return this;
  }

  /**
   * Get numeroFacturaInterna
   * @return numeroFacturaInterna
   */
  @javax.annotation.Nullable
  public String getNumeroFacturaInterna() {
    return numeroFacturaInterna;
  }

  public void setNumeroFacturaInterna(@javax.annotation.Nullable String numeroFacturaInterna) {
    this.numeroFacturaInterna = numeroFacturaInterna;
  }


  public Ecf45Emisor numeroPedidoInterno(@javax.annotation.Nullable String numeroPedidoInterno) {
    this.numeroPedidoInterno = numeroPedidoInterno;
    return this;
  }

  /**
   * Get numeroPedidoInterno
   * @return numeroPedidoInterno
   */
  @javax.annotation.Nullable
  public String getNumeroPedidoInterno() {
    return numeroPedidoInterno;
  }

  public void setNumeroPedidoInterno(@javax.annotation.Nullable String numeroPedidoInterno) {
    this.numeroPedidoInterno = numeroPedidoInterno;
  }


  public Ecf45Emisor zonaVenta(@javax.annotation.Nullable String zonaVenta) {
    this.zonaVenta = zonaVenta;
    return this;
  }

  /**
   * Get zonaVenta
   * @return zonaVenta
   */
  @javax.annotation.Nullable
  public String getZonaVenta() {
    return zonaVenta;
  }

  public void setZonaVenta(@javax.annotation.Nullable String zonaVenta) {
    this.zonaVenta = zonaVenta;
  }


  public Ecf45Emisor rutaVenta(@javax.annotation.Nullable String rutaVenta) {
    this.rutaVenta = rutaVenta;
    return this;
  }

  /**
   * Get rutaVenta
   * @return rutaVenta
   */
  @javax.annotation.Nullable
  public String getRutaVenta() {
    return rutaVenta;
  }

  public void setRutaVenta(@javax.annotation.Nullable String rutaVenta) {
    this.rutaVenta = rutaVenta;
  }


  public Ecf45Emisor informacionAdicionalEmisor(@javax.annotation.Nullable String informacionAdicionalEmisor) {
    this.informacionAdicionalEmisor = informacionAdicionalEmisor;
    return this;
  }

  /**
   * Get informacionAdicionalEmisor
   * @return informacionAdicionalEmisor
   */
  @javax.annotation.Nullable
  public String getInformacionAdicionalEmisor() {
    return informacionAdicionalEmisor;
  }

  public void setInformacionAdicionalEmisor(@javax.annotation.Nullable String informacionAdicionalEmisor) {
    this.informacionAdicionalEmisor = informacionAdicionalEmisor;
  }


  public Ecf45Emisor fechaEmision(@javax.annotation.Nullable Date fechaEmision) {
    this.fechaEmision = fechaEmision;
    return this;
  }

  /**
   * Get fechaEmision
   * @return fechaEmision
   */
  @javax.annotation.Nullable
  public Date getFechaEmision() {
    return fechaEmision;
  }

  public void setFechaEmision(@javax.annotation.Nullable Date fechaEmision) {
    this.fechaEmision = fechaEmision;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Ecf45Emisor ecf45Emisor = (Ecf45Emisor) o;
    return Objects.equals(this.rncEmisor, ecf45Emisor.rncEmisor) &&
        Objects.equals(this.razonSocialEmisor, ecf45Emisor.razonSocialEmisor) &&
        Objects.equals(this.nombreComercial, ecf45Emisor.nombreComercial) &&
        Objects.equals(this.sucursal, ecf45Emisor.sucursal) &&
        Objects.equals(this.direccionEmisor, ecf45Emisor.direccionEmisor) &&
        Objects.equals(this.municipio, ecf45Emisor.municipio) &&
        Objects.equals(this.provincia, ecf45Emisor.provincia) &&
        Objects.equals(this.tablaTelefonoEmisor, ecf45Emisor.tablaTelefonoEmisor) &&
        Objects.equals(this.correoEmisor, ecf45Emisor.correoEmisor) &&
        Objects.equals(this.webSite, ecf45Emisor.webSite) &&
        Objects.equals(this.actividadEconomica, ecf45Emisor.actividadEconomica) &&
        Objects.equals(this.codigoVendedor, ecf45Emisor.codigoVendedor) &&
        Objects.equals(this.numeroFacturaInterna, ecf45Emisor.numeroFacturaInterna) &&
        Objects.equals(this.numeroPedidoInterno, ecf45Emisor.numeroPedidoInterno) &&
        Objects.equals(this.zonaVenta, ecf45Emisor.zonaVenta) &&
        Objects.equals(this.rutaVenta, ecf45Emisor.rutaVenta) &&
        Objects.equals(this.informacionAdicionalEmisor, ecf45Emisor.informacionAdicionalEmisor) &&
        Objects.equals(this.fechaEmision, ecf45Emisor.fechaEmision);
  }

  @Override
  public int hashCode() {
    return Objects.hash(rncEmisor, razonSocialEmisor, nombreComercial, sucursal, direccionEmisor, municipio, provincia, tablaTelefonoEmisor, correoEmisor, webSite, actividadEconomica, codigoVendedor, numeroFacturaInterna, numeroPedidoInterno, zonaVenta, rutaVenta, informacionAdicionalEmisor, fechaEmision);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Ecf45Emisor {\n");
    sb.append("    rncEmisor: ").append(toIndentedString(rncEmisor)).append("\n");
    sb.append("    razonSocialEmisor: ").append(toIndentedString(razonSocialEmisor)).append("\n");
    sb.append("    nombreComercial: ").append(toIndentedString(nombreComercial)).append("\n");
    sb.append("    sucursal: ").append(toIndentedString(sucursal)).append("\n");
    sb.append("    direccionEmisor: ").append(toIndentedString(direccionEmisor)).append("\n");
    sb.append("    municipio: ").append(toIndentedString(municipio)).append("\n");
    sb.append("    provincia: ").append(toIndentedString(provincia)).append("\n");
    sb.append("    tablaTelefonoEmisor: ").append(toIndentedString(tablaTelefonoEmisor)).append("\n");
    sb.append("    correoEmisor: ").append(toIndentedString(correoEmisor)).append("\n");
    sb.append("    webSite: ").append(toIndentedString(webSite)).append("\n");
    sb.append("    actividadEconomica: ").append(toIndentedString(actividadEconomica)).append("\n");
    sb.append("    codigoVendedor: ").append(toIndentedString(codigoVendedor)).append("\n");
    sb.append("    numeroFacturaInterna: ").append(toIndentedString(numeroFacturaInterna)).append("\n");
    sb.append("    numeroPedidoInterno: ").append(toIndentedString(numeroPedidoInterno)).append("\n");
    sb.append("    zonaVenta: ").append(toIndentedString(zonaVenta)).append("\n");
    sb.append("    rutaVenta: ").append(toIndentedString(rutaVenta)).append("\n");
    sb.append("    informacionAdicionalEmisor: ").append(toIndentedString(informacionAdicionalEmisor)).append("\n");
    sb.append("    fechaEmision: ").append(toIndentedString(fechaEmision)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("rncEmisor", "razonSocialEmisor", "nombreComercial", "sucursal", "direccionEmisor", "municipio", "provincia", "tablaTelefonoEmisor", "correoEmisor", "webSite", "actividadEconomica", "codigoVendedor", "numeroFacturaInterna", "numeroPedidoInterno", "zonaVenta", "rutaVenta", "informacionAdicionalEmisor", "fechaEmision"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("rncEmisor", "razonSocialEmisor", "direccionEmisor"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to Ecf45Emisor
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!Ecf45Emisor.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in Ecf45Emisor is not found in the empty JSON string", Ecf45Emisor.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!Ecf45Emisor.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `Ecf45Emisor` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : Ecf45Emisor.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("rncEmisor").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `rncEmisor` to be a primitive type in the JSON string but got `%s`", jsonObj.get("rncEmisor").toString()));
      }
      if (!jsonObj.get("razonSocialEmisor").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `razonSocialEmisor` to be a primitive type in the JSON string but got `%s`", jsonObj.get("razonSocialEmisor").toString()));
      }
      if ((jsonObj.get("nombreComercial") != null && !jsonObj.get("nombreComercial").isJsonNull()) && !jsonObj.get("nombreComercial").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `nombreComercial` to be a primitive type in the JSON string but got `%s`", jsonObj.get("nombreComercial").toString()));
      }
      if ((jsonObj.get("sucursal") != null && !jsonObj.get("sucursal").isJsonNull()) && !jsonObj.get("sucursal").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `sucursal` to be a primitive type in the JSON string but got `%s`", jsonObj.get("sucursal").toString()));
      }
      if (!jsonObj.get("direccionEmisor").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `direccionEmisor` to be a primitive type in the JSON string but got `%s`", jsonObj.get("direccionEmisor").toString()));
      }
      // validate the optional field `municipio`
      if (jsonObj.get("municipio") != null && !jsonObj.get("municipio").isJsonNull()) {
        ProvinciaMunicipioType.validateJsonElement(jsonObj.get("municipio"));
      }
      // validate the optional field `provincia`
      if (jsonObj.get("provincia") != null && !jsonObj.get("provincia").isJsonNull()) {
        ProvinciaMunicipioType.validateJsonElement(jsonObj.get("provincia"));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("tablaTelefonoEmisor") != null && !jsonObj.get("tablaTelefonoEmisor").isJsonNull() && !jsonObj.get("tablaTelefonoEmisor").isJsonArray()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `tablaTelefonoEmisor` to be an array in the JSON string but got `%s`", jsonObj.get("tablaTelefonoEmisor").toString()));
      }
      if ((jsonObj.get("correoEmisor") != null && !jsonObj.get("correoEmisor").isJsonNull()) && !jsonObj.get("correoEmisor").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `correoEmisor` to be a primitive type in the JSON string but got `%s`", jsonObj.get("correoEmisor").toString()));
      }
      if ((jsonObj.get("webSite") != null && !jsonObj.get("webSite").isJsonNull()) && !jsonObj.get("webSite").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `webSite` to be a primitive type in the JSON string but got `%s`", jsonObj.get("webSite").toString()));
      }
      if ((jsonObj.get("actividadEconomica") != null && !jsonObj.get("actividadEconomica").isJsonNull()) && !jsonObj.get("actividadEconomica").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `actividadEconomica` to be a primitive type in the JSON string but got `%s`", jsonObj.get("actividadEconomica").toString()));
      }
      if ((jsonObj.get("codigoVendedor") != null && !jsonObj.get("codigoVendedor").isJsonNull()) && !jsonObj.get("codigoVendedor").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `codigoVendedor` to be a primitive type in the JSON string but got `%s`", jsonObj.get("codigoVendedor").toString()));
      }
      if ((jsonObj.get("numeroFacturaInterna") != null && !jsonObj.get("numeroFacturaInterna").isJsonNull()) && !jsonObj.get("numeroFacturaInterna").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `numeroFacturaInterna` to be a primitive type in the JSON string but got `%s`", jsonObj.get("numeroFacturaInterna").toString()));
      }
      if ((jsonObj.get("numeroPedidoInterno") != null && !jsonObj.get("numeroPedidoInterno").isJsonNull()) && !jsonObj.get("numeroPedidoInterno").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `numeroPedidoInterno` to be a primitive type in the JSON string but got `%s`", jsonObj.get("numeroPedidoInterno").toString()));
      }
      if ((jsonObj.get("zonaVenta") != null && !jsonObj.get("zonaVenta").isJsonNull()) && !jsonObj.get("zonaVenta").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `zonaVenta` to be a primitive type in the JSON string but got `%s`", jsonObj.get("zonaVenta").toString()));
      }
      if ((jsonObj.get("rutaVenta") != null && !jsonObj.get("rutaVenta").isJsonNull()) && !jsonObj.get("rutaVenta").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `rutaVenta` to be a primitive type in the JSON string but got `%s`", jsonObj.get("rutaVenta").toString()));
      }
      if ((jsonObj.get("informacionAdicionalEmisor") != null && !jsonObj.get("informacionAdicionalEmisor").isJsonNull()) && !jsonObj.get("informacionAdicionalEmisor").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `informacionAdicionalEmisor` to be a primitive type in the JSON string but got `%s`", jsonObj.get("informacionAdicionalEmisor").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Ecf45Emisor.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Ecf45Emisor' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Ecf45Emisor> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Ecf45Emisor.class));

       return (TypeAdapter<T>) new TypeAdapter<Ecf45Emisor>() {
           @Override
           public void write(JsonWriter out, Ecf45Emisor value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public Ecf45Emisor read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of Ecf45Emisor given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of Ecf45Emisor
   * @throws IOException if the JSON string is invalid with respect to Ecf45Emisor
   */
  public static Ecf45Emisor fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Ecf45Emisor.class);
  }

  /**
   * Convert an instance of Ecf45Emisor to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

