/*
 * ECF API
 * ECF API (Electronic Fiscal Receipt).
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dom.com.ssd.ecfx.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import dom.com.ssd.ecfx.client.model.Ecf41Comprador;
import dom.com.ssd.ecfx.client.model.Ecf41Emisor;
import dom.com.ssd.ecfx.client.model.Ecf41IdDoc;
import dom.com.ssd.ecfx.client.model.Ecf41OtraMoneda;
import dom.com.ssd.ecfx.client.model.Ecf41Totales;
import dom.com.ssd.ecfx.client.model.Ecf41VersionType;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import dom.com.ssd.ecfx.client.JSON;

/**
 * Ecf41Encabezado
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.20.0")
public class Ecf41Encabezado {
  public static final String SERIALIZED_NAME_VERSION = "version";
  @SerializedName(SERIALIZED_NAME_VERSION)
  @javax.annotation.Nonnull
  private Ecf41VersionType version;

  public static final String SERIALIZED_NAME_ID_DOC = "idDoc";
  @SerializedName(SERIALIZED_NAME_ID_DOC)
  @javax.annotation.Nonnull
  private Ecf41IdDoc idDoc;

  public static final String SERIALIZED_NAME_EMISOR = "emisor";
  @SerializedName(SERIALIZED_NAME_EMISOR)
  @javax.annotation.Nonnull
  private Ecf41Emisor emisor;

  public static final String SERIALIZED_NAME_COMPRADOR = "comprador";
  @SerializedName(SERIALIZED_NAME_COMPRADOR)
  @javax.annotation.Nonnull
  private Ecf41Comprador comprador;

  public static final String SERIALIZED_NAME_TOTALES = "totales";
  @SerializedName(SERIALIZED_NAME_TOTALES)
  @javax.annotation.Nonnull
  private Ecf41Totales totales;

  public static final String SERIALIZED_NAME_OTRA_MONEDA = "otraMoneda";
  @SerializedName(SERIALIZED_NAME_OTRA_MONEDA)
  @javax.annotation.Nullable
  private Ecf41OtraMoneda otraMoneda;

  public Ecf41Encabezado() {
  }

  public Ecf41Encabezado version(@javax.annotation.Nonnull Ecf41VersionType version) {
    this.version = version;
    return this;
  }

  /**
   * Get version
   * @return version
   */
  @javax.annotation.Nonnull
  public Ecf41VersionType getVersion() {
    return version;
  }

  public void setVersion(@javax.annotation.Nonnull Ecf41VersionType version) {
    this.version = version;
  }


  public Ecf41Encabezado idDoc(@javax.annotation.Nonnull Ecf41IdDoc idDoc) {
    this.idDoc = idDoc;
    return this;
  }

  /**
   * Get idDoc
   * @return idDoc
   */
  @javax.annotation.Nonnull
  public Ecf41IdDoc getIdDoc() {
    return idDoc;
  }

  public void setIdDoc(@javax.annotation.Nonnull Ecf41IdDoc idDoc) {
    this.idDoc = idDoc;
  }


  public Ecf41Encabezado emisor(@javax.annotation.Nonnull Ecf41Emisor emisor) {
    this.emisor = emisor;
    return this;
  }

  /**
   * Get emisor
   * @return emisor
   */
  @javax.annotation.Nonnull
  public Ecf41Emisor getEmisor() {
    return emisor;
  }

  public void setEmisor(@javax.annotation.Nonnull Ecf41Emisor emisor) {
    this.emisor = emisor;
  }


  public Ecf41Encabezado comprador(@javax.annotation.Nonnull Ecf41Comprador comprador) {
    this.comprador = comprador;
    return this;
  }

  /**
   * Get comprador
   * @return comprador
   */
  @javax.annotation.Nonnull
  public Ecf41Comprador getComprador() {
    return comprador;
  }

  public void setComprador(@javax.annotation.Nonnull Ecf41Comprador comprador) {
    this.comprador = comprador;
  }


  public Ecf41Encabezado totales(@javax.annotation.Nonnull Ecf41Totales totales) {
    this.totales = totales;
    return this;
  }

  /**
   * Get totales
   * @return totales
   */
  @javax.annotation.Nonnull
  public Ecf41Totales getTotales() {
    return totales;
  }

  public void setTotales(@javax.annotation.Nonnull Ecf41Totales totales) {
    this.totales = totales;
  }


  public Ecf41Encabezado otraMoneda(@javax.annotation.Nullable Ecf41OtraMoneda otraMoneda) {
    this.otraMoneda = otraMoneda;
    return this;
  }

  /**
   * Get otraMoneda
   * @return otraMoneda
   */
  @javax.annotation.Nullable
  public Ecf41OtraMoneda getOtraMoneda() {
    return otraMoneda;
  }

  public void setOtraMoneda(@javax.annotation.Nullable Ecf41OtraMoneda otraMoneda) {
    this.otraMoneda = otraMoneda;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Ecf41Encabezado ecf41Encabezado = (Ecf41Encabezado) o;
    return Objects.equals(this.version, ecf41Encabezado.version) &&
        Objects.equals(this.idDoc, ecf41Encabezado.idDoc) &&
        Objects.equals(this.emisor, ecf41Encabezado.emisor) &&
        Objects.equals(this.comprador, ecf41Encabezado.comprador) &&
        Objects.equals(this.totales, ecf41Encabezado.totales) &&
        Objects.equals(this.otraMoneda, ecf41Encabezado.otraMoneda);
  }

  @Override
  public int hashCode() {
    return Objects.hash(version, idDoc, emisor, comprador, totales, otraMoneda);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Ecf41Encabezado {\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    idDoc: ").append(toIndentedString(idDoc)).append("\n");
    sb.append("    emisor: ").append(toIndentedString(emisor)).append("\n");
    sb.append("    comprador: ").append(toIndentedString(comprador)).append("\n");
    sb.append("    totales: ").append(toIndentedString(totales)).append("\n");
    sb.append("    otraMoneda: ").append(toIndentedString(otraMoneda)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("version", "idDoc", "emisor", "comprador", "totales", "otraMoneda"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("version", "idDoc", "emisor", "comprador", "totales"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to Ecf41Encabezado
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!Ecf41Encabezado.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in Ecf41Encabezado is not found in the empty JSON string", Ecf41Encabezado.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!Ecf41Encabezado.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `Ecf41Encabezado` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : Ecf41Encabezado.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the required field `version`
      Ecf41VersionType.validateJsonElement(jsonObj.get("version"));
      // validate the required field `idDoc`
      Ecf41IdDoc.validateJsonElement(jsonObj.get("idDoc"));
      // validate the required field `emisor`
      Ecf41Emisor.validateJsonElement(jsonObj.get("emisor"));
      // validate the required field `comprador`
      Ecf41Comprador.validateJsonElement(jsonObj.get("comprador"));
      // validate the required field `totales`
      Ecf41Totales.validateJsonElement(jsonObj.get("totales"));
      // validate the optional field `otraMoneda`
      if (jsonObj.get("otraMoneda") != null && !jsonObj.get("otraMoneda").isJsonNull()) {
        Ecf41OtraMoneda.validateJsonElement(jsonObj.get("otraMoneda"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Ecf41Encabezado.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Ecf41Encabezado' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Ecf41Encabezado> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Ecf41Encabezado.class));

       return (TypeAdapter<T>) new TypeAdapter<Ecf41Encabezado>() {
           @Override
           public void write(JsonWriter out, Ecf41Encabezado value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public Ecf41Encabezado read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of Ecf41Encabezado given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of Ecf41Encabezado
   * @throws IOException if the JSON string is invalid with respect to Ecf41Encabezado
   */
  public static Ecf41Encabezado fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Ecf41Encabezado.class);
  }

  /**
   * Convert an instance of Ecf41Encabezado to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

