/*
 * ECF API
 * ECF API (Electronic Fiscal Receipt).
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dom.com.ssd.ecfx.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets Ecf41IndicadorAgenteRetencionoPercepcionType
 */
@JsonAdapter(Ecf41IndicadorAgenteRetencionoPercepcionType.Adapter.class)
public enum Ecf41IndicadorAgenteRetencionoPercepcionType {
  
  RETENCION("Retencion"),
  
  PERCEPCION("Percepcion");

  private String value;

  Ecf41IndicadorAgenteRetencionoPercepcionType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static Ecf41IndicadorAgenteRetencionoPercepcionType fromValue(String value) {
    for (Ecf41IndicadorAgenteRetencionoPercepcionType b : Ecf41IndicadorAgenteRetencionoPercepcionType.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<Ecf41IndicadorAgenteRetencionoPercepcionType> {
    @Override
    public void write(final JsonWriter jsonWriter, final Ecf41IndicadorAgenteRetencionoPercepcionType enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public Ecf41IndicadorAgenteRetencionoPercepcionType read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return Ecf41IndicadorAgenteRetencionoPercepcionType.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    Ecf41IndicadorAgenteRetencionoPercepcionType.fromValue(value);
  }
}

