/*
 * ECF API
 * ECF API (Electronic Fiscal Receipt).
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dom.com.ssd.ecfx.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import dom.com.ssd.ecfx.client.model.AcecfSummaryDto;
import dom.com.ssd.ecfx.client.model.AllTipoECFTypes;
import dom.com.ssd.ecfx.client.model.EcfReceptorDtoEstado;
import dom.com.ssd.ecfx.client.model.EcfReceptorDtoProgress;
import dom.com.ssd.ecfx.client.model.SearchEcfsAmountFromParameter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import java.util.List;
import java.util.UUID;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import dom.com.ssd.ecfx.client.JSON;

/**
 * EcfReceptorDto
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class EcfReceptorDto {
  public static final String SERIALIZED_NAME_ECF_RECEPTOR_ID = "ecfReceptorId";
  @SerializedName(SERIALIZED_NAME_ECF_RECEPTOR_ID)
  @javax.annotation.Nullable
  private UUID ecfReceptorId;

  public static final String SERIALIZED_NAME_TENANT_ID = "tenantId";
  @SerializedName(SERIALIZED_NAME_TENANT_ID)
  @javax.annotation.Nullable
  private UUID tenantId;

  public static final String SERIALIZED_NAME_COMPANY_RNC = "companyRnc";
  @SerializedName(SERIALIZED_NAME_COMPANY_RNC)
  @javax.annotation.Nullable
  private String companyRnc;

  public static final String SERIALIZED_NAME_ENCF = "encf";
  @SerializedName(SERIALIZED_NAME_ENCF)
  @javax.annotation.Nullable
  private String encf;

  public static final String SERIALIZED_NAME_RNC_EMISOR = "rncEmisor";
  @SerializedName(SERIALIZED_NAME_RNC_EMISOR)
  @javax.annotation.Nullable
  private String rncEmisor;

  public static final String SERIALIZED_NAME_RNC_RECEPTOR = "rncReceptor";
  @SerializedName(SERIALIZED_NAME_RNC_RECEPTOR)
  @javax.annotation.Nullable
  private String rncReceptor;

  public static final String SERIALIZED_NAME_TIPO_ECF = "tipoEcf";
  @SerializedName(SERIALIZED_NAME_TIPO_ECF)
  @javax.annotation.Nullable
  private AllTipoECFTypes tipoEcf;

  public static final String SERIALIZED_NAME_MONTO_TOTAL = "montoTotal";
  @SerializedName(SERIALIZED_NAME_MONTO_TOTAL)
  @javax.annotation.Nullable
  private SearchEcfsAmountFromParameter montoTotal;

  public static final String SERIALIZED_NAME_FECHA_EMISION = "fechaEmision";
  @SerializedName(SERIALIZED_NAME_FECHA_EMISION)
  @javax.annotation.Nullable
  private Date fechaEmision;

  public static final String SERIALIZED_NAME_FILE_NAME = "fileName";
  @SerializedName(SERIALIZED_NAME_FILE_NAME)
  @javax.annotation.Nullable
  private String fileName;

  public static final String SERIALIZED_NAME_RAW_JSON_DATA = "rawJsonData";
  @SerializedName(SERIALIZED_NAME_RAW_JSON_DATA)
  @javax.annotation.Nullable
  private String rawJsonData;

  public static final String SERIALIZED_NAME_CREATED_ON = "createdOn";
  @SerializedName(SERIALIZED_NAME_CREATED_ON)
  @javax.annotation.Nullable
  private Date createdOn;

  public static final String SERIALIZED_NAME_FECHA_FIRMA = "fechaFirma";
  @SerializedName(SERIALIZED_NAME_FECHA_FIRMA)
  @javax.annotation.Nullable
  private Date fechaFirma;

  public static final String SERIALIZED_NAME_COD_SEC = "codSec";
  @SerializedName(SERIALIZED_NAME_COD_SEC)
  @javax.annotation.Nullable
  private String codSec;

  public static final String SERIALIZED_NAME_ESTADO = "estado";
  @SerializedName(SERIALIZED_NAME_ESTADO)
  @javax.annotation.Nullable
  private EcfReceptorDtoEstado estado;

  public static final String SERIALIZED_NAME_PROGRESS = "progress";
  @SerializedName(SERIALIZED_NAME_PROGRESS)
  @javax.annotation.Nullable
  private EcfReceptorDtoProgress progress;

  public static final String SERIALIZED_NAME_AMBIENTE = "ambiente";
  @SerializedName(SERIALIZED_NAME_AMBIENTE)
  @javax.annotation.Nullable
  private String ambiente;

  public static final String SERIALIZED_NAME_URL_IMPRESION = "urlImpresion";
  @SerializedName(SERIALIZED_NAME_URL_IMPRESION)
  @javax.annotation.Nullable
  private String urlImpresion;

  public static final String SERIALIZED_NAME_ACECFS = "acecfs";
  @SerializedName(SERIALIZED_NAME_ACECFS)
  @javax.annotation.Nullable
  private List<AcecfSummaryDto> acecfs = new ArrayList<>();

  public EcfReceptorDto() {
  }

  public EcfReceptorDto ecfReceptorId(@javax.annotation.Nullable UUID ecfReceptorId) {
    this.ecfReceptorId = ecfReceptorId;
    return this;
  }

  /**
   * Get ecfReceptorId
   * @return ecfReceptorId
   */
  @javax.annotation.Nullable
  public UUID getEcfReceptorId() {
    return ecfReceptorId;
  }

  public void setEcfReceptorId(@javax.annotation.Nullable UUID ecfReceptorId) {
    this.ecfReceptorId = ecfReceptorId;
  }


  public EcfReceptorDto tenantId(@javax.annotation.Nullable UUID tenantId) {
    this.tenantId = tenantId;
    return this;
  }

  /**
   * Get tenantId
   * @return tenantId
   */
  @javax.annotation.Nullable
  public UUID getTenantId() {
    return tenantId;
  }

  public void setTenantId(@javax.annotation.Nullable UUID tenantId) {
    this.tenantId = tenantId;
  }


  public EcfReceptorDto companyRnc(@javax.annotation.Nullable String companyRnc) {
    this.companyRnc = companyRnc;
    return this;
  }

  /**
   * Get companyRnc
   * @return companyRnc
   */
  @javax.annotation.Nullable
  public String getCompanyRnc() {
    return companyRnc;
  }

  public void setCompanyRnc(@javax.annotation.Nullable String companyRnc) {
    this.companyRnc = companyRnc;
  }


  public EcfReceptorDto encf(@javax.annotation.Nullable String encf) {
    this.encf = encf;
    return this;
  }

  /**
   * Get encf
   * @return encf
   */
  @javax.annotation.Nullable
  public String getEncf() {
    return encf;
  }

  public void setEncf(@javax.annotation.Nullable String encf) {
    this.encf = encf;
  }


  public EcfReceptorDto rncEmisor(@javax.annotation.Nullable String rncEmisor) {
    this.rncEmisor = rncEmisor;
    return this;
  }

  /**
   * Get rncEmisor
   * @return rncEmisor
   */
  @javax.annotation.Nullable
  public String getRncEmisor() {
    return rncEmisor;
  }

  public void setRncEmisor(@javax.annotation.Nullable String rncEmisor) {
    this.rncEmisor = rncEmisor;
  }


  public EcfReceptorDto rncReceptor(@javax.annotation.Nullable String rncReceptor) {
    this.rncReceptor = rncReceptor;
    return this;
  }

  /**
   * Get rncReceptor
   * @return rncReceptor
   */
  @javax.annotation.Nullable
  public String getRncReceptor() {
    return rncReceptor;
  }

  public void setRncReceptor(@javax.annotation.Nullable String rncReceptor) {
    this.rncReceptor = rncReceptor;
  }


  public EcfReceptorDto tipoEcf(@javax.annotation.Nullable AllTipoECFTypes tipoEcf) {
    this.tipoEcf = tipoEcf;
    return this;
  }

  /**
   * Get tipoEcf
   * @return tipoEcf
   */
  @javax.annotation.Nullable
  public AllTipoECFTypes getTipoEcf() {
    return tipoEcf;
  }

  public void setTipoEcf(@javax.annotation.Nullable AllTipoECFTypes tipoEcf) {
    this.tipoEcf = tipoEcf;
  }


  public EcfReceptorDto montoTotal(@javax.annotation.Nullable SearchEcfsAmountFromParameter montoTotal) {
    this.montoTotal = montoTotal;
    return this;
  }

  /**
   * Get montoTotal
   * @return montoTotal
   */
  @javax.annotation.Nullable
  public SearchEcfsAmountFromParameter getMontoTotal() {
    return montoTotal;
  }

  public void setMontoTotal(@javax.annotation.Nullable SearchEcfsAmountFromParameter montoTotal) {
    this.montoTotal = montoTotal;
  }


  public EcfReceptorDto fechaEmision(@javax.annotation.Nullable Date fechaEmision) {
    this.fechaEmision = fechaEmision;
    return this;
  }

  /**
   * Get fechaEmision
   * @return fechaEmision
   */
  @javax.annotation.Nullable
  public Date getFechaEmision() {
    return fechaEmision;
  }

  public void setFechaEmision(@javax.annotation.Nullable Date fechaEmision) {
    this.fechaEmision = fechaEmision;
  }


  public EcfReceptorDto fileName(@javax.annotation.Nullable String fileName) {
    this.fileName = fileName;
    return this;
  }

  /**
   * Get fileName
   * @return fileName
   */
  @javax.annotation.Nullable
  public String getFileName() {
    return fileName;
  }

  public void setFileName(@javax.annotation.Nullable String fileName) {
    this.fileName = fileName;
  }


  public EcfReceptorDto rawJsonData(@javax.annotation.Nullable String rawJsonData) {
    this.rawJsonData = rawJsonData;
    return this;
  }

  /**
   * Get rawJsonData
   * @return rawJsonData
   */
  @javax.annotation.Nullable
  public String getRawJsonData() {
    return rawJsonData;
  }

  public void setRawJsonData(@javax.annotation.Nullable String rawJsonData) {
    this.rawJsonData = rawJsonData;
  }


  public EcfReceptorDto createdOn(@javax.annotation.Nullable Date createdOn) {
    this.createdOn = createdOn;
    return this;
  }

  /**
   * Get createdOn
   * @return createdOn
   */
  @javax.annotation.Nullable
  public Date getCreatedOn() {
    return createdOn;
  }

  public void setCreatedOn(@javax.annotation.Nullable Date createdOn) {
    this.createdOn = createdOn;
  }


  public EcfReceptorDto fechaFirma(@javax.annotation.Nullable Date fechaFirma) {
    this.fechaFirma = fechaFirma;
    return this;
  }

  /**
   * Get fechaFirma
   * @return fechaFirma
   */
  @javax.annotation.Nullable
  public Date getFechaFirma() {
    return fechaFirma;
  }

  public void setFechaFirma(@javax.annotation.Nullable Date fechaFirma) {
    this.fechaFirma = fechaFirma;
  }


  public EcfReceptorDto codSec(@javax.annotation.Nullable String codSec) {
    this.codSec = codSec;
    return this;
  }

  /**
   * Get codSec
   * @return codSec
   */
  @javax.annotation.Nullable
  public String getCodSec() {
    return codSec;
  }

  public void setCodSec(@javax.annotation.Nullable String codSec) {
    this.codSec = codSec;
  }


  public EcfReceptorDto estado(@javax.annotation.Nullable EcfReceptorDtoEstado estado) {
    this.estado = estado;
    return this;
  }

  /**
   * Get estado
   * @return estado
   */
  @javax.annotation.Nullable
  public EcfReceptorDtoEstado getEstado() {
    return estado;
  }

  public void setEstado(@javax.annotation.Nullable EcfReceptorDtoEstado estado) {
    this.estado = estado;
  }


  public EcfReceptorDto progress(@javax.annotation.Nullable EcfReceptorDtoProgress progress) {
    this.progress = progress;
    return this;
  }

  /**
   * Get progress
   * @return progress
   */
  @javax.annotation.Nullable
  public EcfReceptorDtoProgress getProgress() {
    return progress;
  }

  public void setProgress(@javax.annotation.Nullable EcfReceptorDtoProgress progress) {
    this.progress = progress;
  }


  public EcfReceptorDto ambiente(@javax.annotation.Nullable String ambiente) {
    this.ambiente = ambiente;
    return this;
  }

  /**
   * DGII environment serving this tenant (\&quot;Test\&quot;/\&quot;Certification\&quot;/\&quot;Production\&quot;).
   * @return ambiente
   */
  @javax.annotation.Nullable
  public String getAmbiente() {
    return ambiente;
  }

  public void setAmbiente(@javax.annotation.Nullable String ambiente) {
    this.ambiente = ambiente;
  }


  public EcfReceptorDto urlImpresion(@javax.annotation.Nullable String urlImpresion) {
    this.urlImpresion = urlImpresion;
    return this;
  }

  /**
   * DGII consulta-timbre URL with QR query string.
   * @return urlImpresion
   */
  @javax.annotation.Nullable
  public String getUrlImpresion() {
    return urlImpresion;
  }

  public void setUrlImpresion(@javax.annotation.Nullable String urlImpresion) {
    this.urlImpresion = urlImpresion;
  }


  public EcfReceptorDto acecfs(@javax.annotation.Nullable List<AcecfSummaryDto> acecfs) {
    this.acecfs = acecfs;
    return this;
  }

  public EcfReceptorDto addAcecfsItem(AcecfSummaryDto acecfsItem) {
    if (this.acecfs == null) {
      this.acecfs = new ArrayList<>();
    }
    this.acecfs.add(acecfsItem);
    return this;
  }

  /**
   * Get acecfs
   * @return acecfs
   */
  @javax.annotation.Nullable
  public List<AcecfSummaryDto> getAcecfs() {
    return acecfs;
  }

  public void setAcecfs(@javax.annotation.Nullable List<AcecfSummaryDto> acecfs) {
    this.acecfs = acecfs;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EcfReceptorDto ecfReceptorDto = (EcfReceptorDto) o;
    return Objects.equals(this.ecfReceptorId, ecfReceptorDto.ecfReceptorId) &&
        Objects.equals(this.tenantId, ecfReceptorDto.tenantId) &&
        Objects.equals(this.companyRnc, ecfReceptorDto.companyRnc) &&
        Objects.equals(this.encf, ecfReceptorDto.encf) &&
        Objects.equals(this.rncEmisor, ecfReceptorDto.rncEmisor) &&
        Objects.equals(this.rncReceptor, ecfReceptorDto.rncReceptor) &&
        Objects.equals(this.tipoEcf, ecfReceptorDto.tipoEcf) &&
        Objects.equals(this.montoTotal, ecfReceptorDto.montoTotal) &&
        Objects.equals(this.fechaEmision, ecfReceptorDto.fechaEmision) &&
        Objects.equals(this.fileName, ecfReceptorDto.fileName) &&
        Objects.equals(this.rawJsonData, ecfReceptorDto.rawJsonData) &&
        Objects.equals(this.createdOn, ecfReceptorDto.createdOn) &&
        Objects.equals(this.fechaFirma, ecfReceptorDto.fechaFirma) &&
        Objects.equals(this.codSec, ecfReceptorDto.codSec) &&
        Objects.equals(this.estado, ecfReceptorDto.estado) &&
        Objects.equals(this.progress, ecfReceptorDto.progress) &&
        Objects.equals(this.ambiente, ecfReceptorDto.ambiente) &&
        Objects.equals(this.urlImpresion, ecfReceptorDto.urlImpresion) &&
        Objects.equals(this.acecfs, ecfReceptorDto.acecfs);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ecfReceptorId, tenantId, companyRnc, encf, rncEmisor, rncReceptor, tipoEcf, montoTotal, fechaEmision, fileName, rawJsonData, createdOn, fechaFirma, codSec, estado, progress, ambiente, urlImpresion, acecfs);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EcfReceptorDto {\n");
    sb.append("    ecfReceptorId: ").append(toIndentedString(ecfReceptorId)).append("\n");
    sb.append("    tenantId: ").append(toIndentedString(tenantId)).append("\n");
    sb.append("    companyRnc: ").append(toIndentedString(companyRnc)).append("\n");
    sb.append("    encf: ").append(toIndentedString(encf)).append("\n");
    sb.append("    rncEmisor: ").append(toIndentedString(rncEmisor)).append("\n");
    sb.append("    rncReceptor: ").append(toIndentedString(rncReceptor)).append("\n");
    sb.append("    tipoEcf: ").append(toIndentedString(tipoEcf)).append("\n");
    sb.append("    montoTotal: ").append(toIndentedString(montoTotal)).append("\n");
    sb.append("    fechaEmision: ").append(toIndentedString(fechaEmision)).append("\n");
    sb.append("    fileName: ").append(toIndentedString(fileName)).append("\n");
    sb.append("    rawJsonData: ").append(toIndentedString(rawJsonData)).append("\n");
    sb.append("    createdOn: ").append(toIndentedString(createdOn)).append("\n");
    sb.append("    fechaFirma: ").append(toIndentedString(fechaFirma)).append("\n");
    sb.append("    codSec: ").append(toIndentedString(codSec)).append("\n");
    sb.append("    estado: ").append(toIndentedString(estado)).append("\n");
    sb.append("    progress: ").append(toIndentedString(progress)).append("\n");
    sb.append("    ambiente: ").append(toIndentedString(ambiente)).append("\n");
    sb.append("    urlImpresion: ").append(toIndentedString(urlImpresion)).append("\n");
    sb.append("    acecfs: ").append(toIndentedString(acecfs)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("ecfReceptorId", "tenantId", "companyRnc", "encf", "rncEmisor", "rncReceptor", "tipoEcf", "montoTotal", "fechaEmision", "fileName", "rawJsonData", "createdOn", "fechaFirma", "codSec", "estado", "progress", "ambiente", "urlImpresion", "acecfs"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to EcfReceptorDto
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!EcfReceptorDto.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in EcfReceptorDto is not found in the empty JSON string", EcfReceptorDto.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!EcfReceptorDto.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `EcfReceptorDto` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("ecfReceptorId") != null && !jsonObj.get("ecfReceptorId").isJsonNull()) && !jsonObj.get("ecfReceptorId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `ecfReceptorId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("ecfReceptorId").toString()));
      }
      if ((jsonObj.get("tenantId") != null && !jsonObj.get("tenantId").isJsonNull()) && !jsonObj.get("tenantId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `tenantId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("tenantId").toString()));
      }
      if ((jsonObj.get("companyRnc") != null && !jsonObj.get("companyRnc").isJsonNull()) && !jsonObj.get("companyRnc").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `companyRnc` to be a primitive type in the JSON string but got `%s`", jsonObj.get("companyRnc").toString()));
      }
      if ((jsonObj.get("encf") != null && !jsonObj.get("encf").isJsonNull()) && !jsonObj.get("encf").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `encf` to be a primitive type in the JSON string but got `%s`", jsonObj.get("encf").toString()));
      }
      if ((jsonObj.get("rncEmisor") != null && !jsonObj.get("rncEmisor").isJsonNull()) && !jsonObj.get("rncEmisor").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `rncEmisor` to be a primitive type in the JSON string but got `%s`", jsonObj.get("rncEmisor").toString()));
      }
      if ((jsonObj.get("rncReceptor") != null && !jsonObj.get("rncReceptor").isJsonNull()) && !jsonObj.get("rncReceptor").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `rncReceptor` to be a primitive type in the JSON string but got `%s`", jsonObj.get("rncReceptor").toString()));
      }
      // validate the optional field `tipoEcf`
      if (jsonObj.get("tipoEcf") != null && !jsonObj.get("tipoEcf").isJsonNull()) {
        AllTipoECFTypes.validateJsonElement(jsonObj.get("tipoEcf"));
      }
      // validate the optional field `montoTotal`
      if (jsonObj.get("montoTotal") != null && !jsonObj.get("montoTotal").isJsonNull()) {
        SearchEcfsAmountFromParameter.validateJsonElement(jsonObj.get("montoTotal"));
      }
      if ((jsonObj.get("fileName") != null && !jsonObj.get("fileName").isJsonNull()) && !jsonObj.get("fileName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `fileName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("fileName").toString()));
      }
      if ((jsonObj.get("rawJsonData") != null && !jsonObj.get("rawJsonData").isJsonNull()) && !jsonObj.get("rawJsonData").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `rawJsonData` to be a primitive type in the JSON string but got `%s`", jsonObj.get("rawJsonData").toString()));
      }
      if ((jsonObj.get("codSec") != null && !jsonObj.get("codSec").isJsonNull()) && !jsonObj.get("codSec").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `codSec` to be a primitive type in the JSON string but got `%s`", jsonObj.get("codSec").toString()));
      }
      // validate the optional field `estado`
      if (jsonObj.get("estado") != null && !jsonObj.get("estado").isJsonNull()) {
        EcfReceptorDtoEstado.validateJsonElement(jsonObj.get("estado"));
      }
      // validate the optional field `progress`
      if (jsonObj.get("progress") != null && !jsonObj.get("progress").isJsonNull()) {
        EcfReceptorDtoProgress.validateJsonElement(jsonObj.get("progress"));
      }
      if ((jsonObj.get("ambiente") != null && !jsonObj.get("ambiente").isJsonNull()) && !jsonObj.get("ambiente").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `ambiente` to be a primitive type in the JSON string but got `%s`", jsonObj.get("ambiente").toString()));
      }
      if ((jsonObj.get("urlImpresion") != null && !jsonObj.get("urlImpresion").isJsonNull()) && !jsonObj.get("urlImpresion").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `urlImpresion` to be a primitive type in the JSON string but got `%s`", jsonObj.get("urlImpresion").toString()));
      }
      if (jsonObj.get("acecfs") != null && !jsonObj.get("acecfs").isJsonNull()) {
        JsonArray jsonArrayacecfs = jsonObj.getAsJsonArray("acecfs");
        if (jsonArrayacecfs != null) {
          // ensure the json data is an array
          if (!jsonObj.get("acecfs").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `acecfs` to be an array in the JSON string but got `%s`", jsonObj.get("acecfs").toString()));
          }

          // validate the optional field `acecfs` (array)
          for (int i = 0; i < jsonArrayacecfs.size(); i++) {
            AcecfSummaryDto.validateJsonElement(jsonArrayacecfs.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!EcfReceptorDto.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'EcfReceptorDto' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<EcfReceptorDto> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(EcfReceptorDto.class));

       return (TypeAdapter<T>) new TypeAdapter<EcfReceptorDto>() {
           @Override
           public void write(JsonWriter out, EcfReceptorDto value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public EcfReceptorDto read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of EcfReceptorDto given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of EcfReceptorDto
   * @throws IOException if the JSON string is invalid with respect to EcfReceptorDto
   */
  public static EcfReceptorDto fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, EcfReceptorDto.class);
  }

  /**
   * Convert an instance of EcfReceptorDto to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

