/*
 * ECF API
 * ECF API (Electronic Fiscal Receipt).
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dom.com.ssd.ecfx.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import dom.com.ssd.ecfx.client.model.MensajeCodigo;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import dom.com.ssd.ecfx.client.JSON;

/**
 * Representa un mensaje asociado al estado de validación de un comprobante fiscal electrónico (e-CF). Este modelo se utiliza en las respuestas de consulta de resultado para proporcionar información detallada sobre el estado de procesamiento y cualquier mensaje relacionado.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.20.0")
public class Mensaje {
  public static final String SERIALIZED_NAME_VALOR = "valor";
  @SerializedName(SERIALIZED_NAME_VALOR)
  @javax.annotation.Nullable
  private String valor;

  public static final String SERIALIZED_NAME_CODIGO = "codigo";
  @SerializedName(SERIALIZED_NAME_CODIGO)
  @javax.annotation.Nullable
  private MensajeCodigo codigo;

  public Mensaje() {
  }

  public Mensaje valor(@javax.annotation.Nullable String valor) {
    this.valor = valor;
    return this;
  }

  /**
   * Obtiene el valor textual del mensaje que describe el estado o resultado de la validación. El texto descriptivo del mensaje. Puede ser null si no hay mensaje disponible.
   * @return valor
   */
  @javax.annotation.Nullable
  public String getValor() {
    return valor;
  }

  public void setValor(@javax.annotation.Nullable String valor) {
    this.valor = valor;
  }


  public Mensaje codigo(@javax.annotation.Nullable MensajeCodigo codigo) {
    this.codigo = codigo;
    return this;
  }

  /**
   * Get codigo
   * @return codigo
   */
  @javax.annotation.Nullable
  public MensajeCodigo getCodigo() {
    return codigo;
  }

  public void setCodigo(@javax.annotation.Nullable MensajeCodigo codigo) {
    this.codigo = codigo;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Mensaje mensaje = (Mensaje) o;
    return Objects.equals(this.valor, mensaje.valor) &&
        Objects.equals(this.codigo, mensaje.codigo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(valor, codigo);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Mensaje {\n");
    sb.append("    valor: ").append(toIndentedString(valor)).append("\n");
    sb.append("    codigo: ").append(toIndentedString(codigo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("valor", "codigo"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to Mensaje
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!Mensaje.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in Mensaje is not found in the empty JSON string", Mensaje.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!Mensaje.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `Mensaje` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("valor") != null && !jsonObj.get("valor").isJsonNull()) && !jsonObj.get("valor").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `valor` to be a primitive type in the JSON string but got `%s`", jsonObj.get("valor").toString()));
      }
      // validate the optional field `codigo`
      if (jsonObj.get("codigo") != null && !jsonObj.get("codigo").isJsonNull()) {
        MensajeCodigo.validateJsonElement(jsonObj.get("codigo"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Mensaje.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Mensaje' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Mensaje> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Mensaje.class));

       return (TypeAdapter<T>) new TypeAdapter<Mensaje>() {
           @Override
           public void write(JsonWriter out, Mensaje value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public Mensaje read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of Mensaje given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of Mensaje
   * @throws IOException if the JSON string is invalid with respect to Mensaje
   */
  public static Mensaje fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Mensaje.class);
  }

  /**
   * Convert an instance of Mensaje to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

