/*
 * ECF API
 * ECF API (Electronic Fiscal Receipt).
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dom.com.ssd.ecfx.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import dom.com.ssd.ecfx.client.model.DescuentoORecargoMontoDescuentooRecargo;
import dom.com.ssd.ecfx.client.model.IdDocTotalPaginas;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import dom.com.ssd.ecfx.client.JSON;

/**
 * Subtotal
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.20.0")
public class Subtotal {
  public static final String SERIALIZED_NAME_NUMERO_SUB_TOTAL = "numeroSubTotal";
  @SerializedName(SERIALIZED_NAME_NUMERO_SUB_TOTAL)
  @javax.annotation.Nullable
  private IdDocTotalPaginas numeroSubTotal;

  public static final String SERIALIZED_NAME_DESCRIPCION_SUBTOTAL = "descripcionSubtotal";
  @SerializedName(SERIALIZED_NAME_DESCRIPCION_SUBTOTAL)
  @javax.annotation.Nullable
  private String descripcionSubtotal;

  public static final String SERIALIZED_NAME_ORDEN = "orden";
  @SerializedName(SERIALIZED_NAME_ORDEN)
  @javax.annotation.Nullable
  private IdDocTotalPaginas orden;

  public static final String SERIALIZED_NAME_SUB_TOTAL_EXENTO = "subTotalExento";
  @SerializedName(SERIALIZED_NAME_SUB_TOTAL_EXENTO)
  @javax.annotation.Nullable
  private DescuentoORecargoMontoDescuentooRecargo subTotalExento;

  public static final String SERIALIZED_NAME_MONTO_SUB_TOTAL = "montoSubTotal";
  @SerializedName(SERIALIZED_NAME_MONTO_SUB_TOTAL)
  @javax.annotation.Nullable
  private DescuentoORecargoMontoDescuentooRecargo montoSubTotal;

  public static final String SERIALIZED_NAME_LINEAS = "lineas";
  @SerializedName(SERIALIZED_NAME_LINEAS)
  @javax.annotation.Nullable
  private IdDocTotalPaginas lineas;

  public Subtotal() {
  }

  public Subtotal numeroSubTotal(@javax.annotation.Nullable IdDocTotalPaginas numeroSubTotal) {
    this.numeroSubTotal = numeroSubTotal;
    return this;
  }

  /**
   * Get numeroSubTotal
   * @return numeroSubTotal
   */
  @javax.annotation.Nullable
  public IdDocTotalPaginas getNumeroSubTotal() {
    return numeroSubTotal;
  }

  public void setNumeroSubTotal(@javax.annotation.Nullable IdDocTotalPaginas numeroSubTotal) {
    this.numeroSubTotal = numeroSubTotal;
  }


  public Subtotal descripcionSubtotal(@javax.annotation.Nullable String descripcionSubtotal) {
    this.descripcionSubtotal = descripcionSubtotal;
    return this;
  }

  /**
   * Get descripcionSubtotal
   * @return descripcionSubtotal
   */
  @javax.annotation.Nullable
  public String getDescripcionSubtotal() {
    return descripcionSubtotal;
  }

  public void setDescripcionSubtotal(@javax.annotation.Nullable String descripcionSubtotal) {
    this.descripcionSubtotal = descripcionSubtotal;
  }


  public Subtotal orden(@javax.annotation.Nullable IdDocTotalPaginas orden) {
    this.orden = orden;
    return this;
  }

  /**
   * Get orden
   * @return orden
   */
  @javax.annotation.Nullable
  public IdDocTotalPaginas getOrden() {
    return orden;
  }

  public void setOrden(@javax.annotation.Nullable IdDocTotalPaginas orden) {
    this.orden = orden;
  }


  public Subtotal subTotalExento(@javax.annotation.Nullable DescuentoORecargoMontoDescuentooRecargo subTotalExento) {
    this.subTotalExento = subTotalExento;
    return this;
  }

  /**
   * Get subTotalExento
   * @return subTotalExento
   */
  @javax.annotation.Nullable
  public DescuentoORecargoMontoDescuentooRecargo getSubTotalExento() {
    return subTotalExento;
  }

  public void setSubTotalExento(@javax.annotation.Nullable DescuentoORecargoMontoDescuentooRecargo subTotalExento) {
    this.subTotalExento = subTotalExento;
  }


  public Subtotal montoSubTotal(@javax.annotation.Nullable DescuentoORecargoMontoDescuentooRecargo montoSubTotal) {
    this.montoSubTotal = montoSubTotal;
    return this;
  }

  /**
   * Get montoSubTotal
   * @return montoSubTotal
   */
  @javax.annotation.Nullable
  public DescuentoORecargoMontoDescuentooRecargo getMontoSubTotal() {
    return montoSubTotal;
  }

  public void setMontoSubTotal(@javax.annotation.Nullable DescuentoORecargoMontoDescuentooRecargo montoSubTotal) {
    this.montoSubTotal = montoSubTotal;
  }


  public Subtotal lineas(@javax.annotation.Nullable IdDocTotalPaginas lineas) {
    this.lineas = lineas;
    return this;
  }

  /**
   * Get lineas
   * @return lineas
   */
  @javax.annotation.Nullable
  public IdDocTotalPaginas getLineas() {
    return lineas;
  }

  public void setLineas(@javax.annotation.Nullable IdDocTotalPaginas lineas) {
    this.lineas = lineas;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Subtotal subtotal = (Subtotal) o;
    return Objects.equals(this.numeroSubTotal, subtotal.numeroSubTotal) &&
        Objects.equals(this.descripcionSubtotal, subtotal.descripcionSubtotal) &&
        Objects.equals(this.orden, subtotal.orden) &&
        Objects.equals(this.subTotalExento, subtotal.subTotalExento) &&
        Objects.equals(this.montoSubTotal, subtotal.montoSubTotal) &&
        Objects.equals(this.lineas, subtotal.lineas);
  }

  @Override
  public int hashCode() {
    return Objects.hash(numeroSubTotal, descripcionSubtotal, orden, subTotalExento, montoSubTotal, lineas);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Subtotal {\n");
    sb.append("    numeroSubTotal: ").append(toIndentedString(numeroSubTotal)).append("\n");
    sb.append("    descripcionSubtotal: ").append(toIndentedString(descripcionSubtotal)).append("\n");
    sb.append("    orden: ").append(toIndentedString(orden)).append("\n");
    sb.append("    subTotalExento: ").append(toIndentedString(subTotalExento)).append("\n");
    sb.append("    montoSubTotal: ").append(toIndentedString(montoSubTotal)).append("\n");
    sb.append("    lineas: ").append(toIndentedString(lineas)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("numeroSubTotal", "descripcionSubtotal", "orden", "subTotalExento", "montoSubTotal", "lineas"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to Subtotal
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!Subtotal.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in Subtotal is not found in the empty JSON string", Subtotal.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!Subtotal.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `Subtotal` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `numeroSubTotal`
      if (jsonObj.get("numeroSubTotal") != null && !jsonObj.get("numeroSubTotal").isJsonNull()) {
        IdDocTotalPaginas.validateJsonElement(jsonObj.get("numeroSubTotal"));
      }
      if ((jsonObj.get("descripcionSubtotal") != null && !jsonObj.get("descripcionSubtotal").isJsonNull()) && !jsonObj.get("descripcionSubtotal").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `descripcionSubtotal` to be a primitive type in the JSON string but got `%s`", jsonObj.get("descripcionSubtotal").toString()));
      }
      // validate the optional field `orden`
      if (jsonObj.get("orden") != null && !jsonObj.get("orden").isJsonNull()) {
        IdDocTotalPaginas.validateJsonElement(jsonObj.get("orden"));
      }
      // validate the optional field `subTotalExento`
      if (jsonObj.get("subTotalExento") != null && !jsonObj.get("subTotalExento").isJsonNull()) {
        DescuentoORecargoMontoDescuentooRecargo.validateJsonElement(jsonObj.get("subTotalExento"));
      }
      // validate the optional field `montoSubTotal`
      if (jsonObj.get("montoSubTotal") != null && !jsonObj.get("montoSubTotal").isJsonNull()) {
        DescuentoORecargoMontoDescuentooRecargo.validateJsonElement(jsonObj.get("montoSubTotal"));
      }
      // validate the optional field `lineas`
      if (jsonObj.get("lineas") != null && !jsonObj.get("lineas").isJsonNull()) {
        IdDocTotalPaginas.validateJsonElement(jsonObj.get("lineas"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Subtotal.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Subtotal' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Subtotal> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Subtotal.class));

       return (TypeAdapter<T>) new TypeAdapter<Subtotal>() {
           @Override
           public void write(JsonWriter out, Subtotal value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public Subtotal read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of Subtotal given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of Subtotal
   * @throws IOException if the JSON string is invalid with respect to Subtotal
   */
  public static Subtotal fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Subtotal.class);
  }

  /**
   * Convert an instance of Subtotal to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

