/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ecfx.sdk.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Representa una entrada del directorio para contribuyentes electrónicos en el sistema de facturación electrónica  de la República Dominicana. Este modelo contiene las URLs de servicios que los contribuyentes electrónicos  deben proporcionar para la comunicación entre contribuyentes.
 *
 * @param nombre Obtiene el nombre legal o razón social del contribuyente electrónico. La razón social registrada tal como aparece en el registro oficial del contribuyente. Este campo es requerido y debe coincidir con el nombre de la entidad legal del contribuyente.
 * @param rnc Obtiene el Número de Registro Nacional del Contribuyente (RNC) del contribuyente electrónico. Un número de 9 dígitos que identifica de forma única al contribuyente en el sistema tributario  de la República Dominicana. Este campo es requerido y debe tener un formato de RNC válido.
 * @param urlRecepcion Obtiene la URL del servicio de recepción de facturas electrónicas. La URL completa donde otros contribuyentes pueden enviar facturas electrónicas (e-CF) a este contribuyente. Debe seguir el formato estándar: https://host/ambiente/nombreservicio/fe/recepcion/api/ecf Este campo es obligatorio para todos los contribuyentes electrónicos.
 * @param urlAceptacion Obtiene la URL del servicio de aprobación comercial. La URL completa donde otros contribuyentes pueden enviar aprobaciones comerciales para facturas recibidas. Debe seguir el formato estándar: https://host/ambiente/nombreservicio/fe/aprobacioncomercial/api/ecf Este campo es obligatorio para todos los contribuyentes electrónicos.
 * @param urlOpcional Obtiene la URL del servicio opcional de autenticación. La URL base del servicio de autenticación, si es implementado por el contribuyente. Debe seguir el formato estándar: https://host/ambiente/nombreservicio/fe/autenticacion/api/ Este campo es opcional pero recomendado para mayor seguridad.
 */
@Serializable

data class Directorio (

    /* Obtiene el nombre legal o razón social del contribuyente electrónico. La razón social registrada tal como aparece en el registro oficial del contribuyente. Este campo es requerido y debe coincidir con el nombre de la entidad legal del contribuyente. */
    @SerialName(value = "nombre")
    val nombre: kotlin.String? = null,

    /* Obtiene el Número de Registro Nacional del Contribuyente (RNC) del contribuyente electrónico. Un número de 9 dígitos que identifica de forma única al contribuyente en el sistema tributario  de la República Dominicana. Este campo es requerido y debe tener un formato de RNC válido. */
    @SerialName(value = "rnc")
    val rnc: kotlin.String? = null,

    /* Obtiene la URL del servicio de recepción de facturas electrónicas. La URL completa donde otros contribuyentes pueden enviar facturas electrónicas (e-CF) a este contribuyente. Debe seguir el formato estándar: https://host/ambiente/nombreservicio/fe/recepcion/api/ecf Este campo es obligatorio para todos los contribuyentes electrónicos. */
    @SerialName(value = "urlRecepcion")
    val urlRecepcion: kotlin.String? = null,

    /* Obtiene la URL del servicio de aprobación comercial. La URL completa donde otros contribuyentes pueden enviar aprobaciones comerciales para facturas recibidas. Debe seguir el formato estándar: https://host/ambiente/nombreservicio/fe/aprobacioncomercial/api/ecf Este campo es obligatorio para todos los contribuyentes electrónicos. */
    @SerialName(value = "urlAceptacion")
    val urlAceptacion: kotlin.String? = null,

    /* Obtiene la URL del servicio opcional de autenticación. La URL base del servicio de autenticación, si es implementado por el contribuyente. Debe seguir el formato estándar: https://host/ambiente/nombreservicio/fe/autenticacion/api/ Este campo es opcional pero recomendado para mayor seguridad. */
    @SerialName(value = "urlOpcional")
    val urlOpcional: kotlin.String? = null

) {


}

