/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ecfx.sdk.models

import com.ecfx.sdk.models.Ecf31IdDocTotalPaginas
import com.ecfx.sdk.models.Ecf45FormaDePago
import com.ecfx.sdk.models.Ecf45TipoIngresosValidationType
import com.ecfx.sdk.models.Ecf45TipoPagoType
import com.ecfx.sdk.models.IndicadorEnvioDiferidoType
import com.ecfx.sdk.models.IndicadorMontoGravadoType
import com.ecfx.sdk.models.IndicadorServicioTodoIncluidoType
import com.ecfx.sdk.models.TipoCuentaPagoType
import com.ecfx.sdk.models.TipoeCFType

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param tipoeCF 
 * @param encf 
 * @param tipoIngresos 
 * @param tipoPago 
 * @param fechaVencimientoSecuencia 
 * @param indicadorEnvioDiferido 
 * @param indicadorMontoGravado 
 * @param indicadorServicioTodoIncluido 
 * @param fechaLimitePago 
 * @param terminoPago 
 * @param tablaFormasPago 
 * @param tipoCuentaPago 
 * @param numeroCuentaPago 
 * @param bancoPago 
 * @param fechaDesde 
 * @param fechaHasta 
 * @param totalPaginas 
 */
@Serializable

data class Ecf45IdDoc (

    @Contextual @SerialName(value = "tipoeCF")
    val tipoeCF: TipoeCFType,

    @SerialName(value = "encf")
    val encf: kotlin.String,

    @Contextual @SerialName(value = "tipoIngresos")
    val tipoIngresos: Ecf45TipoIngresosValidationType,

    @Contextual @SerialName(value = "tipoPago")
    val tipoPago: Ecf45TipoPagoType,

    @Contextual @SerialName(value = "fechaVencimientoSecuencia")
    val fechaVencimientoSecuencia: java.time.OffsetDateTime? = null,

    @Contextual @SerialName(value = "indicadorEnvioDiferido")
    val indicadorEnvioDiferido: IndicadorEnvioDiferidoType? = null,

    @Contextual @SerialName(value = "indicadorMontoGravado")
    val indicadorMontoGravado: IndicadorMontoGravadoType? = null,

    @Contextual @SerialName(value = "indicadorServicioTodoIncluido")
    val indicadorServicioTodoIncluido: IndicadorServicioTodoIncluidoType? = null,

    @Contextual @SerialName(value = "fechaLimitePago")
    val fechaLimitePago: java.time.OffsetDateTime? = null,

    @SerialName(value = "terminoPago")
    val terminoPago: kotlin.String? = null,

    @SerialName(value = "tablaFormasPago")
    val tablaFormasPago: kotlin.collections.List<Ecf45FormaDePago>? = null,

    @Contextual @SerialName(value = "tipoCuentaPago")
    val tipoCuentaPago: TipoCuentaPagoType? = null,

    @SerialName(value = "numeroCuentaPago")
    val numeroCuentaPago: kotlin.String? = null,

    @SerialName(value = "bancoPago")
    val bancoPago: kotlin.String? = null,

    @Contextual @SerialName(value = "fechaDesde")
    val fechaDesde: java.time.OffsetDateTime? = null,

    @Contextual @SerialName(value = "fechaHasta")
    val fechaHasta: java.time.OffsetDateTime? = null,

    @SerialName(value = "totalPaginas")
    val totalPaginas: Ecf31IdDocTotalPaginas? = null

) {


}

