/*
 * ECF API
 * ECF API (Electronic Fiscal Receipt).
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dom.com.ssd.ecfx.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import dom.com.ssd.ecfx.client.model.AcecfReceptionRequestDtoProgress;
import java.io.IOException;
import java.util.Arrays;
import java.util.Date;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for AcecfReceptionRequestDto
 */
public class AcecfReceptionRequestDtoTest {
    private final AcecfReceptionRequestDto model = new AcecfReceptionRequestDto();

    /**
     * Model tests for AcecfReceptionRequestDto
     */
    @Test
    public void testAcecfReceptionRequestDto() {
        // TODO: test AcecfReceptionRequestDto
    }

    /**
     * Test the property 'messageId'
     */
    @Test
    public void messageIdTest() {
        // TODO: test messageId
    }

    /**
     * Test the property 'tenantId'
     */
    @Test
    public void tenantIdTest() {
        // TODO: test tenantId
    }

    /**
     * Test the property 'companyRnc'
     */
    @Test
    public void companyRncTest() {
        // TODO: test companyRnc
    }

    /**
     * Test the property 'fileName'
     */
    @Test
    public void fileNameTest() {
        // TODO: test fileName
    }

    /**
     * Test the property 'progress'
     */
    @Test
    public void progressTest() {
        // TODO: test progress
    }

    /**
     * Test the property 'createdOn'
     */
    @Test
    public void createdOnTest() {
        // TODO: test createdOn
    }

    /**
     * Test the property 'updatedOn'
     */
    @Test
    public void updatedOnTest() {
        // TODO: test updatedOn
    }

    /**
     * Test the property 'errorMessage'
     */
    @Test
    public void errorMessageTest() {
        // TODO: test errorMessage
    }

    /**
     * Test the property 'encf'
     */
    @Test
    public void encfTest() {
        // TODO: test encf
    }

    /**
     * Test the property 'rncEmisor'
     */
    @Test
    public void rncEmisorTest() {
        // TODO: test rncEmisor
    }

}
