/*
 * ECF API
 * ECF API (Electronic Fiscal Receipt).
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dom.com.ssd.ecfx.client.model;

import java.math.BigDecimal;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ImpuestoAdicional2TasaImpuestoAdicional
 */
public class ImpuestoAdicional2TasaImpuestoAdicionalTest {
    private final ImpuestoAdicional2TasaImpuestoAdicional model = new ImpuestoAdicional2TasaImpuestoAdicional();

    /**
     * Model tests for ImpuestoAdicional2TasaImpuestoAdicional
     */
    @Test
    public void testImpuestoAdicional2TasaImpuestoAdicional() {
        // TODO: test ImpuestoAdicional2TasaImpuestoAdicional
    }

}
