/*
 * ECF API
 * ECF API (Electronic Fiscal Receipt).
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dom.com.ssd.ecfx.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import dom.com.ssd.ecfx.client.model.CodificacionTipoImpuestosType;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ImpuestoAdicional
 */
public class ImpuestoAdicionalTest {
    private final ImpuestoAdicional model = new ImpuestoAdicional();

    /**
     * Model tests for ImpuestoAdicional
     */
    @Test
    public void testImpuestoAdicional() {
        // TODO: test ImpuestoAdicional
    }

    /**
     * Test the property 'tipoImpuesto'
     */
    @Test
    public void tipoImpuestoTest() {
        // TODO: test tipoImpuesto
    }

}
