/*
 * ECF API
 * ECF API (Electronic Fiscal Receipt).
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dom.com.ssd.ecfx.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for RespuestaConsultaTimbre
 */
public class RespuestaConsultaTimbreTest {
    private final RespuestaConsultaTimbre model = new RespuestaConsultaTimbre();

    /**
     * Model tests for RespuestaConsultaTimbre
     */
    @Test
    public void testRespuestaConsultaTimbre() {
        // TODO: test RespuestaConsultaTimbre
    }

    /**
     * Test the property 'rncEmisor'
     */
    @Test
    public void rncEmisorTest() {
        // TODO: test rncEmisor
    }

    /**
     * Test the property 'razonSocial'
     */
    @Test
    public void razonSocialTest() {
        // TODO: test razonSocial
    }

    /**
     * Test the property 'encf'
     */
    @Test
    public void encfTest() {
        // TODO: test encf
    }

    /**
     * Test the property 'estado'
     */
    @Test
    public void estadoTest() {
        // TODO: test estado
    }

}
