/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dom.com.ssd.ecfx.sdk.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import dom.com.ssd.ecfx.sdk.apis.EcfApi
import dom.com.ssd.ecfx.sdk.models.AllTipoECFTypes
import dom.com.ssd.ecfx.sdk.models.AnulacionRequest
import dom.com.ssd.ecfx.sdk.models.ECFType
import dom.com.ssd.ecfx.sdk.models.Ecf31ECF
import dom.com.ssd.ecfx.sdk.models.Ecf32ECF
import dom.com.ssd.ecfx.sdk.models.Ecf33ECF
import dom.com.ssd.ecfx.sdk.models.Ecf34ECF
import dom.com.ssd.ecfx.sdk.models.Ecf41ECF
import dom.com.ssd.ecfx.sdk.models.Ecf43ECF
import dom.com.ssd.ecfx.sdk.models.Ecf44ECF
import dom.com.ssd.ecfx.sdk.models.Ecf45ECF
import dom.com.ssd.ecfx.sdk.models.Ecf46ECF
import dom.com.ssd.ecfx.sdk.models.Ecf47ECF
import dom.com.ssd.ecfx.sdk.models.EcfResponse
import dom.com.ssd.ecfx.sdk.models.GetCompaniesLimitParameter
import dom.com.ssd.ecfx.sdk.models.GetCompaniesPageParameter
import dom.com.ssd.ecfx.sdk.models.PaginatedApiResultOfAnulacionListResponse
import dom.com.ssd.ecfx.sdk.models.PaginatedApiResultOfEcfResponse
import dom.com.ssd.ecfx.sdk.models.ProblemDetails
import dom.com.ssd.ecfx.sdk.models.RespuestaAnulacionRango
import dom.com.ssd.ecfx.sdk.models.SearchEcfsAmountFromParameter
import dom.com.ssd.ecfx.sdk.models.SendAcecfRequest

class EcfApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of EcfApi
        //val apiInstance = EcfApi()

        // to test anulacionRangos
        should("test anulacionRangos") {
            // uncomment below to test anulacionRangos
            //val rnc : kotlin.String = rnc_example // kotlin.String | 
            //val anulacionRequest : AnulacionRequest =  // AnulacionRequest | 
            //val result : RespuestaAnulacionRango = apiInstance.anulacionRangos(rnc, anulacionRequest)
            //result shouldBe ("TODO")
        }

        // to test aprobacionComercial
        should("test aprobacionComercial") {
            // uncomment below to test aprobacionComercial
            //val rnc : kotlin.String = rnc_example // kotlin.String | 
            //val encf : kotlin.String = encf_example // kotlin.String | 
            //val sendAcecfRequest : SendAcecfRequest =  // SendAcecfRequest | 
            //apiInstance.aprobacionComercial(rnc, encf, sendAcecfRequest)
        }

        // to test firmarSemilla
        should("test firmarSemilla") {
            // uncomment below to test firmarSemilla
            //val rnc : kotlin.String = rnc_example // kotlin.String | 
            //val xml : java.io.File = BINARY_DATA_HERE // java.io.File | 
            //apiInstance.firmarSemilla(rnc, xml)
        }

        // to test getEcfById
        should("test getEcfById") {
            // uncomment below to test getEcfById
            //val rnc : kotlin.String = rnc_example // kotlin.String | 
            //val id : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val includeEcfContent : kotlin.Boolean = true // kotlin.Boolean | 
            //val result : kotlin.collections.List<EcfResponse> = apiInstance.getEcfById(rnc, id, includeEcfContent)
            //result shouldBe ("TODO")
        }

        // to test listAnulaciones
        should("test listAnulaciones") {
            // uncomment below to test listAnulaciones
            //val tipoEcf : kotlin.collections.List<ECFType> =  // kotlin.collections.List<ECFType> | 
            //val rncs : kotlin.collections.List<kotlin.String> =  // kotlin.collections.List<kotlin.String> | 
            //val fechaDesde : java.time.OffsetDateTime = 2013-10-20T19:20:30+01:00 // java.time.OffsetDateTime | 
            //val fechaHasta : java.time.OffsetDateTime = 2013-10-20T19:20:30+01:00 // java.time.OffsetDateTime | 
            //val page : GetCompaniesPageParameter = 56 // GetCompaniesPageParameter | 
            //val limit : GetCompaniesLimitParameter = 56 // GetCompaniesLimitParameter | 
            //val result : PaginatedApiResultOfAnulacionListResponse = apiInstance.listAnulaciones(tipoEcf, rncs, fechaDesde, fechaHasta, page, limit)
            //result shouldBe ("TODO")
        }

        // to test queryEcf
        should("test queryEcf") {
            // uncomment below to test queryEcf
            //val rnc : kotlin.String = rnc_example // kotlin.String | 
            //val encf : kotlin.String = encf_example // kotlin.String | 
            //val includeEcfContent : kotlin.Boolean = true // kotlin.Boolean | 
            //val result : kotlin.collections.List<EcfResponse> = apiInstance.queryEcf(rnc, encf, includeEcfContent)
            //result shouldBe ("TODO")
        }

        // to test recepcionEcf31
        should("test recepcionEcf31") {
            // uncomment below to test recepcionEcf31
            //val ecf31ECF : Ecf31ECF =  // Ecf31ECF | 
            //val result : EcfResponse = apiInstance.recepcionEcf31(ecf31ECF)
            //result shouldBe ("TODO")
        }

        // to test recepcionEcf32
        should("test recepcionEcf32") {
            // uncomment below to test recepcionEcf32
            //val ecf32ECF : Ecf32ECF =  // Ecf32ECF | 
            //val result : EcfResponse = apiInstance.recepcionEcf32(ecf32ECF)
            //result shouldBe ("TODO")
        }

        // to test recepcionEcf33
        should("test recepcionEcf33") {
            // uncomment below to test recepcionEcf33
            //val ecf33ECF : Ecf33ECF =  // Ecf33ECF | 
            //val result : EcfResponse = apiInstance.recepcionEcf33(ecf33ECF)
            //result shouldBe ("TODO")
        }

        // to test recepcionEcf34
        should("test recepcionEcf34") {
            // uncomment below to test recepcionEcf34
            //val ecf34ECF : Ecf34ECF =  // Ecf34ECF | 
            //val result : EcfResponse = apiInstance.recepcionEcf34(ecf34ECF)
            //result shouldBe ("TODO")
        }

        // to test recepcionEcf41
        should("test recepcionEcf41") {
            // uncomment below to test recepcionEcf41
            //val ecf41ECF : Ecf41ECF =  // Ecf41ECF | 
            //val result : EcfResponse = apiInstance.recepcionEcf41(ecf41ECF)
            //result shouldBe ("TODO")
        }

        // to test recepcionEcf43
        should("test recepcionEcf43") {
            // uncomment below to test recepcionEcf43
            //val ecf43ECF : Ecf43ECF =  // Ecf43ECF | 
            //val result : EcfResponse = apiInstance.recepcionEcf43(ecf43ECF)
            //result shouldBe ("TODO")
        }

        // to test recepcionEcf44
        should("test recepcionEcf44") {
            // uncomment below to test recepcionEcf44
            //val ecf44ECF : Ecf44ECF =  // Ecf44ECF | 
            //val result : EcfResponse = apiInstance.recepcionEcf44(ecf44ECF)
            //result shouldBe ("TODO")
        }

        // to test recepcionEcf45
        should("test recepcionEcf45") {
            // uncomment below to test recepcionEcf45
            //val ecf45ECF : Ecf45ECF =  // Ecf45ECF | 
            //val result : EcfResponse = apiInstance.recepcionEcf45(ecf45ECF)
            //result shouldBe ("TODO")
        }

        // to test recepcionEcf46
        should("test recepcionEcf46") {
            // uncomment below to test recepcionEcf46
            //val ecf46ECF : Ecf46ECF =  // Ecf46ECF | 
            //val result : EcfResponse = apiInstance.recepcionEcf46(ecf46ECF)
            //result shouldBe ("TODO")
        }

        // to test recepcionEcf47
        should("test recepcionEcf47") {
            // uncomment below to test recepcionEcf47
            //val ecf47ECF : Ecf47ECF =  // Ecf47ECF | 
            //val result : EcfResponse = apiInstance.recepcionEcf47(ecf47ECF)
            //result shouldBe ("TODO")
        }

        // to test searchAllEcfs
        should("test searchAllEcfs") {
            // uncomment below to test searchAllEcfs
            //val encfs : kotlin.collections.List<kotlin.String> =  // kotlin.collections.List<kotlin.String> | 
            //val ids : kotlin.collections.List<java.util.UUID> =  // kotlin.collections.List<java.util.UUID> | 
            //val tiposEcfs : kotlin.collections.List<AllTipoECFTypes> =  // kotlin.collections.List<AllTipoECFTypes> | 
            //val includeEcfContent : kotlin.Boolean = true // kotlin.Boolean | 
            //val fromFechaEmision : java.time.OffsetDateTime = 2013-10-20T19:20:30+01:00 // java.time.OffsetDateTime | 
            //val toFechaEmision : java.time.OffsetDateTime = 2013-10-20T19:20:30+01:00 // java.time.OffsetDateTime | 
            //val amountFrom : SearchEcfsAmountFromParameter = 1.2 // SearchEcfsAmountFromParameter | 
            //val amountTo : SearchEcfsAmountFromParameter = 1.2 // SearchEcfsAmountFromParameter | 
            //val page : GetCompaniesPageParameter = 56 // GetCompaniesPageParameter | 
            //val limit : GetCompaniesLimitParameter = 56 // GetCompaniesLimitParameter | 
            //val result : PaginatedApiResultOfEcfResponse = apiInstance.searchAllEcfs(encfs, ids, tiposEcfs, includeEcfContent, fromFechaEmision, toFechaEmision, amountFrom, amountTo, page, limit)
            //result shouldBe ("TODO")
        }

        // to test searchEcfs
        should("test searchEcfs") {
            // uncomment below to test searchEcfs
            //val rnc : kotlin.String = rnc_example // kotlin.String | 
            //val encfs : kotlin.collections.List<kotlin.String> =  // kotlin.collections.List<kotlin.String> | 
            //val ids : kotlin.collections.List<java.util.UUID> =  // kotlin.collections.List<java.util.UUID> | 
            //val tiposEcfs : kotlin.collections.List<AllTipoECFTypes> =  // kotlin.collections.List<AllTipoECFTypes> | 
            //val includeEcfContent : kotlin.Boolean = true // kotlin.Boolean | 
            //val fromFechaEmision : java.time.OffsetDateTime = 2013-10-20T19:20:30+01:00 // java.time.OffsetDateTime | 
            //val toFechaEmision : java.time.OffsetDateTime = 2013-10-20T19:20:30+01:00 // java.time.OffsetDateTime | 
            //val amountFrom : SearchEcfsAmountFromParameter = 1.2 // SearchEcfsAmountFromParameter | 
            //val amountTo : SearchEcfsAmountFromParameter = 1.2 // SearchEcfsAmountFromParameter | 
            //val page : GetCompaniesPageParameter = 56 // GetCompaniesPageParameter | 
            //val limit : GetCompaniesLimitParameter = 56 // GetCompaniesLimitParameter | 
            //val result : PaginatedApiResultOfEcfResponse = apiInstance.searchEcfs(rnc, encfs, ids, tiposEcfs, includeEcfContent, fromFechaEmision, toFechaEmision, amountFrom, amountTo, page, limit)
            //result shouldBe ("TODO")
        }

    }
}
