/*
 * ECF API
 * ECF API (Electronic Fiscal Receipt).
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dom.com.ssd.ecfx.client.api;

import dom.com.ssd.ecfx.client.ApiException;
import dom.com.ssd.ecfx.client.model.AllTipoECFTypes;
import dom.com.ssd.ecfx.client.model.AnulacionRequest;
import java.util.Date;
import dom.com.ssd.ecfx.client.model.ECFType;
import dom.com.ssd.ecfx.client.model.Ecf31ECF;
import dom.com.ssd.ecfx.client.model.Ecf32ECF;
import dom.com.ssd.ecfx.client.model.Ecf33ECF;
import dom.com.ssd.ecfx.client.model.Ecf34ECF;
import dom.com.ssd.ecfx.client.model.Ecf41ECF;
import dom.com.ssd.ecfx.client.model.Ecf43ECF;
import dom.com.ssd.ecfx.client.model.Ecf44ECF;
import dom.com.ssd.ecfx.client.model.Ecf45ECF;
import dom.com.ssd.ecfx.client.model.Ecf46ECF;
import dom.com.ssd.ecfx.client.model.Ecf47ECF;
import dom.com.ssd.ecfx.client.model.EcfEstado;
import dom.com.ssd.ecfx.client.model.EcfProgress;
import dom.com.ssd.ecfx.client.model.EcfResponse;
import java.io.File;
import dom.com.ssd.ecfx.client.model.GetCompaniesLimitParameter;
import dom.com.ssd.ecfx.client.model.GetCompaniesPageParameter;
import dom.com.ssd.ecfx.client.model.PaginatedApiResultOfAnulacionListResponse;
import dom.com.ssd.ecfx.client.model.PaginatedApiResultOfEcfResponse;
import dom.com.ssd.ecfx.client.model.ProblemDetails;
import dom.com.ssd.ecfx.client.model.RespuestaAnulacionRango;
import dom.com.ssd.ecfx.client.model.SearchEcfsAmountFromParameter;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for EcfApi
 */
@Disabled
public class EcfApiTest {

    private final EcfApi api = new EcfApi();

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void anulacionRangosTest() throws ApiException {
        String rnc = null;
        AnulacionRequest anulacionRequest = null;
        RespuestaAnulacionRango response = api.anulacionRangos(rnc, anulacionRequest);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void firmarSemillaTest() throws ApiException {
        String rnc = null;
        File xml = null;
        api.firmarSemilla(rnc, xml);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getEcfByIdTest() throws ApiException {
        String rnc = null;
        UUID id = null;
        Boolean includeEcfContent = null;
        List<EcfResponse> response = api.getEcfById(rnc, id, includeEcfContent);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listAnulacionesTest() throws ApiException {
        List<ECFType> tipoEcf = null;
        List<String> rncs = null;
        Date fechaDesde = null;
        Date fechaHasta = null;
        GetCompaniesPageParameter page = null;
        GetCompaniesLimitParameter limit = null;
        PaginatedApiResultOfAnulacionListResponse response = api.listAnulaciones(tipoEcf, rncs, fechaDesde, fechaHasta, page, limit);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void queryEcfTest() throws ApiException {
        String rnc = null;
        String encf = null;
        Boolean includeEcfContent = null;
        List<EcfResponse> response = api.queryEcf(rnc, encf, includeEcfContent);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void recepcionEcf31Test() throws ApiException {
        Ecf31ECF ecf31ECF = null;
        EcfResponse response = api.recepcionEcf31(ecf31ECF);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void recepcionEcf32Test() throws ApiException {
        Ecf32ECF ecf32ECF = null;
        EcfResponse response = api.recepcionEcf32(ecf32ECF);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void recepcionEcf33Test() throws ApiException {
        Ecf33ECF ecf33ECF = null;
        EcfResponse response = api.recepcionEcf33(ecf33ECF);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void recepcionEcf34Test() throws ApiException {
        Ecf34ECF ecf34ECF = null;
        EcfResponse response = api.recepcionEcf34(ecf34ECF);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void recepcionEcf41Test() throws ApiException {
        Ecf41ECF ecf41ECF = null;
        EcfResponse response = api.recepcionEcf41(ecf41ECF);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void recepcionEcf43Test() throws ApiException {
        Ecf43ECF ecf43ECF = null;
        EcfResponse response = api.recepcionEcf43(ecf43ECF);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void recepcionEcf44Test() throws ApiException {
        Ecf44ECF ecf44ECF = null;
        EcfResponse response = api.recepcionEcf44(ecf44ECF);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void recepcionEcf45Test() throws ApiException {
        Ecf45ECF ecf45ECF = null;
        EcfResponse response = api.recepcionEcf45(ecf45ECF);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void recepcionEcf46Test() throws ApiException {
        Ecf46ECF ecf46ECF = null;
        EcfResponse response = api.recepcionEcf46(ecf46ECF);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void recepcionEcf47Test() throws ApiException {
        Ecf47ECF ecf47ECF = null;
        EcfResponse response = api.recepcionEcf47(ecf47ECF);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void searchAllEcfsTest() throws ApiException {
        List<String> encfs = null;
        List<UUID> ids = null;
        List<AllTipoECFTypes> tiposEcfs = null;
        Boolean includeEcfContent = null;
        Date fromFechaEmision = null;
        Date toFechaEmision = null;
        SearchEcfsAmountFromParameter amountFrom = null;
        SearchEcfsAmountFromParameter amountTo = null;
        List<EcfProgress> progresses = null;
        List<EcfEstado> dgiiEstados = null;
        GetCompaniesPageParameter page = null;
        GetCompaniesLimitParameter limit = null;
        PaginatedApiResultOfEcfResponse response = api.searchAllEcfs(encfs, ids, tiposEcfs, includeEcfContent, fromFechaEmision, toFechaEmision, amountFrom, amountTo, progresses, dgiiEstados, page, limit);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void searchEcfsTest() throws ApiException {
        String rnc = null;
        List<String> encfs = null;
        List<UUID> ids = null;
        List<AllTipoECFTypes> tiposEcfs = null;
        Boolean includeEcfContent = null;
        Date fromFechaEmision = null;
        Date toFechaEmision = null;
        SearchEcfsAmountFromParameter amountFrom = null;
        SearchEcfsAmountFromParameter amountTo = null;
        List<EcfProgress> progresses = null;
        List<EcfEstado> dgiiEstados = null;
        GetCompaniesPageParameter page = null;
        GetCompaniesLimitParameter limit = null;
        PaginatedApiResultOfEcfResponse response = api.searchEcfs(rnc, encfs, ids, tiposEcfs, includeEcfContent, fromFechaEmision, toFechaEmision, amountFrom, amountTo, progresses, dgiiEstados, page, limit);
        // TODO: test validations
    }

}
