/**
 * ECF API
 * ECF API (Electronic Fiscal Receipt).
 *
 * The version of the OpenAPI document: v1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.20.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * AnulacionListResponse.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_AnulacionListResponse_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_AnulacionListResponse_H_

#include <boost/optional.hpp>

#include "ecf-dgii-client/ModelBase.h"

#include "ecf-dgii-client/model/RespuestaAnulacionRango.h"
#include <cpprest/details/basic_types.h>
#include "ecf-dgii-client/model/DetalleAnulacionRequestDto.h"
#include <vector>

namespace org {
namespace openapitools {
namespace client {
namespace model {

class DetalleAnulacionRequestDto;
class RespuestaAnulacionRango;


class  AnulacionListResponse
    : public ModelBase
{
public:
    AnulacionListResponse();
    virtual ~AnulacionListResponse();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// AnulacionListResponse members


    utility::string_t getAnulacionId() const;
    bool anulacionIdIsSet() const;
    void unsetAnulacionId();
    void setAnulacionId(const utility::string_t& value);

    utility::string_t getTenantId() const;
    bool tenantIdIsSet() const;
    void unsetTenantId();
    void setTenantId(const utility::string_t& value);

    utility::string_t getCompanyRnc() const;
    bool companyRncIsSet() const;
    void unsetCompanyRnc();
    void setCompanyRnc(const utility::string_t& value);

    int32_t getCantidadeNCFAnulados() const;
    bool cantidadeNCFAnuladosIsSet() const;
    void unsetCantidadeNCFAnulados();
    void setCantidadeNCFAnulados(int32_t value);

    std::vector<std::shared_ptr<DetalleAnulacionRequestDto>> getDetalleAnulacion() const;
    bool detalleAnulacionIsSet() const;
    void unsetDetalleAnulacion();
    void setDetalleAnulacion(const std::vector<std::shared_ptr<DetalleAnulacionRequestDto>>& value);

    std::shared_ptr<RespuestaAnulacionRango> getResponse() const;
    bool responseIsSet() const;
    void unsetResponse();
    void setResponse(const std::shared_ptr<RespuestaAnulacionRango>& value);

    int32_t getStatusCode() const;
    bool statusCodeIsSet() const;
    void unsetStatusCode();
    void setStatusCode(int32_t value);

    utility::string_t getFileName() const;
    bool fileNameIsSet() const;
    void unsetFileName();
    void setFileName(const utility::string_t& value);

    utility::datetime getFechaHoraAnulacioneNCF() const;
    bool fechaHoraAnulacioneNCFIsSet() const;
    void unsetFechaHoraAnulacioneNCF();
    void setFechaHoraAnulacioneNCF(const utility::datetime& value);

    utility::datetime getCreatedOn() const;
    bool createdOnIsSet() const;
    void unsetCreatedOn();
    void setCreatedOn(const utility::datetime& value);

    utility::datetime getUpdatedOn() const;
    bool updatedOnIsSet() const;
    void unsetUpdatedOn();
    void setUpdatedOn(const utility::datetime& value);

    utility::string_t getCreatedBy() const;
    bool createdByIsSet() const;
    void unsetCreatedBy();
    void setCreatedBy(const utility::string_t& value);

    utility::string_t getUpdatedBy() const;
    bool updatedByIsSet() const;
    void unsetUpdatedBy();
    void setUpdatedBy(const utility::string_t& value);


protected:
    utility::string_t m_AnulacionId;
    bool m_AnulacionIdIsSet;

    utility::string_t m_TenantId;
    bool m_TenantIdIsSet;

    utility::string_t m_CompanyRnc;
    bool m_CompanyRncIsSet;

    int32_t m_CantidadeNCFAnulados;
    bool m_CantidadeNCFAnuladosIsSet;

    boost::optional<std::vector<std::shared_ptr<DetalleAnulacionRequestDto>>> m_DetalleAnulacion;

    boost::optional<std::shared_ptr<RespuestaAnulacionRango>> m_Response;

    int32_t m_StatusCode;
    bool m_StatusCodeIsSet;

    utility::string_t m_FileName;
    bool m_FileNameIsSet;

    utility::datetime m_FechaHoraAnulacioneNCF;
    bool m_FechaHoraAnulacioneNCFIsSet;

    utility::datetime m_CreatedOn;
    bool m_CreatedOnIsSet;

    utility::datetime m_UpdatedOn;
    bool m_UpdatedOnIsSet;

    utility::string_t m_CreatedBy;
    bool m_CreatedByIsSet;

    utility::string_t m_UpdatedBy;
    bool m_UpdatedByIsSet;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_AnulacionListResponse_H_ */
