/**
 * ECF API
 * ECF API (Electronic Fiscal Receipt).
 *
 * The version of the OpenAPI document: v1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.14.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * AnulacionRequest.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_AnulacionRequest_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_AnulacionRequest_H_


#include "ecf-dgii-client/ModelBase.h"

#include "ecf-dgii-client/model/DetalleAnulacionRequest.h"
#include "ecf-dgii-client/model/SearchEcfReceptionRequests_TiposEcfs_parameter_inner.h"
#include <vector>

namespace org {
namespace openapitools {
namespace client {
namespace model {

class DetalleAnulacionRequest;


class  AnulacionRequest
    : public ModelBase
{
public:
    AnulacionRequest();
    virtual ~AnulacionRequest();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// AnulacionRequest members


    std::shared_ptr<SearchEcfReceptionRequests_TiposEcfs_parameter_inner> getCantidaDeNcfAnulados() const;
    bool cantidaDeNcfAnuladosIsSet() const;
    void unsetCantidaDeNcfAnulados();
    void setCantidaDeNcfAnulados(const std::shared_ptr<SearchEcfReceptionRequests_TiposEcfs_parameter_inner>& value);

    std::vector<std::shared_ptr<DetalleAnulacionRequest>> getDetalleAnulacion() const;
    bool detalleAnulacionIsSet() const;
    void unsetDetalleAnulacion();
    void setDetalleAnulacion(const std::vector<std::shared_ptr<DetalleAnulacionRequest>>& value);


protected:
    std::shared_ptr<SearchEcfReceptionRequests_TiposEcfs_parameter_inner> m_CantidaDeNcfAnulados;
    bool m_CantidaDeNcfAnuladosIsSet;

    std::vector<std::shared_ptr<DetalleAnulacionRequest>> m_DetalleAnulacion;
    bool m_DetalleAnulacionIsSet;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_AnulacionRequest_H_ */
