/**
 * ECF API
 * ECF API (Electronic Fiscal Receipt).
 *
 * The version of the OpenAPI document: v1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.20.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * Ecf34TipoPagoType.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_Ecf34TipoPagoType_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_Ecf34TipoPagoType_H_

#include <boost/optional.hpp>

#include "ecf-dgii-client/ModelBase.h"


namespace org {
namespace openapitools {
namespace client {
namespace model {


class  Ecf34TipoPagoType
    : public ModelBase
{
public:
    Ecf34TipoPagoType();
    Ecf34TipoPagoType(utility::string_t str);
    operator utility::string_t() const {
        return enumToStrMap.at(getValue());
    }


    virtual ~Ecf34TipoPagoType();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    enum class eEcf34TipoPagoType
    {
        CONTADO,
        CREDITO,
        GRATUITO,
    };

    eEcf34TipoPagoType getValue() const;
    void setValue(eEcf34TipoPagoType const value);

    protected:
        eEcf34TipoPagoType m_value;
        std::map<eEcf34TipoPagoType,utility::string_t> enumToStrMap = {
        { eEcf34TipoPagoType::CONTADO, _XPLATSTR("CONTADO") },
        { eEcf34TipoPagoType::CREDITO, _XPLATSTR("CREDITO") },
        { eEcf34TipoPagoType::GRATUITO, _XPLATSTR("GRATUITO") }
};
        std::map<utility::string_t,eEcf34TipoPagoType> strToEnumMap = {
        { _XPLATSTR("CONTADO"), eEcf34TipoPagoType::CONTADO },
        { _XPLATSTR("CREDITO"), eEcf34TipoPagoType::CREDITO },
        { _XPLATSTR("GRATUITO"), eEcf34TipoPagoType::GRATUITO }
};

};

}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_Ecf34TipoPagoType_H_ */
