/**
 * ECF API
 * ECF API (Electronic Fiscal Receipt).
 *
 * The version of the OpenAPI document: v1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.20.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * Ecf33InformacionReferencia.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_Ecf33InformacionReferencia_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_Ecf33InformacionReferencia_H_

#include <stdexcept>
#include <boost/optional.hpp>

#include "ecf-dgii-client/ModelBase.h"

#include <cpprest/details/basic_types.h>
#include "ecf-dgii-client/model/Ecf33CodigoModificacionType.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {



class  Ecf33InformacionReferencia
    : public ModelBase
{
public:
    Ecf33InformacionReferencia();
    virtual ~Ecf33InformacionReferencia();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// Ecf33InformacionReferencia members


    utility::string_t getNcfModificado() const;
    bool ncfModificadoIsSet() const;
    void unsetNcfModificado();
    void setNcfModificado(const utility::string_t& value);

    utility::string_t getRncOtroContribuyente() const;
    bool rncOtroContribuyenteIsSet() const;
    void unsetRncOtroContribuyente();
    void setRncOtroContribuyente(const utility::string_t& value);

    utility::datetime getFechaNCFModificado() const;
    bool fechaNCFModificadoIsSet() const;
    void unsetFechaNCFModificado();
    void setFechaNCFModificado(const utility::datetime& value);

    std::shared_ptr<Ecf33CodigoModificacionType> getCodigoModificacion() const;
    bool codigoModificacionIsSet() const;
    void unsetCodigoModificacion();
    void setCodigoModificacion(const std::shared_ptr<Ecf33CodigoModificacionType>& value);

    utility::string_t getRazonModificacion() const;
    bool razonModificacionIsSet() const;
    void unsetRazonModificacion();
    void setRazonModificacion(const utility::string_t& value);


protected:
    utility::string_t m_NcfModificado;
    bool m_NcfModificadoIsSet;

    boost::optional<utility::string_t> m_RncOtroContribuyente;

    utility::datetime m_FechaNCFModificado;
    bool m_FechaNCFModificadoIsSet;

    std::shared_ptr<Ecf33CodigoModificacionType> m_CodigoModificacion;
    bool m_CodigoModificacionIsSet;

    boost::optional<utility::string_t> m_RazonModificacion;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_Ecf33InformacionReferencia_H_ */
