/**
 * ECF API
 * ECF API (Electronic Fiscal Receipt).
 *
 * The version of the OpenAPI document: v1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.20.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * Ecf34ImpuestoAdicional2.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_Ecf34ImpuestoAdicional2_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_Ecf34ImpuestoAdicional2_H_

#include <stdexcept>
#include <boost/optional.hpp>

#include "ecf-dgii-client/ModelBase.h"

#include "ecf-dgii-client/model/CodificacionTipoImpuestosType.h"
#include "ecf-dgii-client/model/Ecf31DescuentoORecargo_valorDescuentooRecargo.h"
#include "ecf-dgii-client/model/Ecf31ImpuestoAdicional2_montoImpuestoSelectivoConsumoEspecifico.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {



class  Ecf34ImpuestoAdicional2
    : public ModelBase
{
public:
    Ecf34ImpuestoAdicional2();
    virtual ~Ecf34ImpuestoAdicional2();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// Ecf34ImpuestoAdicional2 members


    std::shared_ptr<CodificacionTipoImpuestosType> getTipoImpuesto() const;
    bool tipoImpuestoIsSet() const;
    void unsetTipoImpuesto();
    void setTipoImpuesto(const std::shared_ptr<CodificacionTipoImpuestosType>& value);

    std::shared_ptr<Ecf31DescuentoORecargo_valorDescuentooRecargo> getTasaImpuestoAdicional() const;
    bool tasaImpuestoAdicionalIsSet() const;
    void unsetTasaImpuestoAdicional();
    void setTasaImpuestoAdicional(const std::shared_ptr<Ecf31DescuentoORecargo_valorDescuentooRecargo>& value);

    std::shared_ptr<Ecf31ImpuestoAdicional2_montoImpuestoSelectivoConsumoEspecifico> getMontoImpuestoSelectivoConsumoEspecifico() const;
    bool montoImpuestoSelectivoConsumoEspecificoIsSet() const;
    void unsetMontoImpuestoSelectivoConsumoEspecifico();
    void setMontoImpuestoSelectivoConsumoEspecifico(const std::shared_ptr<Ecf31ImpuestoAdicional2_montoImpuestoSelectivoConsumoEspecifico>& value);

    std::shared_ptr<Ecf31ImpuestoAdicional2_montoImpuestoSelectivoConsumoEspecifico> getMontoImpuestoSelectivoConsumoAdvalorem() const;
    bool montoImpuestoSelectivoConsumoAdvaloremIsSet() const;
    void unsetMontoImpuestoSelectivoConsumoAdvalorem();
    void setMontoImpuestoSelectivoConsumoAdvalorem(const std::shared_ptr<Ecf31ImpuestoAdicional2_montoImpuestoSelectivoConsumoEspecifico>& value);

    std::shared_ptr<Ecf31ImpuestoAdicional2_montoImpuestoSelectivoConsumoEspecifico> getOtrosImpuestosAdicionales() const;
    bool otrosImpuestosAdicionalesIsSet() const;
    void unsetOtrosImpuestosAdicionales();
    void setOtrosImpuestosAdicionales(const std::shared_ptr<Ecf31ImpuestoAdicional2_montoImpuestoSelectivoConsumoEspecifico>& value);


protected:
    boost::optional<std::shared_ptr<CodificacionTipoImpuestosType>> m_TipoImpuesto;

    boost::optional<std::shared_ptr<Ecf31DescuentoORecargo_valorDescuentooRecargo>> m_TasaImpuestoAdicional;

    boost::optional<std::shared_ptr<Ecf31ImpuestoAdicional2_montoImpuestoSelectivoConsumoEspecifico>> m_MontoImpuestoSelectivoConsumoEspecifico;

    boost::optional<std::shared_ptr<Ecf31ImpuestoAdicional2_montoImpuestoSelectivoConsumoEspecifico>> m_MontoImpuestoSelectivoConsumoAdvalorem;

    boost::optional<std::shared_ptr<Ecf31ImpuestoAdicional2_montoImpuestoSelectivoConsumoEspecifico>> m_OtrosImpuestosAdicionales;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_Ecf34ImpuestoAdicional2_H_ */
