/**
 * ECF API
 * ECF API (Electronic Fiscal Receipt).
 *
 * The version of the OpenAPI document: v1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.20.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * Ecf45CodificacionTipoImpuestosType.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_Ecf45CodificacionTipoImpuestosType_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_Ecf45CodificacionTipoImpuestosType_H_

#include <boost/optional.hpp>

#include "ecf-dgii-client/ModelBase.h"


namespace org {
namespace openapitools {
namespace client {
namespace model {


class  Ecf45CodificacionTipoImpuestosType
    : public ModelBase
{
public:
    Ecf45CodificacionTipoImpuestosType();
    Ecf45CodificacionTipoImpuestosType(utility::string_t str);
    operator utility::string_t() const {
        return enumToStrMap.at(getValue());
    }


    virtual ~Ecf45CodificacionTipoImpuestosType();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    enum class eEcf45CodificacionTipoImpuestosType
    {
        _001,
        _002,
        _003,
        _004,
        _005,
        _006,
        _007,
        _008,
        _009,
        _010,
        _011,
        _012,
        _013,
        _014,
        _015,
        _016,
        _017,
        _018,
        _019,
        _020,
        _021,
        _022,
        _023,
        _024,
        _025,
        _026,
        _027,
        _028,
        _029,
        _030,
        _031,
        _032,
        _033,
        _034,
        _035,
        _036,
        _037,
        _038,
        _039,
    };

    eEcf45CodificacionTipoImpuestosType getValue() const;
    void setValue(eEcf45CodificacionTipoImpuestosType const value);

    protected:
        eEcf45CodificacionTipoImpuestosType m_value;
        std::map<eEcf45CodificacionTipoImpuestosType,utility::string_t> enumToStrMap = {
        { eEcf45CodificacionTipoImpuestosType::_001, _XPLATSTR("_001") },
        { eEcf45CodificacionTipoImpuestosType::_002, _XPLATSTR("_002") },
        { eEcf45CodificacionTipoImpuestosType::_003, _XPLATSTR("_003") },
        { eEcf45CodificacionTipoImpuestosType::_004, _XPLATSTR("_004") },
        { eEcf45CodificacionTipoImpuestosType::_005, _XPLATSTR("_005") },
        { eEcf45CodificacionTipoImpuestosType::_006, _XPLATSTR("_006") },
        { eEcf45CodificacionTipoImpuestosType::_007, _XPLATSTR("_007") },
        { eEcf45CodificacionTipoImpuestosType::_008, _XPLATSTR("_008") },
        { eEcf45CodificacionTipoImpuestosType::_009, _XPLATSTR("_009") },
        { eEcf45CodificacionTipoImpuestosType::_010, _XPLATSTR("_010") },
        { eEcf45CodificacionTipoImpuestosType::_011, _XPLATSTR("_011") },
        { eEcf45CodificacionTipoImpuestosType::_012, _XPLATSTR("_012") },
        { eEcf45CodificacionTipoImpuestosType::_013, _XPLATSTR("_013") },
        { eEcf45CodificacionTipoImpuestosType::_014, _XPLATSTR("_014") },
        { eEcf45CodificacionTipoImpuestosType::_015, _XPLATSTR("_015") },
        { eEcf45CodificacionTipoImpuestosType::_016, _XPLATSTR("_016") },
        { eEcf45CodificacionTipoImpuestosType::_017, _XPLATSTR("_017") },
        { eEcf45CodificacionTipoImpuestosType::_018, _XPLATSTR("_018") },
        { eEcf45CodificacionTipoImpuestosType::_019, _XPLATSTR("_019") },
        { eEcf45CodificacionTipoImpuestosType::_020, _XPLATSTR("_020") },
        { eEcf45CodificacionTipoImpuestosType::_021, _XPLATSTR("_021") },
        { eEcf45CodificacionTipoImpuestosType::_022, _XPLATSTR("_022") },
        { eEcf45CodificacionTipoImpuestosType::_023, _XPLATSTR("_023") },
        { eEcf45CodificacionTipoImpuestosType::_024, _XPLATSTR("_024") },
        { eEcf45CodificacionTipoImpuestosType::_025, _XPLATSTR("_025") },
        { eEcf45CodificacionTipoImpuestosType::_026, _XPLATSTR("_026") },
        { eEcf45CodificacionTipoImpuestosType::_027, _XPLATSTR("_027") },
        { eEcf45CodificacionTipoImpuestosType::_028, _XPLATSTR("_028") },
        { eEcf45CodificacionTipoImpuestosType::_029, _XPLATSTR("_029") },
        { eEcf45CodificacionTipoImpuestosType::_030, _XPLATSTR("_030") },
        { eEcf45CodificacionTipoImpuestosType::_031, _XPLATSTR("_031") },
        { eEcf45CodificacionTipoImpuestosType::_032, _XPLATSTR("_032") },
        { eEcf45CodificacionTipoImpuestosType::_033, _XPLATSTR("_033") },
        { eEcf45CodificacionTipoImpuestosType::_034, _XPLATSTR("_034") },
        { eEcf45CodificacionTipoImpuestosType::_035, _XPLATSTR("_035") },
        { eEcf45CodificacionTipoImpuestosType::_036, _XPLATSTR("_036") },
        { eEcf45CodificacionTipoImpuestosType::_037, _XPLATSTR("_037") },
        { eEcf45CodificacionTipoImpuestosType::_038, _XPLATSTR("_038") },
        { eEcf45CodificacionTipoImpuestosType::_039, _XPLATSTR("_039") }
};
        std::map<utility::string_t,eEcf45CodificacionTipoImpuestosType> strToEnumMap = {
        { _XPLATSTR("_001"), eEcf45CodificacionTipoImpuestosType::_001 },
        { _XPLATSTR("_002"), eEcf45CodificacionTipoImpuestosType::_002 },
        { _XPLATSTR("_003"), eEcf45CodificacionTipoImpuestosType::_003 },
        { _XPLATSTR("_004"), eEcf45CodificacionTipoImpuestosType::_004 },
        { _XPLATSTR("_005"), eEcf45CodificacionTipoImpuestosType::_005 },
        { _XPLATSTR("_006"), eEcf45CodificacionTipoImpuestosType::_006 },
        { _XPLATSTR("_007"), eEcf45CodificacionTipoImpuestosType::_007 },
        { _XPLATSTR("_008"), eEcf45CodificacionTipoImpuestosType::_008 },
        { _XPLATSTR("_009"), eEcf45CodificacionTipoImpuestosType::_009 },
        { _XPLATSTR("_010"), eEcf45CodificacionTipoImpuestosType::_010 },
        { _XPLATSTR("_011"), eEcf45CodificacionTipoImpuestosType::_011 },
        { _XPLATSTR("_012"), eEcf45CodificacionTipoImpuestosType::_012 },
        { _XPLATSTR("_013"), eEcf45CodificacionTipoImpuestosType::_013 },
        { _XPLATSTR("_014"), eEcf45CodificacionTipoImpuestosType::_014 },
        { _XPLATSTR("_015"), eEcf45CodificacionTipoImpuestosType::_015 },
        { _XPLATSTR("_016"), eEcf45CodificacionTipoImpuestosType::_016 },
        { _XPLATSTR("_017"), eEcf45CodificacionTipoImpuestosType::_017 },
        { _XPLATSTR("_018"), eEcf45CodificacionTipoImpuestosType::_018 },
        { _XPLATSTR("_019"), eEcf45CodificacionTipoImpuestosType::_019 },
        { _XPLATSTR("_020"), eEcf45CodificacionTipoImpuestosType::_020 },
        { _XPLATSTR("_021"), eEcf45CodificacionTipoImpuestosType::_021 },
        { _XPLATSTR("_022"), eEcf45CodificacionTipoImpuestosType::_022 },
        { _XPLATSTR("_023"), eEcf45CodificacionTipoImpuestosType::_023 },
        { _XPLATSTR("_024"), eEcf45CodificacionTipoImpuestosType::_024 },
        { _XPLATSTR("_025"), eEcf45CodificacionTipoImpuestosType::_025 },
        { _XPLATSTR("_026"), eEcf45CodificacionTipoImpuestosType::_026 },
        { _XPLATSTR("_027"), eEcf45CodificacionTipoImpuestosType::_027 },
        { _XPLATSTR("_028"), eEcf45CodificacionTipoImpuestosType::_028 },
        { _XPLATSTR("_029"), eEcf45CodificacionTipoImpuestosType::_029 },
        { _XPLATSTR("_030"), eEcf45CodificacionTipoImpuestosType::_030 },
        { _XPLATSTR("_031"), eEcf45CodificacionTipoImpuestosType::_031 },
        { _XPLATSTR("_032"), eEcf45CodificacionTipoImpuestosType::_032 },
        { _XPLATSTR("_033"), eEcf45CodificacionTipoImpuestosType::_033 },
        { _XPLATSTR("_034"), eEcf45CodificacionTipoImpuestosType::_034 },
        { _XPLATSTR("_035"), eEcf45CodificacionTipoImpuestosType::_035 },
        { _XPLATSTR("_036"), eEcf45CodificacionTipoImpuestosType::_036 },
        { _XPLATSTR("_037"), eEcf45CodificacionTipoImpuestosType::_037 },
        { _XPLATSTR("_038"), eEcf45CodificacionTipoImpuestosType::_038 },
        { _XPLATSTR("_039"), eEcf45CodificacionTipoImpuestosType::_039 }
};

};

}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_Ecf45CodificacionTipoImpuestosType_H_ */
