/**
 * ECF API
 * ECF API (Electronic Fiscal Receipt).
 *
 * The version of the OpenAPI document: v1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.20.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * Ecf45DescuentoORecargo.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_Ecf45DescuentoORecargo_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_Ecf45DescuentoORecargo_H_

#include <stdexcept>
#include <boost/optional.hpp>

#include "ecf-dgii-client/ModelBase.h"

#include "ecf-dgii-client/model/Ecf45TipoAjusteType.h"
#include "ecf-dgii-client/model/Ecf31DescuentoORecargo_montoDescuentooRecargo.h"
#include "ecf-dgii-client/model/IndicadorNorma1007Type.h"
#include "ecf-dgii-client/model/AcecfReceptionRequestDto_progress.h"
#include "ecf-dgii-client/model/IndicadorFacturacionDRType.h"
#include <cpprest/details/basic_types.h>
#include "ecf-dgii-client/model/Ecf31DescuentoORecargo_valorDescuentooRecargo.h"
#include "ecf-dgii-client/model/TipoDescuentoRecargoType.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {



class  Ecf45DescuentoORecargo
    : public ModelBase
{
public:
    Ecf45DescuentoORecargo();
    virtual ~Ecf45DescuentoORecargo();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// Ecf45DescuentoORecargo members


    std::shared_ptr<AcecfReceptionRequestDto_progress> getNumeroLinea() const;
    bool numeroLineaIsSet() const;
    void unsetNumeroLinea();
    void setNumeroLinea(const std::shared_ptr<AcecfReceptionRequestDto_progress>& value);

    std::shared_ptr<Ecf45TipoAjusteType> getTipoAjuste() const;
    bool tipoAjusteIsSet() const;
    void unsetTipoAjuste();
    void setTipoAjuste(const std::shared_ptr<Ecf45TipoAjusteType>& value);

    std::shared_ptr<IndicadorNorma1007Type> getIndicadorNorma1007() const;
    bool indicadorNorma1007IsSet() const;
    void unsetIndicadorNorma1007();
    void setIndicadorNorma1007(const std::shared_ptr<IndicadorNorma1007Type>& value);

    utility::string_t getDescripcionDescuentooRecargo() const;
    bool descripcionDescuentooRecargoIsSet() const;
    void unsetDescripcionDescuentooRecargo();
    void setDescripcionDescuentooRecargo(const utility::string_t& value);

    std::shared_ptr<TipoDescuentoRecargoType> getTipoValor() const;
    bool tipoValorIsSet() const;
    void unsetTipoValor();
    void setTipoValor(const std::shared_ptr<TipoDescuentoRecargoType>& value);

    std::shared_ptr<Ecf31DescuentoORecargo_valorDescuentooRecargo> getValorDescuentooRecargo() const;
    bool valorDescuentooRecargoIsSet() const;
    void unsetValorDescuentooRecargo();
    void setValorDescuentooRecargo(const std::shared_ptr<Ecf31DescuentoORecargo_valorDescuentooRecargo>& value);

    std::shared_ptr<Ecf31DescuentoORecargo_montoDescuentooRecargo> getMontoDescuentooRecargo() const;
    bool montoDescuentooRecargoIsSet() const;
    void unsetMontoDescuentooRecargo();
    void setMontoDescuentooRecargo(const std::shared_ptr<Ecf31DescuentoORecargo_montoDescuentooRecargo>& value);

    std::shared_ptr<Ecf31DescuentoORecargo_montoDescuentooRecargo> getMontoDescuentooRecargoOtraMoneda() const;
    bool montoDescuentooRecargoOtraMonedaIsSet() const;
    void unsetMontoDescuentooRecargoOtraMoneda();
    void setMontoDescuentooRecargoOtraMoneda(const std::shared_ptr<Ecf31DescuentoORecargo_montoDescuentooRecargo>& value);

    std::shared_ptr<IndicadorFacturacionDRType> getIndicadorFacturacionDescuentooRecargo() const;
    bool indicadorFacturacionDescuentooRecargoIsSet() const;
    void unsetIndicadorFacturacionDescuentooRecargo();
    void setIndicadorFacturacionDescuentooRecargo(const std::shared_ptr<IndicadorFacturacionDRType>& value);


protected:
    std::shared_ptr<AcecfReceptionRequestDto_progress> m_NumeroLinea;
    bool m_NumeroLineaIsSet;

    std::shared_ptr<Ecf45TipoAjusteType> m_TipoAjuste;
    bool m_TipoAjusteIsSet;

    boost::optional<std::shared_ptr<IndicadorNorma1007Type>> m_IndicadorNorma1007;

    boost::optional<utility::string_t> m_DescripcionDescuentooRecargo;

    boost::optional<std::shared_ptr<TipoDescuentoRecargoType>> m_TipoValor;

    boost::optional<std::shared_ptr<Ecf31DescuentoORecargo_valorDescuentooRecargo>> m_ValorDescuentooRecargo;

    boost::optional<std::shared_ptr<Ecf31DescuentoORecargo_montoDescuentooRecargo>> m_MontoDescuentooRecargo;

    boost::optional<std::shared_ptr<Ecf31DescuentoORecargo_montoDescuentooRecargo>> m_MontoDescuentooRecargoOtraMoneda;

    boost::optional<std::shared_ptr<IndicadorFacturacionDRType>> m_IndicadorFacturacionDescuentooRecargo;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_Ecf45DescuentoORecargo_H_ */
