/**
 * ECF API
 * ECF API (Electronic Fiscal Receipt).
 *
 * The version of the OpenAPI document: v1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.20.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * Ecf41Item.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_Ecf41Item_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_Ecf41Item_H_

#include <stdexcept>
#include <boost/optional.hpp>

#include "ecf-dgii-client/ModelBase.h"

#include "ecf-dgii-client/model/Ecf31FormaDePago_montoPago.h"
#include "ecf-dgii-client/model/Ecf41IndicadorBienoServicioType.h"
#include "ecf-dgii-client/model/Ecf41SubRecargo.h"
#include "ecf-dgii-client/model/Ecf31DescuentoORecargo_montoDescuentooRecargo.h"
#include "ecf-dgii-client/model/Ecf31Item_cantidadItem.h"
#include "ecf-dgii-client/model/Ecf31Item_precioUnitarioItem.h"
#include "ecf-dgii-client/model/Ecf41Retencion.h"
#include <vector>
#include "ecf-dgii-client/model/Ecf41OtraMonedaDetalle.h"
#include "ecf-dgii-client/model/Ecf41IndicadorFacturacionType.h"
#include "ecf-dgii-client/model/Ecf41CodigosItem.h"
#include "ecf-dgii-client/model/AcecfReceptionRequestDto_progress.h"
#include <cpprest/details/basic_types.h>
#include "ecf-dgii-client/model/Ecf41SubDescuento.h"
#include "ecf-dgii-client/model/UnidadMedidaType.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

class Ecf41CodigosItem;
class Ecf41Retencion;
class Ecf41SubDescuento;
class Ecf41SubRecargo;
class Ecf41OtraMonedaDetalle;


class  Ecf41Item
    : public ModelBase
{
public:
    Ecf41Item();
    virtual ~Ecf41Item();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// Ecf41Item members


    std::shared_ptr<AcecfReceptionRequestDto_progress> getNumeroLinea() const;
    bool numeroLineaIsSet() const;
    void unsetNumeroLinea();
    void setNumeroLinea(const std::shared_ptr<AcecfReceptionRequestDto_progress>& value);

    std::vector<std::shared_ptr<Ecf41CodigosItem>> getTablaCodigosItem() const;
    bool tablaCodigosItemIsSet() const;
    void unsetTablaCodigosItem();
    void setTablaCodigosItem(const std::vector<std::shared_ptr<Ecf41CodigosItem>>& value);

    std::shared_ptr<Ecf41IndicadorFacturacionType> getIndicadorFacturacion() const;
    bool indicadorFacturacionIsSet() const;
    void unsetIndicadorFacturacion();
    void setIndicadorFacturacion(const std::shared_ptr<Ecf41IndicadorFacturacionType>& value);

    std::shared_ptr<Ecf41Retencion> getRetencion() const;
    bool retencionIsSet() const;
    void unsetRetencion();
    void setRetencion(const std::shared_ptr<Ecf41Retencion>& value);

    utility::string_t getNombreItem() const;
    bool nombreItemIsSet() const;
    void unsetNombreItem();
    void setNombreItem(const utility::string_t& value);

    std::shared_ptr<Ecf41IndicadorBienoServicioType> getIndicadorBienoServicio() const;
    bool indicadorBienoServicioIsSet() const;
    void unsetIndicadorBienoServicio();
    void setIndicadorBienoServicio(const std::shared_ptr<Ecf41IndicadorBienoServicioType>& value);

    utility::string_t getDescripcionItem() const;
    bool descripcionItemIsSet() const;
    void unsetDescripcionItem();
    void setDescripcionItem(const utility::string_t& value);

    std::shared_ptr<Ecf31Item_cantidadItem> getCantidadItem() const;
    bool cantidadItemIsSet() const;
    void unsetCantidadItem();
    void setCantidadItem(const std::shared_ptr<Ecf31Item_cantidadItem>& value);

    std::shared_ptr<UnidadMedidaType> getUnidadMedida() const;
    bool unidadMedidaIsSet() const;
    void unsetUnidadMedida();
    void setUnidadMedida(const std::shared_ptr<UnidadMedidaType>& value);

    utility::datetime getFechaElaboracion() const;
    bool fechaElaboracionIsSet() const;
    void unsetFechaElaboracion();
    void setFechaElaboracion(const utility::datetime& value);

    utility::datetime getFechaVencimientoItem() const;
    bool fechaVencimientoItemIsSet() const;
    void unsetFechaVencimientoItem();
    void setFechaVencimientoItem(const utility::datetime& value);

    std::shared_ptr<Ecf31Item_precioUnitarioItem> getPrecioUnitarioItem() const;
    bool precioUnitarioItemIsSet() const;
    void unsetPrecioUnitarioItem();
    void setPrecioUnitarioItem(const std::shared_ptr<Ecf31Item_precioUnitarioItem>& value);

    std::shared_ptr<Ecf31DescuentoORecargo_montoDescuentooRecargo> getDescuentoMonto() const;
    bool descuentoMontoIsSet() const;
    void unsetDescuentoMonto();
    void setDescuentoMonto(const std::shared_ptr<Ecf31DescuentoORecargo_montoDescuentooRecargo>& value);

    std::vector<std::shared_ptr<Ecf41SubDescuento>> getTablaSubDescuento() const;
    bool tablaSubDescuentoIsSet() const;
    void unsetTablaSubDescuento();
    void setTablaSubDescuento(const std::vector<std::shared_ptr<Ecf41SubDescuento>>& value);

    std::shared_ptr<Ecf31DescuentoORecargo_montoDescuentooRecargo> getRecargoMonto() const;
    bool recargoMontoIsSet() const;
    void unsetRecargoMonto();
    void setRecargoMonto(const std::shared_ptr<Ecf31DescuentoORecargo_montoDescuentooRecargo>& value);

    std::vector<std::shared_ptr<Ecf41SubRecargo>> getTablaSubRecargo() const;
    bool tablaSubRecargoIsSet() const;
    void unsetTablaSubRecargo();
    void setTablaSubRecargo(const std::vector<std::shared_ptr<Ecf41SubRecargo>>& value);

    std::shared_ptr<Ecf41OtraMonedaDetalle> getOtraMonedaDetalle() const;
    bool otraMonedaDetalleIsSet() const;
    void unsetOtraMonedaDetalle();
    void setOtraMonedaDetalle(const std::shared_ptr<Ecf41OtraMonedaDetalle>& value);

    std::shared_ptr<Ecf31FormaDePago_montoPago> getMontoItem() const;
    bool montoItemIsSet() const;
    void unsetMontoItem();
    void setMontoItem(const std::shared_ptr<Ecf31FormaDePago_montoPago>& value);


protected:
    std::shared_ptr<AcecfReceptionRequestDto_progress> m_NumeroLinea;
    bool m_NumeroLineaIsSet;

    boost::optional<std::vector<std::shared_ptr<Ecf41CodigosItem>>> m_TablaCodigosItem;

    std::shared_ptr<Ecf41IndicadorFacturacionType> m_IndicadorFacturacion;
    bool m_IndicadorFacturacionIsSet;

    std::shared_ptr<Ecf41Retencion> m_Retencion;
    bool m_RetencionIsSet;

    utility::string_t m_NombreItem;
    bool m_NombreItemIsSet;

    std::shared_ptr<Ecf41IndicadorBienoServicioType> m_IndicadorBienoServicio;
    bool m_IndicadorBienoServicioIsSet;

    boost::optional<utility::string_t> m_DescripcionItem;

    std::shared_ptr<Ecf31Item_cantidadItem> m_CantidadItem;
    bool m_CantidadItemIsSet;

    boost::optional<std::shared_ptr<UnidadMedidaType>> m_UnidadMedida;

    boost::optional<utility::datetime> m_FechaElaboracion;

    boost::optional<utility::datetime> m_FechaVencimientoItem;

    std::shared_ptr<Ecf31Item_precioUnitarioItem> m_PrecioUnitarioItem;
    bool m_PrecioUnitarioItemIsSet;

    boost::optional<std::shared_ptr<Ecf31DescuentoORecargo_montoDescuentooRecargo>> m_DescuentoMonto;

    boost::optional<std::vector<std::shared_ptr<Ecf41SubDescuento>>> m_TablaSubDescuento;

    boost::optional<std::shared_ptr<Ecf31DescuentoORecargo_montoDescuentooRecargo>> m_RecargoMonto;

    boost::optional<std::vector<std::shared_ptr<Ecf41SubRecargo>>> m_TablaSubRecargo;

    boost::optional<std::shared_ptr<Ecf41OtraMonedaDetalle>> m_OtraMonedaDetalle;

    std::shared_ptr<Ecf31FormaDePago_montoPago> m_MontoItem;
    bool m_MontoItemIsSet;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_Ecf41Item_H_ */
