/**
 * ECF API
 * ECF API (Electronic Fiscal Receipt).
 *
 * The version of the OpenAPI document: v1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.20.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * Ecf44TipoAjusteType.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_Ecf44TipoAjusteType_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_Ecf44TipoAjusteType_H_

#include <boost/optional.hpp>

#include "ecf-dgii-client/ModelBase.h"


namespace org {
namespace openapitools {
namespace client {
namespace model {


class  Ecf44TipoAjusteType
    : public ModelBase
{
public:
    Ecf44TipoAjusteType();
    Ecf44TipoAjusteType(utility::string_t str);
    operator utility::string_t() const {
        return enumToStrMap.at(getValue());
    }


    virtual ~Ecf44TipoAjusteType();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    enum class eEcf44TipoAjusteType
    {
        D,
        R,
    };

    eEcf44TipoAjusteType getValue() const;
    void setValue(eEcf44TipoAjusteType const value);

    protected:
        eEcf44TipoAjusteType m_value;
        std::map<eEcf44TipoAjusteType,utility::string_t> enumToStrMap = {
        { eEcf44TipoAjusteType::D, _XPLATSTR("D") },
        { eEcf44TipoAjusteType::R, _XPLATSTR("R") }
};
        std::map<utility::string_t,eEcf44TipoAjusteType> strToEnumMap = {
        { _XPLATSTR("D"), eEcf44TipoAjusteType::D },
        { _XPLATSTR("R"), eEcf44TipoAjusteType::R }
};

};

}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_Ecf44TipoAjusteType_H_ */
