/**
 * ECF API
 * ECF API (Electronic Fiscal Receipt).
 *
 * The version of the OpenAPI document: v1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.20.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * IndicadorFacturacionType.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_IndicadorFacturacionType_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_IndicadorFacturacionType_H_

#include <boost/optional.hpp>

#include "ecf-dgii-client/ModelBase.h"


namespace org {
namespace openapitools {
namespace client {
namespace model {


class  IndicadorFacturacionType
    : public ModelBase
{
public:
    IndicadorFacturacionType();
    IndicadorFacturacionType(utility::string_t str);
    operator utility::string_t() const {
        return enumToStrMap.at(getValue());
    }


    virtual ~IndicadorFacturacionType();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    enum class eIndicadorFacturacionType
    {
        NOFACTURABLE_18PERCENT,
        ITBIS1_18PERCENT,
        ITBIS2_16PERCENT,
        ITBIS3_0PERCENT,
        EXENTO_E,
    };

    eIndicadorFacturacionType getValue() const;
    void setValue(eIndicadorFacturacionType const value);

    protected:
        eIndicadorFacturacionType m_value;
        std::map<eIndicadorFacturacionType,utility::string_t> enumToStrMap = {
        { eIndicadorFacturacionType::NOFACTURABLE_18PERCENT, _XPLATSTR("NoFacturable_18Percent") },
        { eIndicadorFacturacionType::ITBIS1_18PERCENT, _XPLATSTR("ITBIS1_18Percent") },
        { eIndicadorFacturacionType::ITBIS2_16PERCENT, _XPLATSTR("ITBIS2_16Percent") },
        { eIndicadorFacturacionType::ITBIS3_0PERCENT, _XPLATSTR("ITBIS3_0Percent") },
        { eIndicadorFacturacionType::EXENTO_E, _XPLATSTR("Exento_E") }
};
        std::map<utility::string_t,eIndicadorFacturacionType> strToEnumMap = {
        { _XPLATSTR("NoFacturable_18Percent"), eIndicadorFacturacionType::NOFACTURABLE_18PERCENT },
        { _XPLATSTR("ITBIS1_18Percent"), eIndicadorFacturacionType::ITBIS1_18PERCENT },
        { _XPLATSTR("ITBIS2_16Percent"), eIndicadorFacturacionType::ITBIS2_16PERCENT },
        { _XPLATSTR("ITBIS3_0Percent"), eIndicadorFacturacionType::ITBIS3_0PERCENT },
        { _XPLATSTR("Exento_E"), eIndicadorFacturacionType::EXENTO_E }
};

};

}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_IndicadorFacturacionType_H_ */
