/**
 * ECF API
 * ECF API (Electronic Fiscal Receipt).
 *
 * The version of the OpenAPI document: v1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.20.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * InformacionesAdicionales.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_InformacionesAdicionales_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_InformacionesAdicionales_H_

#include <stdexcept>
#include <boost/optional.hpp>

#include "ecf-dgii-client/ModelBase.h"

#include <cpprest/details/basic_types.h>
#include "ecf-dgii-client/model/UnidadMedidaType.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {



class  InformacionesAdicionales
    : public ModelBase
{
public:
    InformacionesAdicionales();
    virtual ~InformacionesAdicionales();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// InformacionesAdicionales members


    utility::datetime getFechaEmbarque() const;
    bool fechaEmbarqueIsSet() const;
    void unsetFechaEmbarque();
    void setFechaEmbarque(const utility::datetime& value);

    utility::string_t getNumeroEmbarque() const;
    bool numeroEmbarqueIsSet() const;
    void unsetNumeroEmbarque();
    void setNumeroEmbarque(const utility::string_t& value);

    utility::string_t getNumeroContenedor() const;
    bool numeroContenedorIsSet() const;
    void unsetNumeroContenedor();
    void setNumeroContenedor(const utility::string_t& value);

    utility::string_t getNumeroReferencia() const;
    bool numeroReferenciaIsSet() const;
    void unsetNumeroReferencia();
    void setNumeroReferencia(const utility::string_t& value);

    utility::string_t getNombrePuertoEmbarque() const;
    bool nombrePuertoEmbarqueIsSet() const;
    void unsetNombrePuertoEmbarque();
    void setNombrePuertoEmbarque(const utility::string_t& value);

    utility::string_t getCondicionesEntrega() const;
    bool condicionesEntregaIsSet() const;
    void unsetCondicionesEntrega();
    void setCondicionesEntrega(const utility::string_t& value);

    double getTotalFob() const;
    bool totalFobIsSet() const;
    void unsetTotalFob();
    void setTotalFob(double value);

    double getSeguro() const;
    bool seguroIsSet() const;
    void unsetSeguro();
    void setSeguro(double value);

    double getFlete() const;
    bool fleteIsSet() const;
    void unsetFlete();
    void setFlete(double value);

    double getOtrosGastos() const;
    bool otrosGastosIsSet() const;
    void unsetOtrosGastos();
    void setOtrosGastos(double value);

    double getTotalCif() const;
    bool totalCifIsSet() const;
    void unsetTotalCif();
    void setTotalCif(double value);

    utility::string_t getRegimenAduanero() const;
    bool regimenAduaneroIsSet() const;
    void unsetRegimenAduanero();
    void setRegimenAduanero(const utility::string_t& value);

    utility::string_t getNombrePuertoSalida() const;
    bool nombrePuertoSalidaIsSet() const;
    void unsetNombrePuertoSalida();
    void setNombrePuertoSalida(const utility::string_t& value);

    utility::string_t getNombrePuertoDesembarque() const;
    bool nombrePuertoDesembarqueIsSet() const;
    void unsetNombrePuertoDesembarque();
    void setNombrePuertoDesembarque(const utility::string_t& value);

    double getPesoBruto() const;
    bool pesoBrutoIsSet() const;
    void unsetPesoBruto();
    void setPesoBruto(double value);

    double getPesoNeto() const;
    bool pesoNetoIsSet() const;
    void unsetPesoNeto();
    void setPesoNeto(double value);

    std::shared_ptr<UnidadMedidaType> getUnidadPesoBruto() const;
    bool unidadPesoBrutoIsSet() const;
    void unsetUnidadPesoBruto();
    void setUnidadPesoBruto(const std::shared_ptr<UnidadMedidaType>& value);

    std::shared_ptr<UnidadMedidaType> getUnidadPesoNeto() const;
    bool unidadPesoNetoIsSet() const;
    void unsetUnidadPesoNeto();
    void setUnidadPesoNeto(const std::shared_ptr<UnidadMedidaType>& value);

    double getCantidadBulto() const;
    bool cantidadBultoIsSet() const;
    void unsetCantidadBulto();
    void setCantidadBulto(double value);

    std::shared_ptr<UnidadMedidaType> getUnidadBulto() const;
    bool unidadBultoIsSet() const;
    void unsetUnidadBulto();
    void setUnidadBulto(const std::shared_ptr<UnidadMedidaType>& value);

    double getVolumenBulto() const;
    bool volumenBultoIsSet() const;
    void unsetVolumenBulto();
    void setVolumenBulto(double value);

    std::shared_ptr<UnidadMedidaType> getUnidadVolumen() const;
    bool unidadVolumenIsSet() const;
    void unsetUnidadVolumen();
    void setUnidadVolumen(const std::shared_ptr<UnidadMedidaType>& value);


protected:
    boost::optional<utility::datetime> m_FechaEmbarque;

    boost::optional<utility::string_t> m_NumeroEmbarque;

    boost::optional<utility::string_t> m_NumeroContenedor;

    boost::optional<utility::string_t> m_NumeroReferencia;

    boost::optional<utility::string_t> m_NombrePuertoEmbarque;

    boost::optional<utility::string_t> m_CondicionesEntrega;

    boost::optional<double> m_TotalFob;

    boost::optional<double> m_Seguro;

    boost::optional<double> m_Flete;

    boost::optional<double> m_OtrosGastos;

    boost::optional<double> m_TotalCif;

    boost::optional<utility::string_t> m_RegimenAduanero;

    boost::optional<utility::string_t> m_NombrePuertoSalida;

    boost::optional<utility::string_t> m_NombrePuertoDesembarque;

    boost::optional<double> m_PesoBruto;

    boost::optional<double> m_PesoNeto;

    boost::optional<std::shared_ptr<UnidadMedidaType>> m_UnidadPesoBruto;

    boost::optional<std::shared_ptr<UnidadMedidaType>> m_UnidadPesoNeto;

    boost::optional<double> m_CantidadBulto;

    boost::optional<std::shared_ptr<UnidadMedidaType>> m_UnidadBulto;

    boost::optional<double> m_VolumenBulto;

    boost::optional<std::shared_ptr<UnidadMedidaType>> m_UnidadVolumen;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_InformacionesAdicionales_H_ */
