/**
 * ECF API
 * ECF API (Electronic Fiscal Receipt).
 *
 * The version of the OpenAPI document: v1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.14.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * PaginatedApiResultOfEcfResponse.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_PaginatedApiResultOfEcfResponse_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_PaginatedApiResultOfEcfResponse_H_


#include "ecf-dgii-client/ModelBase.h"

#include "ecf-dgii-client/model/Ecf31IdDoc_totalPaginas.h"
#include "ecf-dgii-client/model/EcfResponse.h"
#include <cpprest/details/basic_types.h>
#include "ecf-dgii-client/model/SearchEcfReceptionRequests_TiposEcfs_parameter_inner.h"
#include <vector>

namespace org {
namespace openapitools {
namespace client {
namespace model {

class EcfResponse;


class  PaginatedApiResultOfEcfResponse
    : public ModelBase
{
public:
    PaginatedApiResultOfEcfResponse();
    virtual ~PaginatedApiResultOfEcfResponse();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// PaginatedApiResultOfEcfResponse members


    utility::string_t getNextPageUri() const;
    bool nextPageUriIsSet() const;
    void unsetNextPageUri();
    void setNextPageUri(const utility::string_t& value);

    std::vector<std::shared_ptr<EcfResponse>> getValues() const;
    bool valuesIsSet() const;
    void unsetValues();
    void setValues(const std::vector<std::shared_ptr<EcfResponse>>& value);

    std::shared_ptr<SearchEcfReceptionRequests_TiposEcfs_parameter_inner> getTotal() const;
    bool totalIsSet() const;
    void unsetTotal();
    void setTotal(const std::shared_ptr<SearchEcfReceptionRequests_TiposEcfs_parameter_inner>& value);

    std::shared_ptr<SearchEcfReceptionRequests_TiposEcfs_parameter_inner> getPage() const;
    bool pageIsSet() const;
    void unsetPage();
    void setPage(const std::shared_ptr<SearchEcfReceptionRequests_TiposEcfs_parameter_inner>& value);

    std::shared_ptr<SearchEcfReceptionRequests_TiposEcfs_parameter_inner> getLimit() const;
    bool limitIsSet() const;
    void unsetLimit();
    void setLimit(const std::shared_ptr<SearchEcfReceptionRequests_TiposEcfs_parameter_inner>& value);

    std::shared_ptr<Ecf31IdDoc_totalPaginas> getNextPage() const;
    bool nextPageIsSet() const;
    void unsetNextPage();
    void setNextPage(const std::shared_ptr<Ecf31IdDoc_totalPaginas>& value);

    std::shared_ptr<Ecf31IdDoc_totalPaginas> getPreviousPage() const;
    bool previousPageIsSet() const;
    void unsetPreviousPage();
    void setPreviousPage(const std::shared_ptr<Ecf31IdDoc_totalPaginas>& value);


protected:
    utility::string_t m_NextPageUri;
    bool m_NextPageUriIsSet;

    std::vector<std::shared_ptr<EcfResponse>> m_Values;
    bool m_ValuesIsSet;

    std::shared_ptr<SearchEcfReceptionRequests_TiposEcfs_parameter_inner> m_Total;
    bool m_TotalIsSet;

    std::shared_ptr<SearchEcfReceptionRequests_TiposEcfs_parameter_inner> m_Page;
    bool m_PageIsSet;

    std::shared_ptr<SearchEcfReceptionRequests_TiposEcfs_parameter_inner> m_Limit;
    bool m_LimitIsSet;

    std::shared_ptr<Ecf31IdDoc_totalPaginas> m_NextPage;
    bool m_NextPageIsSet;

    std::shared_ptr<Ecf31IdDoc_totalPaginas> m_PreviousPage;
    bool m_PreviousPageIsSet;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_PaginatedApiResultOfEcfResponse_H_ */
