/**
 * ECF API
 * ECF API (Electronic Fiscal Receipt).
 *
 * The version of the OpenAPI document: v1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.20.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * PaginatedApiResultOfEcfReceptionRequestDto.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_PaginatedApiResultOfEcfReceptionRequestDto_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_PaginatedApiResultOfEcfReceptionRequestDto_H_

#include <boost/optional.hpp>

#include "ecf-dgii-client/ModelBase.h"

#include <cpprest/details/basic_types.h>
#include "ecf-dgii-client/model/EcfReceptionRequestDto.h"
#include <vector>

namespace org {
namespace openapitools {
namespace client {
namespace model {

class EcfReceptionRequestDto;


class  PaginatedApiResultOfEcfReceptionRequestDto
    : public ModelBase
{
public:
    PaginatedApiResultOfEcfReceptionRequestDto();
    virtual ~PaginatedApiResultOfEcfReceptionRequestDto();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// PaginatedApiResultOfEcfReceptionRequestDto members


    utility::string_t getNextPageUri() const;
    bool nextPageUriIsSet() const;
    void unsetNextPageUri();
    void setNextPageUri(const utility::string_t& value);

    std::vector<std::shared_ptr<EcfReceptionRequestDto>> getValues() const;
    bool valuesIsSet() const;
    void unsetValues();
    void setValues(const std::vector<std::shared_ptr<EcfReceptionRequestDto>>& value);

    int32_t getTotal() const;
    bool totalIsSet() const;
    void unsetTotal();
    void setTotal(int32_t value);

    int32_t getPage() const;
    bool pageIsSet() const;
    void unsetPage();
    void setPage(int32_t value);

    int32_t getLimit() const;
    bool limitIsSet() const;
    void unsetLimit();
    void setLimit(int32_t value);

    int32_t getNextPage() const;
    bool nextPageIsSet() const;
    void unsetNextPage();
    void setNextPage(int32_t value);

    int32_t getPreviousPage() const;
    bool previousPageIsSet() const;
    void unsetPreviousPage();
    void setPreviousPage(int32_t value);


protected:
    boost::optional<utility::string_t> m_NextPageUri;

    std::vector<std::shared_ptr<EcfReceptionRequestDto>> m_Values;
    bool m_ValuesIsSet;

    int32_t m_Total;
    bool m_TotalIsSet;

    int32_t m_Page;
    bool m_PageIsSet;

    int32_t m_Limit;
    bool m_LimitIsSet;

    boost::optional<int32_t> m_NextPage;

    boost::optional<int32_t> m_PreviousPage;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_PaginatedApiResultOfEcfReceptionRequestDto_H_ */
