/**
 * ECF API
 * ECF API (Electronic Fiscal Receipt).
 *
 * The version of the OpenAPI document: v1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.14.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * SearchEcfReceptionRequests_TiposEcfs_parameter_inner.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_SearchEcfReceptionRequests_TiposEcfs_parameter_inner_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_SearchEcfReceptionRequests_TiposEcfs_parameter_inner_H_


#include "ecf-dgii-client/ModelBase.h"


namespace org {
namespace openapitools {
namespace client {
namespace model {



class  SearchEcfReceptionRequests_TiposEcfs_parameter_inner
    : public ModelBase
{
public:
    SearchEcfReceptionRequests_TiposEcfs_parameter_inner();
    virtual ~SearchEcfReceptionRequests_TiposEcfs_parameter_inner();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// SearchEcfReceptionRequests_TiposEcfs_parameter_inner members



protected:
};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_SearchEcfReceptionRequests_TiposEcfs_parameter_inner_H_ */
