/**
 * ECF API
 * ECF API (Electronic Fiscal Receipt).
 *
 * The version of the OpenAPI document: v1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.20.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * TipoPagoType.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_TipoPagoType_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_TipoPagoType_H_

#include <boost/optional.hpp>

#include "ecf-dgii-client/ModelBase.h"


namespace org {
namespace openapitools {
namespace client {
namespace model {


class  TipoPagoType
    : public ModelBase
{
public:
    TipoPagoType();
    TipoPagoType(utility::string_t str);
    operator utility::string_t() const {
        return enumToStrMap.at(getValue());
    }


    virtual ~TipoPagoType();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    enum class eTipoPagoType
    {
        CONTADO,
        CREDITO,
        GRATUITO,
    };

    eTipoPagoType getValue() const;
    void setValue(eTipoPagoType const value);

    protected:
        eTipoPagoType m_value;
        std::map<eTipoPagoType,utility::string_t> enumToStrMap = {
        { eTipoPagoType::CONTADO, _XPLATSTR("Contado") },
        { eTipoPagoType::CREDITO, _XPLATSTR("Credito") },
        { eTipoPagoType::GRATUITO, _XPLATSTR("Gratuito") }
};
        std::map<utility::string_t,eTipoPagoType> strToEnumMap = {
        { _XPLATSTR("Contado"), eTipoPagoType::CONTADO },
        { _XPLATSTR("Credito"), eTipoPagoType::CREDITO },
        { _XPLATSTR("Gratuito"), eTipoPagoType::GRATUITO }
};

};

}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_TipoPagoType_H_ */
