/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dom.com.ssd.ecfx.sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import dom.com.ssd.ecfx.sdk.models.Ecf31FormaDePago
import dom.com.ssd.ecfx.sdk.models.Ecf31FormaDePagoMontoPago
import dom.com.ssd.ecfx.sdk.models.Ecf31FormaPagoType

class Ecf31FormaDePagoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Ecf31FormaDePago
        //val modelInstance = Ecf31FormaDePago()

        // to test the property `formaPago`
        should("test formaPago") {
            // uncomment below to test the property
            //modelInstance.formaPago shouldBe ("TODO")
        }

        // to test the property `montoPago`
        should("test montoPago") {
            // uncomment below to test the property
            //modelInstance.montoPago shouldBe ("TODO")
        }

    }
}
