/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dom.com.ssd.ecfx.sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import dom.com.ssd.ecfx.sdk.models.Ecf45Totales
import dom.com.ssd.ecfx.sdk.models.Ecf31DescuentoORecargoMontoDescuentooRecargo
import dom.com.ssd.ecfx.sdk.models.Ecf31FormaDePagoMontoPago
import dom.com.ssd.ecfx.sdk.models.Ecf31IdDocTotalPaginas
import dom.com.ssd.ecfx.sdk.models.Ecf31ImpuestoAdicional2MontoImpuestoSelectivoConsumoEspecifico
import dom.com.ssd.ecfx.sdk.models.Ecf31TotalesMontoNoFacturable
import dom.com.ssd.ecfx.sdk.models.Ecf45ImpuestoAdicional2

class Ecf45TotalesTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Ecf45Totales
        //val modelInstance = Ecf45Totales()

        // to test the property `montoTotal`
        should("test montoTotal") {
            // uncomment below to test the property
            //modelInstance.montoTotal shouldBe ("TODO")
        }

        // to test the property `montoGravadoTotal`
        should("test montoGravadoTotal") {
            // uncomment below to test the property
            //modelInstance.montoGravadoTotal shouldBe ("TODO")
        }

        // to test the property `montoGravadoI1`
        should("test montoGravadoI1") {
            // uncomment below to test the property
            //modelInstance.montoGravadoI1 shouldBe ("TODO")
        }

        // to test the property `montoGravadoI2`
        should("test montoGravadoI2") {
            // uncomment below to test the property
            //modelInstance.montoGravadoI2 shouldBe ("TODO")
        }

        // to test the property `montoGravadoI3`
        should("test montoGravadoI3") {
            // uncomment below to test the property
            //modelInstance.montoGravadoI3 shouldBe ("TODO")
        }

        // to test the property `montoExento`
        should("test montoExento") {
            // uncomment below to test the property
            //modelInstance.montoExento shouldBe ("TODO")
        }

        // to test the property `itbiS1`
        should("test itbiS1") {
            // uncomment below to test the property
            //modelInstance.itbiS1 shouldBe ("TODO")
        }

        // to test the property `itbiS2`
        should("test itbiS2") {
            // uncomment below to test the property
            //modelInstance.itbiS2 shouldBe ("TODO")
        }

        // to test the property `itbiS3`
        should("test itbiS3") {
            // uncomment below to test the property
            //modelInstance.itbiS3 shouldBe ("TODO")
        }

        // to test the property `totalITBIS`
        should("test totalITBIS") {
            // uncomment below to test the property
            //modelInstance.totalITBIS shouldBe ("TODO")
        }

        // to test the property `totalITBIS1`
        should("test totalITBIS1") {
            // uncomment below to test the property
            //modelInstance.totalITBIS1 shouldBe ("TODO")
        }

        // to test the property `totalITBIS2`
        should("test totalITBIS2") {
            // uncomment below to test the property
            //modelInstance.totalITBIS2 shouldBe ("TODO")
        }

        // to test the property `totalITBIS3`
        should("test totalITBIS3") {
            // uncomment below to test the property
            //modelInstance.totalITBIS3 shouldBe ("TODO")
        }

        // to test the property `montoImpuestoAdicional`
        should("test montoImpuestoAdicional") {
            // uncomment below to test the property
            //modelInstance.montoImpuestoAdicional shouldBe ("TODO")
        }

        // to test the property `impuestosAdicionales`
        should("test impuestosAdicionales") {
            // uncomment below to test the property
            //modelInstance.impuestosAdicionales shouldBe ("TODO")
        }

        // to test the property `montoNoFacturable`
        should("test montoNoFacturable") {
            // uncomment below to test the property
            //modelInstance.montoNoFacturable shouldBe ("TODO")
        }

        // to test the property `montoPeriodo`
        should("test montoPeriodo") {
            // uncomment below to test the property
            //modelInstance.montoPeriodo shouldBe ("TODO")
        }

        // to test the property `saldoAnterior`
        should("test saldoAnterior") {
            // uncomment below to test the property
            //modelInstance.saldoAnterior shouldBe ("TODO")
        }

        // to test the property `montoAvancePago`
        should("test montoAvancePago") {
            // uncomment below to test the property
            //modelInstance.montoAvancePago shouldBe ("TODO")
        }

        // to test the property `valorPagar`
        should("test valorPagar") {
            // uncomment below to test the property
            //modelInstance.valorPagar shouldBe ("TODO")
        }

    }
}
