/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dom.com.ssd.ecfx.sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import dom.com.ssd.ecfx.sdk.models.Ecf41InformacionReferencia
import dom.com.ssd.ecfx.sdk.models.CodigoModificacionType

class Ecf41InformacionReferenciaTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Ecf41InformacionReferencia
        //val modelInstance = Ecf41InformacionReferencia()

        // to test the property `ncfModificado`
        should("test ncfModificado") {
            // uncomment below to test the property
            //modelInstance.ncfModificado shouldBe ("TODO")
        }

        // to test the property `rncOtroContribuyente`
        should("test rncOtroContribuyente") {
            // uncomment below to test the property
            //modelInstance.rncOtroContribuyente shouldBe ("TODO")
        }

        // to test the property `fechaNCFModificado`
        should("test fechaNCFModificado") {
            // uncomment below to test the property
            //modelInstance.fechaNCFModificado shouldBe ("TODO")
        }

        // to test the property `codigoModificacion`
        should("test codigoModificacion") {
            // uncomment below to test the property
            //modelInstance.codigoModificacion shouldBe ("TODO")
        }

    }
}
