/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ecfx.sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.ecfx.sdk.models.ImpuestoAdicionalOtraMoneda
import com.ecfx.sdk.models.CodificacionTipoImpuestosType
import com.ecfx.sdk.models.DescuentoORecargoValorDescuentooRecargo
import com.ecfx.sdk.models.ImpuestoAdicional2MontoImpuestoSelectivoConsumoEspecifico

class ImpuestoAdicionalOtraMonedaTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ImpuestoAdicionalOtraMoneda
        //val modelInstance = ImpuestoAdicionalOtraMoneda()

        // to test the property `tipoImpuestoOtraMoneda`
        should("test tipoImpuestoOtraMoneda") {
            // uncomment below to test the property
            //modelInstance.tipoImpuestoOtraMoneda shouldBe ("TODO")
        }

        // to test the property `tasaImpuestoAdicionalOtraMoneda`
        should("test tasaImpuestoAdicionalOtraMoneda") {
            // uncomment below to test the property
            //modelInstance.tasaImpuestoAdicionalOtraMoneda shouldBe ("TODO")
        }

        // to test the property `montoImpuestoSelectivoConsumoEspecificoOtraMoneda`
        should("test montoImpuestoSelectivoConsumoEspecificoOtraMoneda") {
            // uncomment below to test the property
            //modelInstance.montoImpuestoSelectivoConsumoEspecificoOtraMoneda shouldBe ("TODO")
        }

        // to test the property `montoImpuestoSelectivoConsumoAdvaloremOtraMoneda`
        should("test montoImpuestoSelectivoConsumoAdvaloremOtraMoneda") {
            // uncomment below to test the property
            //modelInstance.montoImpuestoSelectivoConsumoAdvaloremOtraMoneda shouldBe ("TODO")
        }

        // to test the property `otrosImpuestosAdicionalesOtraMoneda`
        should("test otrosImpuestosAdicionalesOtraMoneda") {
            // uncomment below to test the property
            //modelInstance.otrosImpuestosAdicionalesOtraMoneda shouldBe ("TODO")
        }

    }
}
