/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ecfx.sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.ecfx.sdk.models.Mineria
import com.ecfx.sdk.models.LiquidacionType
import com.ecfx.sdk.models.MineriaPesoNetoKilogramo
import com.ecfx.sdk.models.TipoAfiliacionType

class MineriaTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Mineria
        //val modelInstance = Mineria()

        // to test the property `pesoNetoKilogramo`
        should("test pesoNetoKilogramo") {
            // uncomment below to test the property
            //modelInstance.pesoNetoKilogramo shouldBe ("TODO")
        }

        // to test the property `pesoNetoMineria`
        should("test pesoNetoMineria") {
            // uncomment below to test the property
            //modelInstance.pesoNetoMineria shouldBe ("TODO")
        }

        // to test the property `tipoAfiliacion`
        should("test tipoAfiliacion") {
            // uncomment below to test the property
            //modelInstance.tipoAfiliacion shouldBe ("TODO")
        }

        // to test the property `liquidacion`
        should("test liquidacion") {
            // uncomment below to test the property
            //modelInstance.liquidacion shouldBe ("TODO")
        }

    }
}
