/**
 * ECF API
 * ECF API (Electronic Fiscal Receipt).
 *
 * The version of the OpenAPI document: v1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.20.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "ecf-dgii-client/model/Ecf34TipoIngresosValidationType.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

namespace
{
using EnumUnderlyingType = utility::string_t;

Ecf34TipoIngresosValidationType::eEcf34TipoIngresosValidationType toEnum(const EnumUnderlyingType& val)
{
    if (val == utility::conversions::to_string_t(_XPLATSTR("01")))
        return Ecf34TipoIngresosValidationType::eEcf34TipoIngresosValidationType::_01;
    if (val == utility::conversions::to_string_t(_XPLATSTR("02")))
        return Ecf34TipoIngresosValidationType::eEcf34TipoIngresosValidationType::_02;
    if (val == utility::conversions::to_string_t(_XPLATSTR("03")))
        return Ecf34TipoIngresosValidationType::eEcf34TipoIngresosValidationType::_03;
    if (val == utility::conversions::to_string_t(_XPLATSTR("04")))
        return Ecf34TipoIngresosValidationType::eEcf34TipoIngresosValidationType::_04;
    if (val == utility::conversions::to_string_t(_XPLATSTR("05")))
        return Ecf34TipoIngresosValidationType::eEcf34TipoIngresosValidationType::_05;
    if (val == utility::conversions::to_string_t(_XPLATSTR("06")))
        return Ecf34TipoIngresosValidationType::eEcf34TipoIngresosValidationType::_06;
    return {};
}

EnumUnderlyingType fromEnum(Ecf34TipoIngresosValidationType::eEcf34TipoIngresosValidationType e)
{
    switch (e)
    {
    case Ecf34TipoIngresosValidationType::eEcf34TipoIngresosValidationType::_01:
        return _XPLATSTR("01");
    case Ecf34TipoIngresosValidationType::eEcf34TipoIngresosValidationType::_02:
        return _XPLATSTR("02");
    case Ecf34TipoIngresosValidationType::eEcf34TipoIngresosValidationType::_03:
        return _XPLATSTR("03");
    case Ecf34TipoIngresosValidationType::eEcf34TipoIngresosValidationType::_04:
        return _XPLATSTR("04");
    case Ecf34TipoIngresosValidationType::eEcf34TipoIngresosValidationType::_05:
        return _XPLATSTR("05");
    case Ecf34TipoIngresosValidationType::eEcf34TipoIngresosValidationType::_06:
        return _XPLATSTR("06");
    default:
        break;
    }
    return {};
}
}

Ecf34TipoIngresosValidationType::Ecf34TipoIngresosValidationType()
{
}

Ecf34TipoIngresosValidationType::~Ecf34TipoIngresosValidationType()
{
}

void Ecf34TipoIngresosValidationType::validate()
{
    // TODO: implement validation
}

web::json::value Ecf34TipoIngresosValidationType::toJson() const
{
    auto val = fromEnum(m_value);
    return web::json::value(val);
}

bool Ecf34TipoIngresosValidationType::fromJson(const web::json::value& val)
{
    m_value = toEnum(val.as_string());
    return true;
}

void Ecf34TipoIngresosValidationType::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if (!namePrefix.empty() && namePrefix.back() != _XPLATSTR('.'))
    {
        namePrefix.push_back(_XPLATSTR('.'));
    }

    auto e = fromEnum(m_value);
    multipart->add(ModelBase::toHttpContent(namePrefix, e));
}

bool Ecf34TipoIngresosValidationType::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if (!namePrefix.empty() && namePrefix.back() != _XPLATSTR('.'))
    {
        namePrefix.push_back(_XPLATSTR('.'));
    }
    {
        EnumUnderlyingType e;
        ok = ModelBase::fromHttpContent(multipart->getContent(namePrefix), e);
        if (ok)
        {
            auto v = toEnum(e);
            setValue(v);
        }
    }
    return ok;
}

Ecf34TipoIngresosValidationType::eEcf34TipoIngresosValidationType Ecf34TipoIngresosValidationType::getValue() const
{
   return m_value;
}

void Ecf34TipoIngresosValidationType::setValue(Ecf34TipoIngresosValidationType::eEcf34TipoIngresosValidationType const value)
{
   m_value = value;
}

Ecf34TipoIngresosValidationType::Ecf34TipoIngresosValidationType(utility::string_t str){
    setValue( strToEnumMap[str] );
}

}
}
}
}


