/**
 * ECF API
 * ECF API (Electronic Fiscal Receipt).
 *
 * The version of the OpenAPI document: v1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.20.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "ecf-dgii-client/model/Ecf34VersionType.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

namespace
{
using EnumUnderlyingType = utility::string_t;

Ecf34VersionType::eEcf34VersionType toEnum(const EnumUnderlyingType& val)
{
    if (val == utility::conversions::to_string_t(_XPLATSTR("Version1_0")))
        return Ecf34VersionType::eEcf34VersionType::VERSION1_0;
    return {};
}

EnumUnderlyingType fromEnum(Ecf34VersionType::eEcf34VersionType e)
{
    switch (e)
    {
    case Ecf34VersionType::eEcf34VersionType::VERSION1_0:
        return _XPLATSTR("Version1_0");
    default:
        break;
    }
    return {};
}
}

Ecf34VersionType::Ecf34VersionType()
{
}

Ecf34VersionType::~Ecf34VersionType()
{
}

void Ecf34VersionType::validate()
{
    // TODO: implement validation
}

web::json::value Ecf34VersionType::toJson() const
{
    auto val = fromEnum(m_value);
    return web::json::value(val);
}

bool Ecf34VersionType::fromJson(const web::json::value& val)
{
    m_value = toEnum(val.as_string());
    return true;
}

void Ecf34VersionType::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if (!namePrefix.empty() && namePrefix.back() != _XPLATSTR('.'))
    {
        namePrefix.push_back(_XPLATSTR('.'));
    }

    auto e = fromEnum(m_value);
    multipart->add(ModelBase::toHttpContent(namePrefix, e));
}

bool Ecf34VersionType::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if (!namePrefix.empty() && namePrefix.back() != _XPLATSTR('.'))
    {
        namePrefix.push_back(_XPLATSTR('.'));
    }
    {
        EnumUnderlyingType e;
        ok = ModelBase::fromHttpContent(multipart->getContent(namePrefix), e);
        if (ok)
        {
            auto v = toEnum(e);
            setValue(v);
        }
    }
    return ok;
}

Ecf34VersionType::eEcf34VersionType Ecf34VersionType::getValue() const
{
   return m_value;
}

void Ecf34VersionType::setValue(Ecf34VersionType::eEcf34VersionType const value)
{
   m_value = value;
}

Ecf34VersionType::Ecf34VersionType(utility::string_t str){
    setValue( strToEnumMap[str] );
}

}
}
}
}


