/**
 * ECF API
 * ECF API (Electronic Fiscal Receipt).
 *
 * The version of the OpenAPI document: v1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.20.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "ecf-dgii-client/model/Ecf43Pagina.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

Ecf43Pagina::Ecf43Pagina()
{
}

Ecf43Pagina::~Ecf43Pagina()
{
}

void Ecf43Pagina::validate()
{
    // TODO: implement validation
}

web::json::value Ecf43Pagina::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_PaginaNo.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("paginaNo"))] = ModelBase::toJson(m_PaginaNo.get());
    }
    if(m_NoLineaDesde.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("noLineaDesde"))] = ModelBase::toJson(m_NoLineaDesde.get());
    }
    if(m_NoLineaHasta.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("noLineaHasta"))] = ModelBase::toJson(m_NoLineaHasta.get());
    }
    if(m_SubtotalExentoPagina.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("subtotalExentoPagina"))] = ModelBase::toJson(m_SubtotalExentoPagina.get());
    }
    if(m_MontoSubtotalPagina.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("montoSubtotalPagina"))] = ModelBase::toJson(m_MontoSubtotalPagina.get());
    }

    return val;
}

bool Ecf43Pagina::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("paginaNo"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("paginaNo")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<Ecf31IdDoc_totalPaginas> refVal_setPaginaNo;
            ok &= ModelBase::fromJson(fieldValue, refVal_setPaginaNo);
            setPaginaNo(refVal_setPaginaNo);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("noLineaDesde"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("noLineaDesde")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<Ecf31IdDoc_totalPaginas> refVal_setNoLineaDesde;
            ok &= ModelBase::fromJson(fieldValue, refVal_setNoLineaDesde);
            setNoLineaDesde(refVal_setNoLineaDesde);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("noLineaHasta"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("noLineaHasta")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<Ecf31IdDoc_totalPaginas> refVal_setNoLineaHasta;
            ok &= ModelBase::fromJson(fieldValue, refVal_setNoLineaHasta);
            setNoLineaHasta(refVal_setNoLineaHasta);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("subtotalExentoPagina"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("subtotalExentoPagina")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<Ecf31DescuentoORecargo_montoDescuentooRecargo> refVal_setSubtotalExentoPagina;
            ok &= ModelBase::fromJson(fieldValue, refVal_setSubtotalExentoPagina);
            setSubtotalExentoPagina(refVal_setSubtotalExentoPagina);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("montoSubtotalPagina"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("montoSubtotalPagina")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<Ecf31DescuentoORecargo_montoDescuentooRecargo> refVal_setMontoSubtotalPagina;
            ok &= ModelBase::fromJson(fieldValue, refVal_setMontoSubtotalPagina);
            setMontoSubtotalPagina(refVal_setMontoSubtotalPagina);
            
        }
    }
    return ok;
}

void Ecf43Pagina::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_PaginaNo.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("paginaNo")), m_PaginaNo.get()));
    }
    if(m_NoLineaDesde.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("noLineaDesde")), m_NoLineaDesde.get()));
    }
    if(m_NoLineaHasta.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("noLineaHasta")), m_NoLineaHasta.get()));
    }
    if(m_SubtotalExentoPagina.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("subtotalExentoPagina")), m_SubtotalExentoPagina.get()));
    }
    if(m_MontoSubtotalPagina.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("montoSubtotalPagina")), m_MontoSubtotalPagina.get()));
    }
}

bool Ecf43Pagina::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("paginaNo"))))
    {
        std::shared_ptr<Ecf31IdDoc_totalPaginas> refVal_setPaginaNo;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("paginaNo"))), refVal_setPaginaNo );
        setPaginaNo(refVal_setPaginaNo);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("noLineaDesde"))))
    {
        std::shared_ptr<Ecf31IdDoc_totalPaginas> refVal_setNoLineaDesde;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("noLineaDesde"))), refVal_setNoLineaDesde );
        setNoLineaDesde(refVal_setNoLineaDesde);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("noLineaHasta"))))
    {
        std::shared_ptr<Ecf31IdDoc_totalPaginas> refVal_setNoLineaHasta;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("noLineaHasta"))), refVal_setNoLineaHasta );
        setNoLineaHasta(refVal_setNoLineaHasta);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("subtotalExentoPagina"))))
    {
        std::shared_ptr<Ecf31DescuentoORecargo_montoDescuentooRecargo> refVal_setSubtotalExentoPagina;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("subtotalExentoPagina"))), refVal_setSubtotalExentoPagina );
        setSubtotalExentoPagina(refVal_setSubtotalExentoPagina);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("montoSubtotalPagina"))))
    {
        std::shared_ptr<Ecf31DescuentoORecargo_montoDescuentooRecargo> refVal_setMontoSubtotalPagina;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("montoSubtotalPagina"))), refVal_setMontoSubtotalPagina );
        setMontoSubtotalPagina(refVal_setMontoSubtotalPagina);
    }
    return ok;
}


std::shared_ptr<Ecf31IdDoc_totalPaginas> Ecf43Pagina::getPaginaNo() const
{
    return m_PaginaNo.get();
}


void Ecf43Pagina::setPaginaNo(const std::shared_ptr<Ecf31IdDoc_totalPaginas>& value)
{
    m_PaginaNo = value;
}

bool Ecf43Pagina::paginaNoIsSet() const
{
    return m_PaginaNo.has_value();
}

void Ecf43Pagina::unsetPaginaNo()
{
    m_PaginaNo.reset();
}
std::shared_ptr<Ecf31IdDoc_totalPaginas> Ecf43Pagina::getNoLineaDesde() const
{
    return m_NoLineaDesde.get();
}


void Ecf43Pagina::setNoLineaDesde(const std::shared_ptr<Ecf31IdDoc_totalPaginas>& value)
{
    m_NoLineaDesde = value;
}

bool Ecf43Pagina::noLineaDesdeIsSet() const
{
    return m_NoLineaDesde.has_value();
}

void Ecf43Pagina::unsetNoLineaDesde()
{
    m_NoLineaDesde.reset();
}
std::shared_ptr<Ecf31IdDoc_totalPaginas> Ecf43Pagina::getNoLineaHasta() const
{
    return m_NoLineaHasta.get();
}


void Ecf43Pagina::setNoLineaHasta(const std::shared_ptr<Ecf31IdDoc_totalPaginas>& value)
{
    m_NoLineaHasta = value;
}

bool Ecf43Pagina::noLineaHastaIsSet() const
{
    return m_NoLineaHasta.has_value();
}

void Ecf43Pagina::unsetNoLineaHasta()
{
    m_NoLineaHasta.reset();
}
std::shared_ptr<Ecf31DescuentoORecargo_montoDescuentooRecargo> Ecf43Pagina::getSubtotalExentoPagina() const
{
    return m_SubtotalExentoPagina.get();
}


void Ecf43Pagina::setSubtotalExentoPagina(const std::shared_ptr<Ecf31DescuentoORecargo_montoDescuentooRecargo>& value)
{
    m_SubtotalExentoPagina = value;
}

bool Ecf43Pagina::subtotalExentoPaginaIsSet() const
{
    return m_SubtotalExentoPagina.has_value();
}

void Ecf43Pagina::unsetSubtotalExentoPagina()
{
    m_SubtotalExentoPagina.reset();
}
std::shared_ptr<Ecf31DescuentoORecargo_montoDescuentooRecargo> Ecf43Pagina::getMontoSubtotalPagina() const
{
    return m_MontoSubtotalPagina.get();
}


void Ecf43Pagina::setMontoSubtotalPagina(const std::shared_ptr<Ecf31DescuentoORecargo_montoDescuentooRecargo>& value)
{
    m_MontoSubtotalPagina = value;
}

bool Ecf43Pagina::montoSubtotalPaginaIsSet() const
{
    return m_MontoSubtotalPagina.has_value();
}

void Ecf43Pagina::unsetMontoSubtotalPagina()
{
    m_MontoSubtotalPagina.reset();
}

}
}
}
}


