/**
 * ECF API
 * ECF API (Electronic Fiscal Receipt).
 *
 * The version of the OpenAPI document: v1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.14.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "ecf-dgii-client/model/Ecf41Pagina.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

Ecf41Pagina::Ecf41Pagina()
{
    m_PaginaNoIsSet = false;
    m_NoLineaDesdeIsSet = false;
    m_NoLineaHastaIsSet = false;
    m_SubtotalMontoGravadoPaginaIsSet = false;
    m_SubtotalMontoGravado1PaginaIsSet = false;
    m_SubtotalMontoGravado2PaginaIsSet = false;
    m_SubtotalMontoGravado3PaginaIsSet = false;
    m_SubtotalExentoPaginaIsSet = false;
    m_SubtotalItbisPaginaIsSet = false;
    m_SubtotalItbis1PaginaIsSet = false;
    m_SubtotalItbis2PaginaIsSet = false;
    m_SubtotalItbis3PaginaIsSet = false;
    m_MontoSubtotalPaginaIsSet = false;
}

Ecf41Pagina::~Ecf41Pagina()
{
}

void Ecf41Pagina::validate()
{
    // TODO: implement validation
}

web::json::value Ecf41Pagina::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_PaginaNoIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("paginaNo"))] = ModelBase::toJson(m_PaginaNo);
    }
    if(m_NoLineaDesdeIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("noLineaDesde"))] = ModelBase::toJson(m_NoLineaDesde);
    }
    if(m_NoLineaHastaIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("noLineaHasta"))] = ModelBase::toJson(m_NoLineaHasta);
    }
    if(m_SubtotalMontoGravadoPaginaIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("subtotalMontoGravadoPagina"))] = ModelBase::toJson(m_SubtotalMontoGravadoPagina);
    }
    if(m_SubtotalMontoGravado1PaginaIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("subtotalMontoGravado1Pagina"))] = ModelBase::toJson(m_SubtotalMontoGravado1Pagina);
    }
    if(m_SubtotalMontoGravado2PaginaIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("subtotalMontoGravado2Pagina"))] = ModelBase::toJson(m_SubtotalMontoGravado2Pagina);
    }
    if(m_SubtotalMontoGravado3PaginaIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("subtotalMontoGravado3Pagina"))] = ModelBase::toJson(m_SubtotalMontoGravado3Pagina);
    }
    if(m_SubtotalExentoPaginaIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("subtotalExentoPagina"))] = ModelBase::toJson(m_SubtotalExentoPagina);
    }
    if(m_SubtotalItbisPaginaIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("subtotalItbisPagina"))] = ModelBase::toJson(m_SubtotalItbisPagina);
    }
    if(m_SubtotalItbis1PaginaIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("subtotalItbis1Pagina"))] = ModelBase::toJson(m_SubtotalItbis1Pagina);
    }
    if(m_SubtotalItbis2PaginaIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("subtotalItbis2Pagina"))] = ModelBase::toJson(m_SubtotalItbis2Pagina);
    }
    if(m_SubtotalItbis3PaginaIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("subtotalItbis3Pagina"))] = ModelBase::toJson(m_SubtotalItbis3Pagina);
    }
    if(m_MontoSubtotalPaginaIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("montoSubtotalPagina"))] = ModelBase::toJson(m_MontoSubtotalPagina);
    }

    return val;
}

bool Ecf41Pagina::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("paginaNo"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("paginaNo")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<Ecf31IdDoc_totalPaginas> refVal_setPaginaNo;
            ok &= ModelBase::fromJson(fieldValue, refVal_setPaginaNo);
            setPaginaNo(refVal_setPaginaNo);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("noLineaDesde"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("noLineaDesde")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<Ecf31IdDoc_totalPaginas> refVal_setNoLineaDesde;
            ok &= ModelBase::fromJson(fieldValue, refVal_setNoLineaDesde);
            setNoLineaDesde(refVal_setNoLineaDesde);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("noLineaHasta"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("noLineaHasta")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<Ecf31IdDoc_totalPaginas> refVal_setNoLineaHasta;
            ok &= ModelBase::fromJson(fieldValue, refVal_setNoLineaHasta);
            setNoLineaHasta(refVal_setNoLineaHasta);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("subtotalMontoGravadoPagina"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("subtotalMontoGravadoPagina")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<Ecf31DescuentoORecargo_montoDescuentooRecargo> refVal_setSubtotalMontoGravadoPagina;
            ok &= ModelBase::fromJson(fieldValue, refVal_setSubtotalMontoGravadoPagina);
            setSubtotalMontoGravadoPagina(refVal_setSubtotalMontoGravadoPagina);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("subtotalMontoGravado1Pagina"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("subtotalMontoGravado1Pagina")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<Ecf31DescuentoORecargo_montoDescuentooRecargo> refVal_setSubtotalMontoGravado1Pagina;
            ok &= ModelBase::fromJson(fieldValue, refVal_setSubtotalMontoGravado1Pagina);
            setSubtotalMontoGravado1Pagina(refVal_setSubtotalMontoGravado1Pagina);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("subtotalMontoGravado2Pagina"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("subtotalMontoGravado2Pagina")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<Ecf31DescuentoORecargo_montoDescuentooRecargo> refVal_setSubtotalMontoGravado2Pagina;
            ok &= ModelBase::fromJson(fieldValue, refVal_setSubtotalMontoGravado2Pagina);
            setSubtotalMontoGravado2Pagina(refVal_setSubtotalMontoGravado2Pagina);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("subtotalMontoGravado3Pagina"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("subtotalMontoGravado3Pagina")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<Ecf31DescuentoORecargo_montoDescuentooRecargo> refVal_setSubtotalMontoGravado3Pagina;
            ok &= ModelBase::fromJson(fieldValue, refVal_setSubtotalMontoGravado3Pagina);
            setSubtotalMontoGravado3Pagina(refVal_setSubtotalMontoGravado3Pagina);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("subtotalExentoPagina"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("subtotalExentoPagina")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<Ecf31DescuentoORecargo_montoDescuentooRecargo> refVal_setSubtotalExentoPagina;
            ok &= ModelBase::fromJson(fieldValue, refVal_setSubtotalExentoPagina);
            setSubtotalExentoPagina(refVal_setSubtotalExentoPagina);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("subtotalItbisPagina"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("subtotalItbisPagina")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<Ecf31DescuentoORecargo_montoDescuentooRecargo> refVal_setSubtotalItbisPagina;
            ok &= ModelBase::fromJson(fieldValue, refVal_setSubtotalItbisPagina);
            setSubtotalItbisPagina(refVal_setSubtotalItbisPagina);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("subtotalItbis1Pagina"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("subtotalItbis1Pagina")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<Ecf31DescuentoORecargo_montoDescuentooRecargo> refVal_setSubtotalItbis1Pagina;
            ok &= ModelBase::fromJson(fieldValue, refVal_setSubtotalItbis1Pagina);
            setSubtotalItbis1Pagina(refVal_setSubtotalItbis1Pagina);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("subtotalItbis2Pagina"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("subtotalItbis2Pagina")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<Ecf31DescuentoORecargo_montoDescuentooRecargo> refVal_setSubtotalItbis2Pagina;
            ok &= ModelBase::fromJson(fieldValue, refVal_setSubtotalItbis2Pagina);
            setSubtotalItbis2Pagina(refVal_setSubtotalItbis2Pagina);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("subtotalItbis3Pagina"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("subtotalItbis3Pagina")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<Ecf31DescuentoORecargo_montoDescuentooRecargo> refVal_setSubtotalItbis3Pagina;
            ok &= ModelBase::fromJson(fieldValue, refVal_setSubtotalItbis3Pagina);
            setSubtotalItbis3Pagina(refVal_setSubtotalItbis3Pagina);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("montoSubtotalPagina"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("montoSubtotalPagina")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<Ecf31DescuentoORecargo_montoDescuentooRecargo> refVal_setMontoSubtotalPagina;
            ok &= ModelBase::fromJson(fieldValue, refVal_setMontoSubtotalPagina);
            setMontoSubtotalPagina(refVal_setMontoSubtotalPagina);
            
        }
    }
    return ok;
}

void Ecf41Pagina::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_PaginaNoIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("paginaNo")), m_PaginaNo));
    }
    if(m_NoLineaDesdeIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("noLineaDesde")), m_NoLineaDesde));
    }
    if(m_NoLineaHastaIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("noLineaHasta")), m_NoLineaHasta));
    }
    if(m_SubtotalMontoGravadoPaginaIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("subtotalMontoGravadoPagina")), m_SubtotalMontoGravadoPagina));
    }
    if(m_SubtotalMontoGravado1PaginaIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("subtotalMontoGravado1Pagina")), m_SubtotalMontoGravado1Pagina));
    }
    if(m_SubtotalMontoGravado2PaginaIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("subtotalMontoGravado2Pagina")), m_SubtotalMontoGravado2Pagina));
    }
    if(m_SubtotalMontoGravado3PaginaIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("subtotalMontoGravado3Pagina")), m_SubtotalMontoGravado3Pagina));
    }
    if(m_SubtotalExentoPaginaIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("subtotalExentoPagina")), m_SubtotalExentoPagina));
    }
    if(m_SubtotalItbisPaginaIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("subtotalItbisPagina")), m_SubtotalItbisPagina));
    }
    if(m_SubtotalItbis1PaginaIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("subtotalItbis1Pagina")), m_SubtotalItbis1Pagina));
    }
    if(m_SubtotalItbis2PaginaIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("subtotalItbis2Pagina")), m_SubtotalItbis2Pagina));
    }
    if(m_SubtotalItbis3PaginaIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("subtotalItbis3Pagina")), m_SubtotalItbis3Pagina));
    }
    if(m_MontoSubtotalPaginaIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("montoSubtotalPagina")), m_MontoSubtotalPagina));
    }
}

bool Ecf41Pagina::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("paginaNo"))))
    {
        std::shared_ptr<Ecf31IdDoc_totalPaginas> refVal_setPaginaNo;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("paginaNo"))), refVal_setPaginaNo );
        setPaginaNo(refVal_setPaginaNo);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("noLineaDesde"))))
    {
        std::shared_ptr<Ecf31IdDoc_totalPaginas> refVal_setNoLineaDesde;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("noLineaDesde"))), refVal_setNoLineaDesde );
        setNoLineaDesde(refVal_setNoLineaDesde);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("noLineaHasta"))))
    {
        std::shared_ptr<Ecf31IdDoc_totalPaginas> refVal_setNoLineaHasta;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("noLineaHasta"))), refVal_setNoLineaHasta );
        setNoLineaHasta(refVal_setNoLineaHasta);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("subtotalMontoGravadoPagina"))))
    {
        std::shared_ptr<Ecf31DescuentoORecargo_montoDescuentooRecargo> refVal_setSubtotalMontoGravadoPagina;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("subtotalMontoGravadoPagina"))), refVal_setSubtotalMontoGravadoPagina );
        setSubtotalMontoGravadoPagina(refVal_setSubtotalMontoGravadoPagina);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("subtotalMontoGravado1Pagina"))))
    {
        std::shared_ptr<Ecf31DescuentoORecargo_montoDescuentooRecargo> refVal_setSubtotalMontoGravado1Pagina;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("subtotalMontoGravado1Pagina"))), refVal_setSubtotalMontoGravado1Pagina );
        setSubtotalMontoGravado1Pagina(refVal_setSubtotalMontoGravado1Pagina);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("subtotalMontoGravado2Pagina"))))
    {
        std::shared_ptr<Ecf31DescuentoORecargo_montoDescuentooRecargo> refVal_setSubtotalMontoGravado2Pagina;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("subtotalMontoGravado2Pagina"))), refVal_setSubtotalMontoGravado2Pagina );
        setSubtotalMontoGravado2Pagina(refVal_setSubtotalMontoGravado2Pagina);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("subtotalMontoGravado3Pagina"))))
    {
        std::shared_ptr<Ecf31DescuentoORecargo_montoDescuentooRecargo> refVal_setSubtotalMontoGravado3Pagina;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("subtotalMontoGravado3Pagina"))), refVal_setSubtotalMontoGravado3Pagina );
        setSubtotalMontoGravado3Pagina(refVal_setSubtotalMontoGravado3Pagina);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("subtotalExentoPagina"))))
    {
        std::shared_ptr<Ecf31DescuentoORecargo_montoDescuentooRecargo> refVal_setSubtotalExentoPagina;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("subtotalExentoPagina"))), refVal_setSubtotalExentoPagina );
        setSubtotalExentoPagina(refVal_setSubtotalExentoPagina);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("subtotalItbisPagina"))))
    {
        std::shared_ptr<Ecf31DescuentoORecargo_montoDescuentooRecargo> refVal_setSubtotalItbisPagina;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("subtotalItbisPagina"))), refVal_setSubtotalItbisPagina );
        setSubtotalItbisPagina(refVal_setSubtotalItbisPagina);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("subtotalItbis1Pagina"))))
    {
        std::shared_ptr<Ecf31DescuentoORecargo_montoDescuentooRecargo> refVal_setSubtotalItbis1Pagina;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("subtotalItbis1Pagina"))), refVal_setSubtotalItbis1Pagina );
        setSubtotalItbis1Pagina(refVal_setSubtotalItbis1Pagina);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("subtotalItbis2Pagina"))))
    {
        std::shared_ptr<Ecf31DescuentoORecargo_montoDescuentooRecargo> refVal_setSubtotalItbis2Pagina;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("subtotalItbis2Pagina"))), refVal_setSubtotalItbis2Pagina );
        setSubtotalItbis2Pagina(refVal_setSubtotalItbis2Pagina);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("subtotalItbis3Pagina"))))
    {
        std::shared_ptr<Ecf31DescuentoORecargo_montoDescuentooRecargo> refVal_setSubtotalItbis3Pagina;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("subtotalItbis3Pagina"))), refVal_setSubtotalItbis3Pagina );
        setSubtotalItbis3Pagina(refVal_setSubtotalItbis3Pagina);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("montoSubtotalPagina"))))
    {
        std::shared_ptr<Ecf31DescuentoORecargo_montoDescuentooRecargo> refVal_setMontoSubtotalPagina;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("montoSubtotalPagina"))), refVal_setMontoSubtotalPagina );
        setMontoSubtotalPagina(refVal_setMontoSubtotalPagina);
    }
    return ok;
}


std::shared_ptr<Ecf31IdDoc_totalPaginas> Ecf41Pagina::getPaginaNo() const
{
    return m_PaginaNo;
}


void Ecf41Pagina::setPaginaNo(const std::shared_ptr<Ecf31IdDoc_totalPaginas>& value)
{
    m_PaginaNo = value;
    m_PaginaNoIsSet = true;
}

bool Ecf41Pagina::paginaNoIsSet() const
{
    return m_PaginaNoIsSet;
}

void Ecf41Pagina::unsetPaginaNo()
{
    m_PaginaNoIsSet = false;
}
std::shared_ptr<Ecf31IdDoc_totalPaginas> Ecf41Pagina::getNoLineaDesde() const
{
    return m_NoLineaDesde;
}


void Ecf41Pagina::setNoLineaDesde(const std::shared_ptr<Ecf31IdDoc_totalPaginas>& value)
{
    m_NoLineaDesde = value;
    m_NoLineaDesdeIsSet = true;
}

bool Ecf41Pagina::noLineaDesdeIsSet() const
{
    return m_NoLineaDesdeIsSet;
}

void Ecf41Pagina::unsetNoLineaDesde()
{
    m_NoLineaDesdeIsSet = false;
}
std::shared_ptr<Ecf31IdDoc_totalPaginas> Ecf41Pagina::getNoLineaHasta() const
{
    return m_NoLineaHasta;
}


void Ecf41Pagina::setNoLineaHasta(const std::shared_ptr<Ecf31IdDoc_totalPaginas>& value)
{
    m_NoLineaHasta = value;
    m_NoLineaHastaIsSet = true;
}

bool Ecf41Pagina::noLineaHastaIsSet() const
{
    return m_NoLineaHastaIsSet;
}

void Ecf41Pagina::unsetNoLineaHasta()
{
    m_NoLineaHastaIsSet = false;
}
std::shared_ptr<Ecf31DescuentoORecargo_montoDescuentooRecargo> Ecf41Pagina::getSubtotalMontoGravadoPagina() const
{
    return m_SubtotalMontoGravadoPagina;
}


void Ecf41Pagina::setSubtotalMontoGravadoPagina(const std::shared_ptr<Ecf31DescuentoORecargo_montoDescuentooRecargo>& value)
{
    m_SubtotalMontoGravadoPagina = value;
    m_SubtotalMontoGravadoPaginaIsSet = true;
}

bool Ecf41Pagina::subtotalMontoGravadoPaginaIsSet() const
{
    return m_SubtotalMontoGravadoPaginaIsSet;
}

void Ecf41Pagina::unsetSubtotalMontoGravadoPagina()
{
    m_SubtotalMontoGravadoPaginaIsSet = false;
}
std::shared_ptr<Ecf31DescuentoORecargo_montoDescuentooRecargo> Ecf41Pagina::getSubtotalMontoGravado1Pagina() const
{
    return m_SubtotalMontoGravado1Pagina;
}


void Ecf41Pagina::setSubtotalMontoGravado1Pagina(const std::shared_ptr<Ecf31DescuentoORecargo_montoDescuentooRecargo>& value)
{
    m_SubtotalMontoGravado1Pagina = value;
    m_SubtotalMontoGravado1PaginaIsSet = true;
}

bool Ecf41Pagina::subtotalMontoGravado1PaginaIsSet() const
{
    return m_SubtotalMontoGravado1PaginaIsSet;
}

void Ecf41Pagina::unsetSubtotalMontoGravado1Pagina()
{
    m_SubtotalMontoGravado1PaginaIsSet = false;
}
std::shared_ptr<Ecf31DescuentoORecargo_montoDescuentooRecargo> Ecf41Pagina::getSubtotalMontoGravado2Pagina() const
{
    return m_SubtotalMontoGravado2Pagina;
}


void Ecf41Pagina::setSubtotalMontoGravado2Pagina(const std::shared_ptr<Ecf31DescuentoORecargo_montoDescuentooRecargo>& value)
{
    m_SubtotalMontoGravado2Pagina = value;
    m_SubtotalMontoGravado2PaginaIsSet = true;
}

bool Ecf41Pagina::subtotalMontoGravado2PaginaIsSet() const
{
    return m_SubtotalMontoGravado2PaginaIsSet;
}

void Ecf41Pagina::unsetSubtotalMontoGravado2Pagina()
{
    m_SubtotalMontoGravado2PaginaIsSet = false;
}
std::shared_ptr<Ecf31DescuentoORecargo_montoDescuentooRecargo> Ecf41Pagina::getSubtotalMontoGravado3Pagina() const
{
    return m_SubtotalMontoGravado3Pagina;
}


void Ecf41Pagina::setSubtotalMontoGravado3Pagina(const std::shared_ptr<Ecf31DescuentoORecargo_montoDescuentooRecargo>& value)
{
    m_SubtotalMontoGravado3Pagina = value;
    m_SubtotalMontoGravado3PaginaIsSet = true;
}

bool Ecf41Pagina::subtotalMontoGravado3PaginaIsSet() const
{
    return m_SubtotalMontoGravado3PaginaIsSet;
}

void Ecf41Pagina::unsetSubtotalMontoGravado3Pagina()
{
    m_SubtotalMontoGravado3PaginaIsSet = false;
}
std::shared_ptr<Ecf31DescuentoORecargo_montoDescuentooRecargo> Ecf41Pagina::getSubtotalExentoPagina() const
{
    return m_SubtotalExentoPagina;
}


void Ecf41Pagina::setSubtotalExentoPagina(const std::shared_ptr<Ecf31DescuentoORecargo_montoDescuentooRecargo>& value)
{
    m_SubtotalExentoPagina = value;
    m_SubtotalExentoPaginaIsSet = true;
}

bool Ecf41Pagina::subtotalExentoPaginaIsSet() const
{
    return m_SubtotalExentoPaginaIsSet;
}

void Ecf41Pagina::unsetSubtotalExentoPagina()
{
    m_SubtotalExentoPaginaIsSet = false;
}
std::shared_ptr<Ecf31DescuentoORecargo_montoDescuentooRecargo> Ecf41Pagina::getSubtotalItbisPagina() const
{
    return m_SubtotalItbisPagina;
}


void Ecf41Pagina::setSubtotalItbisPagina(const std::shared_ptr<Ecf31DescuentoORecargo_montoDescuentooRecargo>& value)
{
    m_SubtotalItbisPagina = value;
    m_SubtotalItbisPaginaIsSet = true;
}

bool Ecf41Pagina::subtotalItbisPaginaIsSet() const
{
    return m_SubtotalItbisPaginaIsSet;
}

void Ecf41Pagina::unsetSubtotalItbisPagina()
{
    m_SubtotalItbisPaginaIsSet = false;
}
std::shared_ptr<Ecf31DescuentoORecargo_montoDescuentooRecargo> Ecf41Pagina::getSubtotalItbis1Pagina() const
{
    return m_SubtotalItbis1Pagina;
}


void Ecf41Pagina::setSubtotalItbis1Pagina(const std::shared_ptr<Ecf31DescuentoORecargo_montoDescuentooRecargo>& value)
{
    m_SubtotalItbis1Pagina = value;
    m_SubtotalItbis1PaginaIsSet = true;
}

bool Ecf41Pagina::subtotalItbis1PaginaIsSet() const
{
    return m_SubtotalItbis1PaginaIsSet;
}

void Ecf41Pagina::unsetSubtotalItbis1Pagina()
{
    m_SubtotalItbis1PaginaIsSet = false;
}
std::shared_ptr<Ecf31DescuentoORecargo_montoDescuentooRecargo> Ecf41Pagina::getSubtotalItbis2Pagina() const
{
    return m_SubtotalItbis2Pagina;
}


void Ecf41Pagina::setSubtotalItbis2Pagina(const std::shared_ptr<Ecf31DescuentoORecargo_montoDescuentooRecargo>& value)
{
    m_SubtotalItbis2Pagina = value;
    m_SubtotalItbis2PaginaIsSet = true;
}

bool Ecf41Pagina::subtotalItbis2PaginaIsSet() const
{
    return m_SubtotalItbis2PaginaIsSet;
}

void Ecf41Pagina::unsetSubtotalItbis2Pagina()
{
    m_SubtotalItbis2PaginaIsSet = false;
}
std::shared_ptr<Ecf31DescuentoORecargo_montoDescuentooRecargo> Ecf41Pagina::getSubtotalItbis3Pagina() const
{
    return m_SubtotalItbis3Pagina;
}


void Ecf41Pagina::setSubtotalItbis3Pagina(const std::shared_ptr<Ecf31DescuentoORecargo_montoDescuentooRecargo>& value)
{
    m_SubtotalItbis3Pagina = value;
    m_SubtotalItbis3PaginaIsSet = true;
}

bool Ecf41Pagina::subtotalItbis3PaginaIsSet() const
{
    return m_SubtotalItbis3PaginaIsSet;
}

void Ecf41Pagina::unsetSubtotalItbis3Pagina()
{
    m_SubtotalItbis3PaginaIsSet = false;
}
std::shared_ptr<Ecf31DescuentoORecargo_montoDescuentooRecargo> Ecf41Pagina::getMontoSubtotalPagina() const
{
    return m_MontoSubtotalPagina;
}


void Ecf41Pagina::setMontoSubtotalPagina(const std::shared_ptr<Ecf31DescuentoORecargo_montoDescuentooRecargo>& value)
{
    m_MontoSubtotalPagina = value;
    m_MontoSubtotalPaginaIsSet = true;
}

bool Ecf41Pagina::montoSubtotalPaginaIsSet() const
{
    return m_MontoSubtotalPaginaIsSet;
}

void Ecf41Pagina::unsetMontoSubtotalPagina()
{
    m_MontoSubtotalPaginaIsSet = false;
}

}
}
}
}


