/**
 * ECF API
 * ECF API (Electronic Fiscal Receipt).
 *
 * The version of the OpenAPI document: v1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.20.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "ecf-dgii-client/model/Ecf44ImpuestoAdicional2.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

Ecf44ImpuestoAdicional2::Ecf44ImpuestoAdicional2()
{
    m_TipoImpuestoIsSet = false;
    m_TasaImpuestoAdicionalIsSet = false;
    m_OtrosImpuestosAdicionalesIsSet = false;
}

Ecf44ImpuestoAdicional2::~Ecf44ImpuestoAdicional2()
{
}

void Ecf44ImpuestoAdicional2::validate()
{
    // TODO: implement validation
}

web::json::value Ecf44ImpuestoAdicional2::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_TipoImpuestoIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("tipoImpuesto"))] = ModelBase::toJson(m_TipoImpuesto);
    }
    if(m_TasaImpuestoAdicionalIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("tasaImpuestoAdicional"))] = ModelBase::toJson(m_TasaImpuestoAdicional);
    }
    if(m_OtrosImpuestosAdicionalesIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("otrosImpuestosAdicionales"))] = ModelBase::toJson(m_OtrosImpuestosAdicionales);
    }

    return val;
}

bool Ecf44ImpuestoAdicional2::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("tipoImpuesto"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("tipoImpuesto")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<Ecf44CodificacionTipoImpuestosType> refVal_setTipoImpuesto;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTipoImpuesto);
            setTipoImpuesto(refVal_setTipoImpuesto);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("tasaImpuestoAdicional"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("tasaImpuestoAdicional")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<Ecf31ImpuestoAdicional2_tasaImpuestoAdicional> refVal_setTasaImpuestoAdicional;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTasaImpuestoAdicional);
            setTasaImpuestoAdicional(refVal_setTasaImpuestoAdicional);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("otrosImpuestosAdicionales"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("otrosImpuestosAdicionales")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<Ecf31Item_cantidadItem> refVal_setOtrosImpuestosAdicionales;
            ok &= ModelBase::fromJson(fieldValue, refVal_setOtrosImpuestosAdicionales);
            setOtrosImpuestosAdicionales(refVal_setOtrosImpuestosAdicionales);
            
        }
    }
    return ok;
}

void Ecf44ImpuestoAdicional2::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_TipoImpuestoIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("tipoImpuesto")), m_TipoImpuesto));
    }
    if(m_TasaImpuestoAdicionalIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("tasaImpuestoAdicional")), m_TasaImpuestoAdicional));
    }
    if(m_OtrosImpuestosAdicionalesIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("otrosImpuestosAdicionales")), m_OtrosImpuestosAdicionales));
    }
}

bool Ecf44ImpuestoAdicional2::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("tipoImpuesto"))))
    {
        std::shared_ptr<Ecf44CodificacionTipoImpuestosType> refVal_setTipoImpuesto;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("tipoImpuesto"))), refVal_setTipoImpuesto );
        setTipoImpuesto(refVal_setTipoImpuesto);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("tasaImpuestoAdicional"))))
    {
        std::shared_ptr<Ecf31ImpuestoAdicional2_tasaImpuestoAdicional> refVal_setTasaImpuestoAdicional;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("tasaImpuestoAdicional"))), refVal_setTasaImpuestoAdicional );
        setTasaImpuestoAdicional(refVal_setTasaImpuestoAdicional);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("otrosImpuestosAdicionales"))))
    {
        std::shared_ptr<Ecf31Item_cantidadItem> refVal_setOtrosImpuestosAdicionales;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("otrosImpuestosAdicionales"))), refVal_setOtrosImpuestosAdicionales );
        setOtrosImpuestosAdicionales(refVal_setOtrosImpuestosAdicionales);
    }
    return ok;
}


std::shared_ptr<Ecf44CodificacionTipoImpuestosType> Ecf44ImpuestoAdicional2::getTipoImpuesto() const
{
    return m_TipoImpuesto;
}


void Ecf44ImpuestoAdicional2::setTipoImpuesto(const std::shared_ptr<Ecf44CodificacionTipoImpuestosType>& value)
{
    m_TipoImpuesto = value;
    m_TipoImpuestoIsSet = true;
}

bool Ecf44ImpuestoAdicional2::tipoImpuestoIsSet() const
{
    return m_TipoImpuestoIsSet;
}

void Ecf44ImpuestoAdicional2::unsetTipoImpuesto()
{
    m_TipoImpuestoIsSet = false;
}
std::shared_ptr<Ecf31ImpuestoAdicional2_tasaImpuestoAdicional> Ecf44ImpuestoAdicional2::getTasaImpuestoAdicional() const
{
    return m_TasaImpuestoAdicional;
}


void Ecf44ImpuestoAdicional2::setTasaImpuestoAdicional(const std::shared_ptr<Ecf31ImpuestoAdicional2_tasaImpuestoAdicional>& value)
{
    m_TasaImpuestoAdicional = value;
    m_TasaImpuestoAdicionalIsSet = true;
}

bool Ecf44ImpuestoAdicional2::tasaImpuestoAdicionalIsSet() const
{
    return m_TasaImpuestoAdicionalIsSet;
}

void Ecf44ImpuestoAdicional2::unsetTasaImpuestoAdicional()
{
    m_TasaImpuestoAdicionalIsSet = false;
}
std::shared_ptr<Ecf31Item_cantidadItem> Ecf44ImpuestoAdicional2::getOtrosImpuestosAdicionales() const
{
    return m_OtrosImpuestosAdicionales;
}


void Ecf44ImpuestoAdicional2::setOtrosImpuestosAdicionales(const std::shared_ptr<Ecf31Item_cantidadItem>& value)
{
    m_OtrosImpuestosAdicionales = value;
    m_OtrosImpuestosAdicionalesIsSet = true;
}

bool Ecf44ImpuestoAdicional2::otrosImpuestosAdicionalesIsSet() const
{
    return m_OtrosImpuestosAdicionalesIsSet;
}

void Ecf44ImpuestoAdicional2::unsetOtrosImpuestosAdicionales()
{
    m_OtrosImpuestosAdicionalesIsSet = false;
}

}
}
}
}


