/**
 * ECF API
 * ECF API (Electronic Fiscal Receipt).
 *
 * The version of the OpenAPI document: v1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.20.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "ecf-dgii-client/model/Ecf45IdDoc.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

Ecf45IdDoc::Ecf45IdDoc()
{
    m_TipoeCFIsSet = false;
    m_Encf = utility::conversions::to_string_t("");
    m_EncfIsSet = false;
    m_FechaVencimientoSecuencia = utility::datetime();
    m_FechaVencimientoSecuenciaIsSet = false;
    m_TipoIngresosIsSet = false;
    m_TipoPagoIsSet = false;
}

Ecf45IdDoc::~Ecf45IdDoc()
{
}

void Ecf45IdDoc::validate()
{
    // TODO: implement validation
}

web::json::value Ecf45IdDoc::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_TipoeCFIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("tipoeCF"))] = ModelBase::toJson(m_TipoeCF);
    }
    if(m_EncfIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("encf"))] = ModelBase::toJson(m_Encf);
    }
    if(m_FechaVencimientoSecuenciaIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("fechaVencimientoSecuencia"))] = ModelBase::toJson(m_FechaVencimientoSecuencia);
    }
    if(m_IndicadorEnvioDiferido.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("indicadorEnvioDiferido"))] = ModelBase::toJson(m_IndicadorEnvioDiferido.get());
    }
    if(m_IndicadorMontoGravado.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("indicadorMontoGravado"))] = ModelBase::toJson(m_IndicadorMontoGravado.get());
    }
    if(m_IndicadorServicioTodoIncluido.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("indicadorServicioTodoIncluido"))] = ModelBase::toJson(m_IndicadorServicioTodoIncluido.get());
    }
    if(m_TipoIngresosIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("tipoIngresos"))] = ModelBase::toJson(m_TipoIngresos);
    }
    if(m_TipoPagoIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("tipoPago"))] = ModelBase::toJson(m_TipoPago);
    }
    if(m_FechaLimitePago.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("fechaLimitePago"))] = ModelBase::toJson(m_FechaLimitePago.get());
    }
    if(m_TerminoPago.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("terminoPago"))] = ModelBase::toJson(m_TerminoPago.get());
    }
    if(m_TablaFormasPago.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("tablaFormasPago"))] = ModelBase::toJson(m_TablaFormasPago.get());
    }
    if(m_TipoCuentaPago.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("tipoCuentaPago"))] = ModelBase::toJson(m_TipoCuentaPago.get());
    }
    if(m_NumeroCuentaPago.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("numeroCuentaPago"))] = ModelBase::toJson(m_NumeroCuentaPago.get());
    }
    if(m_BancoPago.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("bancoPago"))] = ModelBase::toJson(m_BancoPago.get());
    }
    if(m_FechaDesde.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("fechaDesde"))] = ModelBase::toJson(m_FechaDesde.get());
    }
    if(m_FechaHasta.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("fechaHasta"))] = ModelBase::toJson(m_FechaHasta.get());
    }
    if(m_TotalPaginas.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("totalPaginas"))] = ModelBase::toJson(m_TotalPaginas.get());
    }

    return val;
}

bool Ecf45IdDoc::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("tipoeCF"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("tipoeCF")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<TipoeCFType> refVal_setTipoeCF;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTipoeCF);
            setTipoeCF(refVal_setTipoeCF);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("encf"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("encf")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setEncf;
            ok &= ModelBase::fromJson(fieldValue, refVal_setEncf);
            setEncf(refVal_setEncf);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("fechaVencimientoSecuencia"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("fechaVencimientoSecuencia")));
        if(!fieldValue.is_null())
        {
            utility::datetime refVal_setFechaVencimientoSecuencia;
            ok &= ModelBase::fromJson(fieldValue, refVal_setFechaVencimientoSecuencia);
            setFechaVencimientoSecuencia(refVal_setFechaVencimientoSecuencia);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("indicadorEnvioDiferido"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("indicadorEnvioDiferido")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<IndicadorEnvioDiferidoType> refVal_setIndicadorEnvioDiferido;
            ok &= ModelBase::fromJson(fieldValue, refVal_setIndicadorEnvioDiferido);
            setIndicadorEnvioDiferido(refVal_setIndicadorEnvioDiferido);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("indicadorMontoGravado"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("indicadorMontoGravado")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<IndicadorMontoGravadoType> refVal_setIndicadorMontoGravado;
            ok &= ModelBase::fromJson(fieldValue, refVal_setIndicadorMontoGravado);
            setIndicadorMontoGravado(refVal_setIndicadorMontoGravado);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("indicadorServicioTodoIncluido"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("indicadorServicioTodoIncluido")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<IndicadorServicioTodoIncluidoType> refVal_setIndicadorServicioTodoIncluido;
            ok &= ModelBase::fromJson(fieldValue, refVal_setIndicadorServicioTodoIncluido);
            setIndicadorServicioTodoIncluido(refVal_setIndicadorServicioTodoIncluido);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("tipoIngresos"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("tipoIngresos")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<Ecf45TipoIngresosValidationType> refVal_setTipoIngresos;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTipoIngresos);
            setTipoIngresos(refVal_setTipoIngresos);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("tipoPago"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("tipoPago")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<Ecf45TipoPagoType> refVal_setTipoPago;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTipoPago);
            setTipoPago(refVal_setTipoPago);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("fechaLimitePago"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("fechaLimitePago")));
        if(!fieldValue.is_null())
        {
            utility::datetime refVal_setFechaLimitePago;
            ok &= ModelBase::fromJson(fieldValue, refVal_setFechaLimitePago);
            setFechaLimitePago(refVal_setFechaLimitePago);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("terminoPago"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("terminoPago")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setTerminoPago;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTerminoPago);
            setTerminoPago(refVal_setTerminoPago);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("tablaFormasPago"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("tablaFormasPago")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<Ecf45FormaDePago>> refVal_setTablaFormasPago;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTablaFormasPago);
            setTablaFormasPago(refVal_setTablaFormasPago);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("tipoCuentaPago"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("tipoCuentaPago")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<TipoCuentaPagoType> refVal_setTipoCuentaPago;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTipoCuentaPago);
            setTipoCuentaPago(refVal_setTipoCuentaPago);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("numeroCuentaPago"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("numeroCuentaPago")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setNumeroCuentaPago;
            ok &= ModelBase::fromJson(fieldValue, refVal_setNumeroCuentaPago);
            setNumeroCuentaPago(refVal_setNumeroCuentaPago);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("bancoPago"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("bancoPago")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setBancoPago;
            ok &= ModelBase::fromJson(fieldValue, refVal_setBancoPago);
            setBancoPago(refVal_setBancoPago);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("fechaDesde"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("fechaDesde")));
        if(!fieldValue.is_null())
        {
            utility::datetime refVal_setFechaDesde;
            ok &= ModelBase::fromJson(fieldValue, refVal_setFechaDesde);
            setFechaDesde(refVal_setFechaDesde);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("fechaHasta"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("fechaHasta")));
        if(!fieldValue.is_null())
        {
            utility::datetime refVal_setFechaHasta;
            ok &= ModelBase::fromJson(fieldValue, refVal_setFechaHasta);
            setFechaHasta(refVal_setFechaHasta);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("totalPaginas"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("totalPaginas")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<Ecf31IdDoc_totalPaginas> refVal_setTotalPaginas;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTotalPaginas);
            setTotalPaginas(refVal_setTotalPaginas);
            
        }
    }
    return ok;
}

void Ecf45IdDoc::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_TipoeCFIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("tipoeCF")), m_TipoeCF));
    }
    if(m_EncfIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("encf")), m_Encf));
    }
    if(m_FechaVencimientoSecuenciaIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("fechaVencimientoSecuencia")), m_FechaVencimientoSecuencia));
    }
    if(m_IndicadorEnvioDiferido.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("indicadorEnvioDiferido")), m_IndicadorEnvioDiferido.get()));
    }
    if(m_IndicadorMontoGravado.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("indicadorMontoGravado")), m_IndicadorMontoGravado.get()));
    }
    if(m_IndicadorServicioTodoIncluido.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("indicadorServicioTodoIncluido")), m_IndicadorServicioTodoIncluido.get()));
    }
    if(m_TipoIngresosIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("tipoIngresos")), m_TipoIngresos));
    }
    if(m_TipoPagoIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("tipoPago")), m_TipoPago));
    }
    if(m_FechaLimitePago.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("fechaLimitePago")), m_FechaLimitePago.get()));
    }
    if(m_TerminoPago.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("terminoPago")), m_TerminoPago.get()));
    }
    if(m_TablaFormasPago.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("tablaFormasPago")), m_TablaFormasPago.get()));
    }
    if(m_TipoCuentaPago.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("tipoCuentaPago")), m_TipoCuentaPago.get()));
    }
    if(m_NumeroCuentaPago.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("numeroCuentaPago")), m_NumeroCuentaPago.get()));
    }
    if(m_BancoPago.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("bancoPago")), m_BancoPago.get()));
    }
    if(m_FechaDesde.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("fechaDesde")), m_FechaDesde.get()));
    }
    if(m_FechaHasta.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("fechaHasta")), m_FechaHasta.get()));
    }
    if(m_TotalPaginas.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("totalPaginas")), m_TotalPaginas.get()));
    }
}

bool Ecf45IdDoc::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("tipoeCF"))))
    {
        std::shared_ptr<TipoeCFType> refVal_setTipoeCF;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("tipoeCF"))), refVal_setTipoeCF );
        setTipoeCF(refVal_setTipoeCF);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("encf"))))
    {
        utility::string_t refVal_setEncf;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("encf"))), refVal_setEncf );
        setEncf(refVal_setEncf);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("fechaVencimientoSecuencia"))))
    {
        utility::datetime refVal_setFechaVencimientoSecuencia;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("fechaVencimientoSecuencia"))), refVal_setFechaVencimientoSecuencia );
        setFechaVencimientoSecuencia(refVal_setFechaVencimientoSecuencia);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("indicadorEnvioDiferido"))))
    {
        std::shared_ptr<IndicadorEnvioDiferidoType> refVal_setIndicadorEnvioDiferido;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("indicadorEnvioDiferido"))), refVal_setIndicadorEnvioDiferido );
        setIndicadorEnvioDiferido(refVal_setIndicadorEnvioDiferido);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("indicadorMontoGravado"))))
    {
        std::shared_ptr<IndicadorMontoGravadoType> refVal_setIndicadorMontoGravado;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("indicadorMontoGravado"))), refVal_setIndicadorMontoGravado );
        setIndicadorMontoGravado(refVal_setIndicadorMontoGravado);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("indicadorServicioTodoIncluido"))))
    {
        std::shared_ptr<IndicadorServicioTodoIncluidoType> refVal_setIndicadorServicioTodoIncluido;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("indicadorServicioTodoIncluido"))), refVal_setIndicadorServicioTodoIncluido );
        setIndicadorServicioTodoIncluido(refVal_setIndicadorServicioTodoIncluido);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("tipoIngresos"))))
    {
        std::shared_ptr<Ecf45TipoIngresosValidationType> refVal_setTipoIngresos;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("tipoIngresos"))), refVal_setTipoIngresos );
        setTipoIngresos(refVal_setTipoIngresos);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("tipoPago"))))
    {
        std::shared_ptr<Ecf45TipoPagoType> refVal_setTipoPago;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("tipoPago"))), refVal_setTipoPago );
        setTipoPago(refVal_setTipoPago);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("fechaLimitePago"))))
    {
        utility::datetime refVal_setFechaLimitePago;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("fechaLimitePago"))), refVal_setFechaLimitePago );
        setFechaLimitePago(refVal_setFechaLimitePago);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("terminoPago"))))
    {
        utility::string_t refVal_setTerminoPago;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("terminoPago"))), refVal_setTerminoPago );
        setTerminoPago(refVal_setTerminoPago);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("tablaFormasPago"))))
    {
        std::vector<std::shared_ptr<Ecf45FormaDePago>> refVal_setTablaFormasPago;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("tablaFormasPago"))), refVal_setTablaFormasPago );
        setTablaFormasPago(refVal_setTablaFormasPago);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("tipoCuentaPago"))))
    {
        std::shared_ptr<TipoCuentaPagoType> refVal_setTipoCuentaPago;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("tipoCuentaPago"))), refVal_setTipoCuentaPago );
        setTipoCuentaPago(refVal_setTipoCuentaPago);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("numeroCuentaPago"))))
    {
        utility::string_t refVal_setNumeroCuentaPago;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("numeroCuentaPago"))), refVal_setNumeroCuentaPago );
        setNumeroCuentaPago(refVal_setNumeroCuentaPago);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("bancoPago"))))
    {
        utility::string_t refVal_setBancoPago;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("bancoPago"))), refVal_setBancoPago );
        setBancoPago(refVal_setBancoPago);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("fechaDesde"))))
    {
        utility::datetime refVal_setFechaDesde;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("fechaDesde"))), refVal_setFechaDesde );
        setFechaDesde(refVal_setFechaDesde);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("fechaHasta"))))
    {
        utility::datetime refVal_setFechaHasta;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("fechaHasta"))), refVal_setFechaHasta );
        setFechaHasta(refVal_setFechaHasta);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("totalPaginas"))))
    {
        std::shared_ptr<Ecf31IdDoc_totalPaginas> refVal_setTotalPaginas;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("totalPaginas"))), refVal_setTotalPaginas );
        setTotalPaginas(refVal_setTotalPaginas);
    }
    return ok;
}


std::shared_ptr<TipoeCFType> Ecf45IdDoc::getTipoeCF() const
{
    return m_TipoeCF;
}


void Ecf45IdDoc::setTipoeCF(const std::shared_ptr<TipoeCFType>& value)
{
    m_TipoeCF = value;
    m_TipoeCFIsSet = true;
}

bool Ecf45IdDoc::tipoeCFIsSet() const
{
    return m_TipoeCFIsSet;
}

void Ecf45IdDoc::unsetTipoeCF()
{
    m_TipoeCFIsSet = false;
}
utility::string_t Ecf45IdDoc::getEncf() const
{
    return m_Encf;
}


void Ecf45IdDoc::setEncf(const utility::string_t& value)
{
    m_Encf = value;
    m_EncfIsSet = true;
}

bool Ecf45IdDoc::encfIsSet() const
{
    return m_EncfIsSet;
}

void Ecf45IdDoc::unsetEncf()
{
    m_EncfIsSet = false;
}
utility::datetime Ecf45IdDoc::getFechaVencimientoSecuencia() const
{
    return m_FechaVencimientoSecuencia;
}


void Ecf45IdDoc::setFechaVencimientoSecuencia(const utility::datetime& value)
{
    m_FechaVencimientoSecuencia = value;
    m_FechaVencimientoSecuenciaIsSet = true;
}

bool Ecf45IdDoc::fechaVencimientoSecuenciaIsSet() const
{
    return m_FechaVencimientoSecuenciaIsSet;
}

void Ecf45IdDoc::unsetFechaVencimientoSecuencia()
{
    m_FechaVencimientoSecuenciaIsSet = false;
}
std::shared_ptr<IndicadorEnvioDiferidoType> Ecf45IdDoc::getIndicadorEnvioDiferido() const
{
    return m_IndicadorEnvioDiferido.get();
}


void Ecf45IdDoc::setIndicadorEnvioDiferido(const std::shared_ptr<IndicadorEnvioDiferidoType>& value)
{
    m_IndicadorEnvioDiferido = value;
}

bool Ecf45IdDoc::indicadorEnvioDiferidoIsSet() const
{
    return m_IndicadorEnvioDiferido.has_value();
}

void Ecf45IdDoc::unsetIndicadorEnvioDiferido()
{
    m_IndicadorEnvioDiferido.reset();
}
std::shared_ptr<IndicadorMontoGravadoType> Ecf45IdDoc::getIndicadorMontoGravado() const
{
    return m_IndicadorMontoGravado.get();
}


void Ecf45IdDoc::setIndicadorMontoGravado(const std::shared_ptr<IndicadorMontoGravadoType>& value)
{
    m_IndicadorMontoGravado = value;
}

bool Ecf45IdDoc::indicadorMontoGravadoIsSet() const
{
    return m_IndicadorMontoGravado.has_value();
}

void Ecf45IdDoc::unsetIndicadorMontoGravado()
{
    m_IndicadorMontoGravado.reset();
}
std::shared_ptr<IndicadorServicioTodoIncluidoType> Ecf45IdDoc::getIndicadorServicioTodoIncluido() const
{
    return m_IndicadorServicioTodoIncluido.get();
}


void Ecf45IdDoc::setIndicadorServicioTodoIncluido(const std::shared_ptr<IndicadorServicioTodoIncluidoType>& value)
{
    m_IndicadorServicioTodoIncluido = value;
}

bool Ecf45IdDoc::indicadorServicioTodoIncluidoIsSet() const
{
    return m_IndicadorServicioTodoIncluido.has_value();
}

void Ecf45IdDoc::unsetIndicadorServicioTodoIncluido()
{
    m_IndicadorServicioTodoIncluido.reset();
}
std::shared_ptr<Ecf45TipoIngresosValidationType> Ecf45IdDoc::getTipoIngresos() const
{
    return m_TipoIngresos;
}


void Ecf45IdDoc::setTipoIngresos(const std::shared_ptr<Ecf45TipoIngresosValidationType>& value)
{
    m_TipoIngresos = value;
    m_TipoIngresosIsSet = true;
}

bool Ecf45IdDoc::tipoIngresosIsSet() const
{
    return m_TipoIngresosIsSet;
}

void Ecf45IdDoc::unsetTipoIngresos()
{
    m_TipoIngresosIsSet = false;
}
std::shared_ptr<Ecf45TipoPagoType> Ecf45IdDoc::getTipoPago() const
{
    return m_TipoPago;
}


void Ecf45IdDoc::setTipoPago(const std::shared_ptr<Ecf45TipoPagoType>& value)
{
    m_TipoPago = value;
    m_TipoPagoIsSet = true;
}

bool Ecf45IdDoc::tipoPagoIsSet() const
{
    return m_TipoPagoIsSet;
}

void Ecf45IdDoc::unsetTipoPago()
{
    m_TipoPagoIsSet = false;
}
utility::datetime Ecf45IdDoc::getFechaLimitePago() const
{
    return m_FechaLimitePago.get();
}


void Ecf45IdDoc::setFechaLimitePago(const utility::datetime& value)
{
    m_FechaLimitePago = value;
}

bool Ecf45IdDoc::fechaLimitePagoIsSet() const
{
    return m_FechaLimitePago.has_value();
}

void Ecf45IdDoc::unsetFechaLimitePago()
{
    m_FechaLimitePago.reset();
}
utility::string_t Ecf45IdDoc::getTerminoPago() const
{
    return m_TerminoPago.get();
}


void Ecf45IdDoc::setTerminoPago(const utility::string_t& value)
{
    m_TerminoPago = value;
}

bool Ecf45IdDoc::terminoPagoIsSet() const
{
    return m_TerminoPago.has_value();
}

void Ecf45IdDoc::unsetTerminoPago()
{
    m_TerminoPago.reset();
}
std::vector<std::shared_ptr<Ecf45FormaDePago>> Ecf45IdDoc::getTablaFormasPago() const
{
    return m_TablaFormasPago.get();
}


void Ecf45IdDoc::setTablaFormasPago(const std::vector<std::shared_ptr<Ecf45FormaDePago>>& value)
{
    m_TablaFormasPago = value;
}

bool Ecf45IdDoc::tablaFormasPagoIsSet() const
{
    return m_TablaFormasPago.has_value();
}

void Ecf45IdDoc::unsetTablaFormasPago()
{
    m_TablaFormasPago.reset();
}
std::shared_ptr<TipoCuentaPagoType> Ecf45IdDoc::getTipoCuentaPago() const
{
    return m_TipoCuentaPago.get();
}


void Ecf45IdDoc::setTipoCuentaPago(const std::shared_ptr<TipoCuentaPagoType>& value)
{
    m_TipoCuentaPago = value;
}

bool Ecf45IdDoc::tipoCuentaPagoIsSet() const
{
    return m_TipoCuentaPago.has_value();
}

void Ecf45IdDoc::unsetTipoCuentaPago()
{
    m_TipoCuentaPago.reset();
}
utility::string_t Ecf45IdDoc::getNumeroCuentaPago() const
{
    return m_NumeroCuentaPago.get();
}


void Ecf45IdDoc::setNumeroCuentaPago(const utility::string_t& value)
{
    m_NumeroCuentaPago = value;
}

bool Ecf45IdDoc::numeroCuentaPagoIsSet() const
{
    return m_NumeroCuentaPago.has_value();
}

void Ecf45IdDoc::unsetNumeroCuentaPago()
{
    m_NumeroCuentaPago.reset();
}
utility::string_t Ecf45IdDoc::getBancoPago() const
{
    return m_BancoPago.get();
}


void Ecf45IdDoc::setBancoPago(const utility::string_t& value)
{
    m_BancoPago = value;
}

bool Ecf45IdDoc::bancoPagoIsSet() const
{
    return m_BancoPago.has_value();
}

void Ecf45IdDoc::unsetBancoPago()
{
    m_BancoPago.reset();
}
utility::datetime Ecf45IdDoc::getFechaDesde() const
{
    return m_FechaDesde.get();
}


void Ecf45IdDoc::setFechaDesde(const utility::datetime& value)
{
    m_FechaDesde = value;
}

bool Ecf45IdDoc::fechaDesdeIsSet() const
{
    return m_FechaDesde.has_value();
}

void Ecf45IdDoc::unsetFechaDesde()
{
    m_FechaDesde.reset();
}
utility::datetime Ecf45IdDoc::getFechaHasta() const
{
    return m_FechaHasta.get();
}


void Ecf45IdDoc::setFechaHasta(const utility::datetime& value)
{
    m_FechaHasta = value;
}

bool Ecf45IdDoc::fechaHastaIsSet() const
{
    return m_FechaHasta.has_value();
}

void Ecf45IdDoc::unsetFechaHasta()
{
    m_FechaHasta.reset();
}
std::shared_ptr<Ecf31IdDoc_totalPaginas> Ecf45IdDoc::getTotalPaginas() const
{
    return m_TotalPaginas.get();
}


void Ecf45IdDoc::setTotalPaginas(const std::shared_ptr<Ecf31IdDoc_totalPaginas>& value)
{
    m_TotalPaginas = value;
}

bool Ecf45IdDoc::totalPaginasIsSet() const
{
    return m_TotalPaginas.has_value();
}

void Ecf45IdDoc::unsetTotalPaginas()
{
    m_TotalPaginas.reset();
}

}
}
}
}


