/**
 * ECF API
 * ECF API (Electronic Fiscal Receipt).
 *
 * The version of the OpenAPI document: v1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.20.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "ecf-dgii-client/model/Ecf45FormaPagoType.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

namespace
{
using EnumUnderlyingType = utility::string_t;

Ecf45FormaPagoType::eEcf45FormaPagoType toEnum(const EnumUnderlyingType& val)
{
    if (val == utility::conversions::to_string_t(_XPLATSTR("Efectivo")))
        return Ecf45FormaPagoType::eEcf45FormaPagoType::EFECTIVO;
    if (val == utility::conversions::to_string_t(_XPLATSTR("ChequeSlashTransferenciaSlashDeposito")))
        return Ecf45FormaPagoType::eEcf45FormaPagoType::CHEQUESLASHTRANSFERENCIASLASHDEPOSITO;
    if (val == utility::conversions::to_string_t(_XPLATSTR("TarjetaDeDebitoSlashCredito")))
        return Ecf45FormaPagoType::eEcf45FormaPagoType::TARJETADEDEBITOSLASHCREDITO;
    if (val == utility::conversions::to_string_t(_XPLATSTR("VentaACredito")))
        return Ecf45FormaPagoType::eEcf45FormaPagoType::VENTAACREDITO;
    if (val == utility::conversions::to_string_t(_XPLATSTR("BonosOCertificadosDeRegalo")))
        return Ecf45FormaPagoType::eEcf45FormaPagoType::BONOSOCERTIFICADOSDEREGALO;
    if (val == utility::conversions::to_string_t(_XPLATSTR("Permuta")))
        return Ecf45FormaPagoType::eEcf45FormaPagoType::PERMUTA;
    if (val == utility::conversions::to_string_t(_XPLATSTR("NotaDeCredito")))
        return Ecf45FormaPagoType::eEcf45FormaPagoType::NOTADECREDITO;
    if (val == utility::conversions::to_string_t(_XPLATSTR("OtrasFormasDePago")))
        return Ecf45FormaPagoType::eEcf45FormaPagoType::OTRASFORMASDEPAGO;
    return {};
}

EnumUnderlyingType fromEnum(Ecf45FormaPagoType::eEcf45FormaPagoType e)
{
    switch (e)
    {
    case Ecf45FormaPagoType::eEcf45FormaPagoType::EFECTIVO:
        return _XPLATSTR("Efectivo");
    case Ecf45FormaPagoType::eEcf45FormaPagoType::CHEQUESLASHTRANSFERENCIASLASHDEPOSITO:
        return _XPLATSTR("ChequeSlashTransferenciaSlashDeposito");
    case Ecf45FormaPagoType::eEcf45FormaPagoType::TARJETADEDEBITOSLASHCREDITO:
        return _XPLATSTR("TarjetaDeDebitoSlashCredito");
    case Ecf45FormaPagoType::eEcf45FormaPagoType::VENTAACREDITO:
        return _XPLATSTR("VentaACredito");
    case Ecf45FormaPagoType::eEcf45FormaPagoType::BONOSOCERTIFICADOSDEREGALO:
        return _XPLATSTR("BonosOCertificadosDeRegalo");
    case Ecf45FormaPagoType::eEcf45FormaPagoType::PERMUTA:
        return _XPLATSTR("Permuta");
    case Ecf45FormaPagoType::eEcf45FormaPagoType::NOTADECREDITO:
        return _XPLATSTR("NotaDeCredito");
    case Ecf45FormaPagoType::eEcf45FormaPagoType::OTRASFORMASDEPAGO:
        return _XPLATSTR("OtrasFormasDePago");
    default:
        break;
    }
    return {};
}
}

Ecf45FormaPagoType::Ecf45FormaPagoType()
{
}

Ecf45FormaPagoType::~Ecf45FormaPagoType()
{
}

void Ecf45FormaPagoType::validate()
{
    // TODO: implement validation
}

web::json::value Ecf45FormaPagoType::toJson() const
{
    auto val = fromEnum(m_value);
    return web::json::value(val);
}

bool Ecf45FormaPagoType::fromJson(const web::json::value& val)
{
    m_value = toEnum(val.as_string());
    return true;
}

void Ecf45FormaPagoType::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if (!namePrefix.empty() && namePrefix.back() != _XPLATSTR('.'))
    {
        namePrefix.push_back(_XPLATSTR('.'));
    }

    auto e = fromEnum(m_value);
    multipart->add(ModelBase::toHttpContent(namePrefix, e));
}

bool Ecf45FormaPagoType::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if (!namePrefix.empty() && namePrefix.back() != _XPLATSTR('.'))
    {
        namePrefix.push_back(_XPLATSTR('.'));
    }
    {
        EnumUnderlyingType e;
        ok = ModelBase::fromHttpContent(multipart->getContent(namePrefix), e);
        if (ok)
        {
            auto v = toEnum(e);
            setValue(v);
        }
    }
    return ok;
}

Ecf45FormaPagoType::eEcf45FormaPagoType Ecf45FormaPagoType::getValue() const
{
   return m_value;
}

void Ecf45FormaPagoType::setValue(Ecf45FormaPagoType::eEcf45FormaPagoType const value)
{
   m_value = value;
}

Ecf45FormaPagoType::Ecf45FormaPagoType(utility::string_t str){
    setValue( strToEnumMap[str] );
}

}
}
}
}


