/**
 * ECF API
 * ECF API (Electronic Fiscal Receipt).
 *
 * The version of the OpenAPI document: v1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.20.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "ecf-dgii-client/model/EcfProgress.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

namespace
{
using EnumUnderlyingType = utility::string_t;

EcfProgress::eEcfProgress toEnum(const EnumUnderlyingType& val)
{
    if (val == utility::conversions::to_string_t(_XPLATSTR("New")))
        return EcfProgress::eEcfProgress::NEW;
    if (val == utility::conversions::to_string_t(_XPLATSTR("Processing")))
        return EcfProgress::eEcfProgress::PROCESSING;
    if (val == utility::conversions::to_string_t(_XPLATSTR("UploadedToDgii")))
        return EcfProgress::eEcfProgress::UPLOADEDTODGII;
    if (val == utility::conversions::to_string_t(_XPLATSTR("Finished")))
        return EcfProgress::eEcfProgress::FINISHED;
    if (val == utility::conversions::to_string_t(_XPLATSTR("Error")))
        return EcfProgress::eEcfProgress::ERROR;
    return {};
}

EnumUnderlyingType fromEnum(EcfProgress::eEcfProgress e)
{
    switch (e)
    {
    case EcfProgress::eEcfProgress::NEW:
        return _XPLATSTR("New");
    case EcfProgress::eEcfProgress::PROCESSING:
        return _XPLATSTR("Processing");
    case EcfProgress::eEcfProgress::UPLOADEDTODGII:
        return _XPLATSTR("UploadedToDgii");
    case EcfProgress::eEcfProgress::FINISHED:
        return _XPLATSTR("Finished");
    case EcfProgress::eEcfProgress::ERROR:
        return _XPLATSTR("Error");
    default:
        break;
    }
    return {};
}
}

EcfProgress::EcfProgress()
{
}

EcfProgress::~EcfProgress()
{
}

void EcfProgress::validate()
{
    // TODO: implement validation
}

web::json::value EcfProgress::toJson() const
{
    auto val = fromEnum(m_value);
    return web::json::value(val);
}

bool EcfProgress::fromJson(const web::json::value& val)
{
    m_value = toEnum(val.as_string());
    return true;
}

void EcfProgress::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if (!namePrefix.empty() && namePrefix.back() != _XPLATSTR('.'))
    {
        namePrefix.push_back(_XPLATSTR('.'));
    }

    auto e = fromEnum(m_value);
    multipart->add(ModelBase::toHttpContent(namePrefix, e));
}

bool EcfProgress::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if (!namePrefix.empty() && namePrefix.back() != _XPLATSTR('.'))
    {
        namePrefix.push_back(_XPLATSTR('.'));
    }
    {
        EnumUnderlyingType e;
        ok = ModelBase::fromHttpContent(multipart->getContent(namePrefix), e);
        if (ok)
        {
            auto v = toEnum(e);
            setValue(v);
        }
    }
    return ok;
}

EcfProgress::eEcfProgress EcfProgress::getValue() const
{
   return m_value;
}

void EcfProgress::setValue(EcfProgress::eEcfProgress const value)
{
   m_value = value;
}

EcfProgress::EcfProgress(utility::string_t str){
    setValue( strToEnumMap[str] );
}

}
}
}
}


