/**
 * ECF API
 * ECF API (Electronic Fiscal Receipt).
 *
 * The version of the OpenAPI document: v1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.14.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "ecf-dgii-client/model/EcfReceptorDto_estado.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

EcfReceptorDto_estado::EcfReceptorDto_estado()
{
}

EcfReceptorDto_estado::~EcfReceptorDto_estado()
{
}

void EcfReceptorDto_estado::validate()
{
    // TODO: implement validation
}

web::json::value EcfReceptorDto_estado::toJson() const
{
    web::json::value val = web::json::value::object();

    return val;
}

bool EcfReceptorDto_estado::fromJson(const web::json::value& val)
{
    bool ok = true;
    return ok;
}

void EcfReceptorDto_estado::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
}

bool EcfReceptorDto_estado::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    return ok;
}



}
}
}
}


