/**
 * ECF API
 * ECF API (Electronic Fiscal Receipt).
 *
 * The version of the OpenAPI document: v1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.20.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "ecf-dgii-client/model/IndicadorFacturacionType.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

namespace
{
using EnumUnderlyingType = utility::string_t;

IndicadorFacturacionType::eIndicadorFacturacionType toEnum(const EnumUnderlyingType& val)
{
    if (val == utility::conversions::to_string_t(_XPLATSTR("NoFacturable_18Percent")))
        return IndicadorFacturacionType::eIndicadorFacturacionType::NOFACTURABLE_18PERCENT;
    if (val == utility::conversions::to_string_t(_XPLATSTR("ITBIS1_18Percent")))
        return IndicadorFacturacionType::eIndicadorFacturacionType::ITBIS1_18PERCENT;
    if (val == utility::conversions::to_string_t(_XPLATSTR("ITBIS2_16Percent")))
        return IndicadorFacturacionType::eIndicadorFacturacionType::ITBIS2_16PERCENT;
    if (val == utility::conversions::to_string_t(_XPLATSTR("ITBIS3_0Percent")))
        return IndicadorFacturacionType::eIndicadorFacturacionType::ITBIS3_0PERCENT;
    if (val == utility::conversions::to_string_t(_XPLATSTR("Exento_E")))
        return IndicadorFacturacionType::eIndicadorFacturacionType::EXENTO_E;
    return {};
}

EnumUnderlyingType fromEnum(IndicadorFacturacionType::eIndicadorFacturacionType e)
{
    switch (e)
    {
    case IndicadorFacturacionType::eIndicadorFacturacionType::NOFACTURABLE_18PERCENT:
        return _XPLATSTR("NoFacturable_18Percent");
    case IndicadorFacturacionType::eIndicadorFacturacionType::ITBIS1_18PERCENT:
        return _XPLATSTR("ITBIS1_18Percent");
    case IndicadorFacturacionType::eIndicadorFacturacionType::ITBIS2_16PERCENT:
        return _XPLATSTR("ITBIS2_16Percent");
    case IndicadorFacturacionType::eIndicadorFacturacionType::ITBIS3_0PERCENT:
        return _XPLATSTR("ITBIS3_0Percent");
    case IndicadorFacturacionType::eIndicadorFacturacionType::EXENTO_E:
        return _XPLATSTR("Exento_E");
    default:
        break;
    }
    return {};
}
}

IndicadorFacturacionType::IndicadorFacturacionType()
{
}

IndicadorFacturacionType::~IndicadorFacturacionType()
{
}

void IndicadorFacturacionType::validate()
{
    // TODO: implement validation
}

web::json::value IndicadorFacturacionType::toJson() const
{
    auto val = fromEnum(m_value);
    return web::json::value(val);
}

bool IndicadorFacturacionType::fromJson(const web::json::value& val)
{
    m_value = toEnum(val.as_string());
    return true;
}

void IndicadorFacturacionType::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if (!namePrefix.empty() && namePrefix.back() != _XPLATSTR('.'))
    {
        namePrefix.push_back(_XPLATSTR('.'));
    }

    auto e = fromEnum(m_value);
    multipart->add(ModelBase::toHttpContent(namePrefix, e));
}

bool IndicadorFacturacionType::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if (!namePrefix.empty() && namePrefix.back() != _XPLATSTR('.'))
    {
        namePrefix.push_back(_XPLATSTR('.'));
    }
    {
        EnumUnderlyingType e;
        ok = ModelBase::fromHttpContent(multipart->getContent(namePrefix), e);
        if (ok)
        {
            auto v = toEnum(e);
            setValue(v);
        }
    }
    return ok;
}

IndicadorFacturacionType::eIndicadorFacturacionType IndicadorFacturacionType::getValue() const
{
   return m_value;
}

void IndicadorFacturacionType::setValue(IndicadorFacturacionType::eIndicadorFacturacionType const value)
{
   m_value = value;
}

IndicadorFacturacionType::IndicadorFacturacionType(utility::string_t str){
    setValue( strToEnumMap[str] );
}

}
}
}
}


