/**
 * ECF API
 * ECF API (Electronic Fiscal Receipt).
 *
 * The version of the OpenAPI document: v1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.20.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "ecf-dgii-client/model/Mensaje.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

Mensaje::Mensaje()
{
    m_Codigo = 0;
    m_CodigoIsSet = false;
}

Mensaje::~Mensaje()
{
}

void Mensaje::validate()
{
    // TODO: implement validation
}

web::json::value Mensaje::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_Valor.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("valor"))] = ModelBase::toJson(m_Valor.get());
    }
    if(m_CodigoIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("codigo"))] = ModelBase::toJson(m_Codigo);
    }

    return val;
}

bool Mensaje::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("valor"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("valor")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setValor;
            ok &= ModelBase::fromJson(fieldValue, refVal_setValor);
            setValor(refVal_setValor);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("codigo"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("codigo")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setCodigo;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCodigo);
            setCodigo(refVal_setCodigo);
            
        }
    }
    return ok;
}

void Mensaje::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_Valor.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("valor")), m_Valor.get()));
    }
    if(m_CodigoIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("codigo")), m_Codigo));
    }
}

bool Mensaje::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("valor"))))
    {
        utility::string_t refVal_setValor;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("valor"))), refVal_setValor );
        setValor(refVal_setValor);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("codigo"))))
    {
        int32_t refVal_setCodigo;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("codigo"))), refVal_setCodigo );
        setCodigo(refVal_setCodigo);
    }
    return ok;
}


utility::string_t Mensaje::getValor() const
{
    return m_Valor.get();
}


void Mensaje::setValor(const utility::string_t& value)
{
    m_Valor = value;
}

bool Mensaje::valorIsSet() const
{
    return m_Valor.has_value();
}

void Mensaje::unsetValor()
{
    m_Valor.reset();
}
int32_t Mensaje::getCodigo() const
{
    return m_Codigo;
}

void Mensaje::setCodigo(int32_t value)
{
    m_Codigo = value;
    m_CodigoIsSet = true;
}

bool Mensaje::codigoIsSet() const
{
    return m_CodigoIsSet;
}

void Mensaje::unsetCodigo()
{
    m_CodigoIsSet = false;
}

}
}
}
}


