/**
 * ECF API
 * ECF API (Electronic Fiscal Receipt).
 *
 * The version of the OpenAPI document: v1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.20.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "ecf-dgii-client/model/UpsertCompanyRequest.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

UpsertCompanyRequest::UpsertCompanyRequest()
{
    m_Rnc = utility::conversions::to_string_t("");
    m_RncIsSet = false;
    m_LegalName = utility::conversions::to_string_t("");
    m_LegalNameIsSet = false;
    m_Name = utility::conversions::to_string_t("");
    m_NameIsSet = false;
}

UpsertCompanyRequest::~UpsertCompanyRequest()
{
}

void UpsertCompanyRequest::validate()
{
    // TODO: implement validation
}

web::json::value UpsertCompanyRequest::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_RncIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("rnc"))] = ModelBase::toJson(m_Rnc);
    }
    if(m_LegalNameIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("legalName"))] = ModelBase::toJson(m_LegalName);
    }
    if(m_NameIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("name"))] = ModelBase::toJson(m_Name);
    }

    return val;
}

bool UpsertCompanyRequest::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("rnc"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("rnc")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setRnc;
            ok &= ModelBase::fromJson(fieldValue, refVal_setRnc);
            setRnc(refVal_setRnc);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("legalName"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("legalName")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setLegalName;
            ok &= ModelBase::fromJson(fieldValue, refVal_setLegalName);
            setLegalName(refVal_setLegalName);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("name"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("name")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setName;
            ok &= ModelBase::fromJson(fieldValue, refVal_setName);
            setName(refVal_setName);
            
        }
    }
    return ok;
}

void UpsertCompanyRequest::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_RncIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("rnc")), m_Rnc));
    }
    if(m_LegalNameIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("legalName")), m_LegalName));
    }
    if(m_NameIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("name")), m_Name));
    }
}

bool UpsertCompanyRequest::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("rnc"))))
    {
        utility::string_t refVal_setRnc;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("rnc"))), refVal_setRnc );
        setRnc(refVal_setRnc);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("legalName"))))
    {
        utility::string_t refVal_setLegalName;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("legalName"))), refVal_setLegalName );
        setLegalName(refVal_setLegalName);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("name"))))
    {
        utility::string_t refVal_setName;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("name"))), refVal_setName );
        setName(refVal_setName);
    }
    return ok;
}


utility::string_t UpsertCompanyRequest::getRnc() const
{
    return m_Rnc;
}


void UpsertCompanyRequest::setRnc(const utility::string_t& value)
{
    m_Rnc = value;
    m_RncIsSet = true;
}

bool UpsertCompanyRequest::rncIsSet() const
{
    return m_RncIsSet;
}

void UpsertCompanyRequest::unsetRnc()
{
    m_RncIsSet = false;
}
utility::string_t UpsertCompanyRequest::getLegalName() const
{
    return m_LegalName;
}


void UpsertCompanyRequest::setLegalName(const utility::string_t& value)
{
    m_LegalName = value;
    m_LegalNameIsSet = true;
}

bool UpsertCompanyRequest::legalNameIsSet() const
{
    return m_LegalNameIsSet;
}

void UpsertCompanyRequest::unsetLegalName()
{
    m_LegalNameIsSet = false;
}
utility::string_t UpsertCompanyRequest::getName() const
{
    return m_Name;
}


void UpsertCompanyRequest::setName(const utility::string_t& value)
{
    m_Name = value;
    m_NameIsSet = true;
}

bool UpsertCompanyRequest::nameIsSet() const
{
    return m_NameIsSet;
}

void UpsertCompanyRequest::unsetName()
{
    m_NameIsSet = false;
}

}
}
}
}


