/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dom.com.ssd.ecfx.sdk.models

import dom.com.ssd.ecfx.sdk.models.ECFType
import dom.com.ssd.ecfx.sdk.models.SecuenciaRequest

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param tipoEcf 
 * @param cantidadeNcfAnulados 
 * @param noLinea 
 * @param secuencias 
 */
@Serializable

data class DetalleAnulacionRequest (

    @Contextual @SerialName(value = "tipoEcf")
    val tipoEcf: ECFType,

    @SerialName(value = "cantidadeNcfAnulados")
    val cantidadeNcfAnulados: Int,

    @SerialName(value = "noLinea")
    val noLinea: kotlin.collections.List<Int>,

    @SerialName(value = "secuencias")
    val secuencias: kotlin.collections.List<SecuenciaRequest>

) {


}

