/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dom.com.ssd.ecfx.sdk.models

import dom.com.ssd.ecfx.sdk.models.Ecf33CodificacionTipoImpuestosType

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param tipoImpuesto 
 */
@Serializable

data class Ecf33ImpuestoAdicional (

    @Contextual @SerialName(value = "tipoImpuesto")
    val tipoImpuesto: Ecf33CodificacionTipoImpuestosType

) {


}

