/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dom.com.ssd.ecfx.sdk.models

import dom.com.ssd.ecfx.sdk.models.Ecf31DescuentoORecargoMontoDescuentooRecargo
import dom.com.ssd.ecfx.sdk.models.Ecf31FormaDePagoMontoPago
import dom.com.ssd.ecfx.sdk.models.Ecf31TotalesMontoNoFacturable

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param montoTotal 
 * @param montoExento 
 * @param montoPeriodo 
 * @param saldoAnterior 
 * @param montoAvancePago 
 * @param valorPagar 
 */
@Serializable

data class Ecf43Totales (

    @SerialName(value = "montoTotal")
    val montoTotal: Ecf31FormaDePagoMontoPago,

    @SerialName(value = "montoExento")
    val montoExento: Ecf31DescuentoORecargoMontoDescuentooRecargo? = null,

    @SerialName(value = "montoPeriodo")
    val montoPeriodo: Ecf31TotalesMontoNoFacturable? = null,

    @SerialName(value = "saldoAnterior")
    val saldoAnterior: Ecf31TotalesMontoNoFacturable? = null,

    @SerialName(value = "montoAvancePago")
    val montoAvancePago: Ecf31DescuentoORecargoMontoDescuentooRecargo? = null,

    @SerialName(value = "valorPagar")
    val valorPagar: Ecf31TotalesMontoNoFacturable? = null

) {


}

