/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dom.com.ssd.ecfx.sdk.models

import dom.com.ssd.ecfx.sdk.models.AcecfReceptionRequestDtoProgress
import dom.com.ssd.ecfx.sdk.models.Ecf31DescuentoORecargoMontoDescuentooRecargo
import dom.com.ssd.ecfx.sdk.models.Ecf31FormaDePagoMontoPago
import dom.com.ssd.ecfx.sdk.models.Ecf31ItemCantidadItem
import dom.com.ssd.ecfx.sdk.models.Ecf31ItemPrecioUnitarioItem
import dom.com.ssd.ecfx.sdk.models.Ecf41CodigosItem
import dom.com.ssd.ecfx.sdk.models.Ecf41IndicadorBienoServicioType
import dom.com.ssd.ecfx.sdk.models.Ecf41IndicadorFacturacionType
import dom.com.ssd.ecfx.sdk.models.Ecf41OtraMonedaDetalle
import dom.com.ssd.ecfx.sdk.models.Ecf41Retencion
import dom.com.ssd.ecfx.sdk.models.Ecf41SubDescuento
import dom.com.ssd.ecfx.sdk.models.Ecf41SubRecargo
import dom.com.ssd.ecfx.sdk.models.UnidadMedidaType

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param numeroLinea 
 * @param indicadorFacturacion 
 * @param retencion 
 * @param nombreItem 
 * @param indicadorBienoServicio 
 * @param cantidadItem 
 * @param precioUnitarioItem 
 * @param montoItem 
 * @param tablaCodigosItem 
 * @param descripcionItem 
 * @param unidadMedida 
 * @param fechaElaboracion 
 * @param fechaVencimientoItem 
 * @param descuentoMonto 
 * @param tablaSubDescuento 
 * @param recargoMonto 
 * @param tablaSubRecargo 
 * @param otraMonedaDetalle 
 */
@Serializable

data class Ecf41Item (

    @SerialName(value = "numeroLinea")
    val numeroLinea: AcecfReceptionRequestDtoProgress,

    @Contextual @SerialName(value = "indicadorFacturacion")
    val indicadorFacturacion: Ecf41IndicadorFacturacionType,

    @SerialName(value = "retencion")
    val retencion: Ecf41Retencion,

    @SerialName(value = "nombreItem")
    val nombreItem: kotlin.String,

    @Contextual @SerialName(value = "indicadorBienoServicio")
    val indicadorBienoServicio: Ecf41IndicadorBienoServicioType,

    @SerialName(value = "cantidadItem")
    val cantidadItem: Ecf31ItemCantidadItem,

    @SerialName(value = "precioUnitarioItem")
    val precioUnitarioItem: Ecf31ItemPrecioUnitarioItem,

    @SerialName(value = "montoItem")
    val montoItem: Ecf31FormaDePagoMontoPago,

    @SerialName(value = "tablaCodigosItem")
    val tablaCodigosItem: kotlin.collections.List<Ecf41CodigosItem>? = null,

    @SerialName(value = "descripcionItem")
    val descripcionItem: kotlin.String? = null,

    @Contextual @SerialName(value = "unidadMedida")
    val unidadMedida: UnidadMedidaType? = null,

    @Contextual @SerialName(value = "fechaElaboracion")
    val fechaElaboracion: java.time.OffsetDateTime? = null,

    @Contextual @SerialName(value = "fechaVencimientoItem")
    val fechaVencimientoItem: java.time.OffsetDateTime? = null,

    @SerialName(value = "descuentoMonto")
    val descuentoMonto: Ecf31DescuentoORecargoMontoDescuentooRecargo? = null,

    @SerialName(value = "tablaSubDescuento")
    val tablaSubDescuento: kotlin.collections.List<Ecf41SubDescuento>? = null,

    @SerialName(value = "recargoMonto")
    val recargoMonto: Ecf31DescuentoORecargoMontoDescuentooRecargo? = null,

    @SerialName(value = "tablaSubRecargo")
    val tablaSubRecargo: kotlin.collections.List<Ecf41SubRecargo>? = null,

    @SerialName(value = "otraMonedaDetalle")
    val otraMonedaDetalle: Ecf41OtraMonedaDetalle? = null

) {


}

