<?php
/**
 * Ecf44SubDescuento
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Ecfx\EcfDgii
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ECF API
 *
 * ECF API (Electronic Fiscal Receipt).
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Ecfx\EcfDgii\Model;

use \ArrayAccess;
use \Ecfx\EcfDgii\ObjectSerializer;

/**
 * Ecf44SubDescuento Class Doc Comment
 *
 * @category Class
 * @package  Ecfx\EcfDgii
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class Ecf44SubDescuento implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Ecf44SubDescuento';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'tipo_sub_descuento' => '\Ecfx\EcfDgii\Model\Ecf44TipoDescuentoRecargoType',
        'sub_descuento_porcentaje' => '\Ecfx\EcfDgii\Model\Ecf31DescuentoORecargoValorDescuentooRecargo',
        'monto_sub_descuento' => '\Ecfx\EcfDgii\Model\Ecf31DescuentoORecargoMontoDescuentooRecargo'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'tipo_sub_descuento' => null,
        'sub_descuento_porcentaje' => null,
        'monto_sub_descuento' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'tipo_sub_descuento' => false,
        'sub_descuento_porcentaje' => true,
        'monto_sub_descuento' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'tipo_sub_descuento' => 'tipoSubDescuento',
        'sub_descuento_porcentaje' => 'subDescuentoPorcentaje',
        'monto_sub_descuento' => 'montoSubDescuento'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'tipo_sub_descuento' => 'setTipoSubDescuento',
        'sub_descuento_porcentaje' => 'setSubDescuentoPorcentaje',
        'monto_sub_descuento' => 'setMontoSubDescuento'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'tipo_sub_descuento' => 'getTipoSubDescuento',
        'sub_descuento_porcentaje' => 'getSubDescuentoPorcentaje',
        'monto_sub_descuento' => 'getMontoSubDescuento'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('tipo_sub_descuento', $data ?? [], null);
        $this->setIfExists('sub_descuento_porcentaje', $data ?? [], null);
        $this->setIfExists('monto_sub_descuento', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['tipo_sub_descuento'] === null) {
            $invalidProperties[] = "'tipo_sub_descuento' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets tipo_sub_descuento
     *
     * @return \Ecfx\EcfDgii\Model\Ecf44TipoDescuentoRecargoType
     */
    public function getTipoSubDescuento()
    {
        return $this->container['tipo_sub_descuento'];
    }

    /**
     * Sets tipo_sub_descuento
     *
     * @param \Ecfx\EcfDgii\Model\Ecf44TipoDescuentoRecargoType $tipo_sub_descuento tipo_sub_descuento
     *
     * @return self
     */
    public function setTipoSubDescuento($tipo_sub_descuento)
    {
        if (is_null($tipo_sub_descuento)) {
            throw new \InvalidArgumentException('non-nullable tipo_sub_descuento cannot be null');
        }
        $this->container['tipo_sub_descuento'] = $tipo_sub_descuento;

        return $this;
    }

    /**
     * Gets sub_descuento_porcentaje
     *
     * @return \Ecfx\EcfDgii\Model\Ecf31DescuentoORecargoValorDescuentooRecargo|null
     */
    public function getSubDescuentoPorcentaje()
    {
        return $this->container['sub_descuento_porcentaje'];
    }

    /**
     * Sets sub_descuento_porcentaje
     *
     * @param \Ecfx\EcfDgii\Model\Ecf31DescuentoORecargoValorDescuentooRecargo|null $sub_descuento_porcentaje sub_descuento_porcentaje
     *
     * @return self
     */
    public function setSubDescuentoPorcentaje($sub_descuento_porcentaje)
    {
        if (is_null($sub_descuento_porcentaje)) {
            array_push($this->openAPINullablesSetToNull, 'sub_descuento_porcentaje');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('sub_descuento_porcentaje', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['sub_descuento_porcentaje'] = $sub_descuento_porcentaje;

        return $this;
    }

    /**
     * Gets monto_sub_descuento
     *
     * @return \Ecfx\EcfDgii\Model\Ecf31DescuentoORecargoMontoDescuentooRecargo|null
     */
    public function getMontoSubDescuento()
    {
        return $this->container['monto_sub_descuento'];
    }

    /**
     * Sets monto_sub_descuento
     *
     * @param \Ecfx\EcfDgii\Model\Ecf31DescuentoORecargoMontoDescuentooRecargo|null $monto_sub_descuento monto_sub_descuento
     *
     * @return self
     */
    public function setMontoSubDescuento($monto_sub_descuento)
    {
        if (is_null($monto_sub_descuento)) {
            array_push($this->openAPINullablesSetToNull, 'monto_sub_descuento');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('monto_sub_descuento', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['monto_sub_descuento'] = $monto_sub_descuento;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


