"""ECF DGII Python SDK - Client for the Dominican Republic Electronic Fiscal Receipts API."""

from .client import EcfClient, Environment, ENVIRONMENT_URLS
from .frontend_client import EcfFrontendClient, create_frontend_client
from .exceptions import (
    EcfApiError,
    EcfAuthenticationError,
    EcfForbiddenError,
    EcfNotFoundError,
    EcfProcessingError,
    EcfServerError,
    EcfValidationError,
    PollingMaxRetriesError,
    PollingTimeoutError,
)
from .polling import PollingOptions

# Re-export generated models and enums for convenience
from .generated.client import AuthenticatedClient, Client
from .generated.models import (
    AcecfReceptionRequestDto,
    AllTipoECFTypesType1,
    AnulacionListResponse,
    AnulacionRequest,
    CertificateResponse,
    CompanyResponse,
    DetalleAnulacionRequest,
    DetalleAnulacionRequestDto,
    DGIIEnvironment,
    Directorio,
    Ecf31ECF,
    Ecf32ECF,
    Ecf33ECF,
    Ecf34ECF,
    Ecf41ECF,
    Ecf43ECF,
    Ecf44ECF,
    Ecf45ECF,
    Ecf46ECF,
    Ecf47ECF,
    EcfEstadoType1,
    EcfProgress,
    EcfReceptionRequestDto,
    EcfResponse,
    ECFType,
    FirmarSemillaRequest,
    Mensaje,
    NewCompanyApiKey,
    PaginatedApiResultOfAcecfReceptionRequestDto,
    PaginatedApiResultOfAnulacionListResponse,
    PaginatedApiResultOfCompanyResponse,
    PaginatedApiResultOfEcfReceptionRequestDto,
    PaginatedApiResultOfEcfResponse,
    ProblemDetails,
    RespuestaAnulacionRango,
    RespuestaConsultaEstado,
    RespuestaConsultaRFCE,
    RespuestaConsultaTimbre,
    RespuestaConsultaTrackId,
    RespuestaEstatusServicio,
    RespuestaVentanaDeMantenimiento,
    SecuenciaRequest,
    SendAcecfRequest,
    Token,
    UpsertCompanyRequest,
)

__all__ = [
    # Client
    "EcfClient",
    "EcfFrontendClient",
    "create_frontend_client",
    "Environment",
    "ENVIRONMENT_URLS",
    "PollingOptions",
    # Generated client
    "AuthenticatedClient",
    "Client",
    # Exceptions
    "EcfApiError",
    "EcfAuthenticationError",
    "EcfForbiddenError",
    "EcfNotFoundError",
    "EcfProcessingError",
    "EcfServerError",
    "EcfValidationError",
    "PollingMaxRetriesError",
    "PollingTimeoutError",
    # Models
    "AcecfReceptionRequestDto",
    "AllTipoECFTypesType1",
    "AnulacionListResponse",
    "AnulacionRequest",
    "CertificateResponse",
    "CompanyResponse",
    "DetalleAnulacionRequest",
    "DetalleAnulacionRequestDto",
    "DGIIEnvironment",
    "Directorio",
    "Ecf31ECF",
    "Ecf32ECF",
    "Ecf33ECF",
    "Ecf34ECF",
    "Ecf41ECF",
    "Ecf43ECF",
    "Ecf44ECF",
    "Ecf45ECF",
    "Ecf46ECF",
    "Ecf47ECF",
    "EcfEstadoType1",
    "EcfProgress",
    "EcfReceptionRequestDto",
    "EcfResponse",
    "ECFType",
    "FirmarSemillaRequest",
    "Mensaje",
    "NewCompanyApiKey",
    "PaginatedApiResultOfAcecfReceptionRequestDto",
    "PaginatedApiResultOfAnulacionListResponse",
    "PaginatedApiResultOfCompanyResponse",
    "PaginatedApiResultOfEcfReceptionRequestDto",
    "PaginatedApiResultOfEcfResponse",
    "ProblemDetails",
    "RespuestaAnulacionRango",
    "RespuestaConsultaEstado",
    "RespuestaConsultaRFCE",
    "RespuestaConsultaTimbre",
    "RespuestaConsultaTrackId",
    "RespuestaEstatusServicio",
    "RespuestaVentanaDeMantenimiento",
    "SecuenciaRequest",
    "SendAcecfRequest",
    "Token",
    "UpsertCompanyRequest",
]
